/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "AFHTTPResponseSerializer.h"


__attribute__((visibility("hidden")))
@interface AFPropertyListResponseSerializer : AFHTTPResponseSerializer {
	unsigned _format;
	unsigned _readOptions;
}
@property(assign, nonatomic) unsigned readOptions;	// G=0x270685; S=0x270695; 
@property(assign, nonatomic) unsigned format;	// G=0x270665; S=0x270675; 
+(id)serializerWithFormat:(unsigned)format readOptions:(unsigned)options;	// 0x270189
+(id)serializer;	// 0x270175
-(id)copyWithZone:(NSZone*)zone;	// 0x2705d5
-(void)encodeWithCoder:(id)coder;	// 0x2704c1
-(id)initWithCoder:(id)coder;	// 0x270369
-(id)responseObjectForResponse:(id)response data:(id)data error:(id*)error;	// 0x270281
-(id)init;	// 0x2701e5
@end

