/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AliSecXLocalStorage : XXUnknownSuperclass {
}
+(id)getFirstLevelFolderPath:(int)path;	// 0xd0eba9
+(BOOL)removeFile:(id)file fromFolder:(int)folder withPath:(id)path error:(id*)error;	// 0xd0eb01
+(unsigned long long)getFileSize:(id)size fromFolder:(int)folder withPath:(id)path error:(id*)error;	// 0xd0ea59
+(id)getDocumentsFolderFileListFromFolder:(int)folder withPath:(id)path error:(id*)error;	// 0xd0e9b1
+(BOOL)createFile:(id)file fromFolder:(int)folder withPath:(id)path error:(id*)error;	// 0xd0e8fd
+(BOOL)isFileExist:(id)exist fromFolder:(int)folder withPath:(id)path;	// 0xd0e851
+(int)saveDataToFile:(id)file Value:(id)value fromFolder:(int)folder withPath:(id)path;	// 0xd0e71d
+(id)loadDataFromFile:(id)file fromFolder:(int)folder withPath:(id)path;	// 0xd0e649
+(BOOL)removeFile:(id)file error:(id*)error;	// 0xd0e5f1
+(id)getDocumentsFolderFileList:(id*)list;	// 0xd0e5d5
+(unsigned long long)getFileSize:(id)size error:(id*)error;	// 0xd0e5b5
+(BOOL)saveDataToFile:(id)file Value:(id)value;	// 0xd0e551
+(id)loadDataFromFile:(id)file;	// 0xd0e4f1
+(BOOL)createFile:(id)file;	// 0xd0e49d
+(BOOL)isFileExist:(id)exist;	// 0xd0e481
+(int)saveDataToKeychain:(id)keychain Value:(id)value;	// 0xd0e3f5
+(id)loadDataFromKeychain:(id)keychain;	// 0xd0e395
+(BOOL)deleteItemFromKeychain:(id)keychain;	// 0xd0e369
+(int)saveStringToKeychain:(id)keychain Value:(id)value;	// 0xd0e2a1
+(id)loadStringFromKeychain:(id)keychain service:(id)service;	// 0xd0e25d
+(id)loadStringFromKeychain:(id)keychain;	// 0xd0e231
+(BOOL)deleteItemFromKeychain:(id)keychain service:(id)service;	// 0xd0e1f5
+(BOOL)deleteItemFromKeychain:(id)keychain error:(id*)error;	// 0xd0e1bd
+(BOOL)saveStringToKeychain:(id)keychain Value:(id)value error:(id*)error;	// 0xd0e105
+(id)loadStringFromKeychain:(id)keychain error:(id*)error;	// 0xd0e0cd
@end

