/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AliSecXCryptoGTMBase64 : XXUnknownSuperclass {
}
+(id)webSafeDecodeString:(id)string;	// 0xd0d061
+(id)stringByWebSafeEncodingBytes:(const void*)bytes length:(unsigned)length padded:(BOOL)padded;	// 0xd0cf35
+(id)stringByWebSafeEncodingData:(id)data padded:(BOOL)padded;	// 0xd0cdc1
+(id)webSafeDecodeBytes:(const void*)bytes length:(unsigned)length;	// 0xd0cd95
+(id)webSafeEncodeBytes:(const void*)bytes length:(unsigned)length padded:(BOOL)padded;	// 0xd0cd69
+(id)webSafeDecodeData:(id)data;	// 0xd0cc51
+(id)webSafeEncodeData:(id)data padded:(BOOL)padded;	// 0xd0cb39
+(id)decodeString:(id)string;	// 0xd0c9f1
+(id)stringByEncodingBytes:(const void*)bytes length:(unsigned)length;	// 0xd0c8c5
+(id)stringByEncodingData:(id)data;	// 0xd0c751
+(id)decodeBytes:(const void*)bytes length:(unsigned)length;	// 0xd0c725
+(id)encodeBytes:(const void*)bytes length:(unsigned)length;	// 0xd0c6f9
+(id)decodeData:(id)data;	// 0xd0c5e1
+(id)encodeData:(id)data;	// 0xd0c4c9
+(unsigned)baseDecode:(const char*)decode srcLen:(unsigned)len destBytes:(char*)bytes destLen:(unsigned)len4 charset:(const char*)charset requirePadding:(BOOL)padding;	// 0xd0d5a5
+(unsigned)baseEncode:(const char*)encode srcLen:(unsigned)len destBytes:(char*)bytes destLen:(unsigned)len4 charset:(const char*)charset padded:(BOOL)padded;	// 0xd0d491
+(id)baseDecode:(const void*)decode length:(unsigned)length charset:(const char*)charset requirePadding:(BOOL)padding;	// 0xd0d321
+(id)baseEncode:(const void*)encode length:(unsigned)length charset:(const char*)charset padded:(BOOL)padded;	// 0xd0d1a9
@end

