/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AliSecXSSKeychain : XXUnknownSuperclass {
}
+(void)setAccessibilityType:(void*)type;	// 0xd0e0a9
+(void*)accessibilityType;	// 0xd0e099
+(id)accountsForService:(id)service;	// 0xd0e015
+(id)allAccounts;	// 0xd0e001
+(BOOL)setPassword:(id)password forService:(id)service account:(id)account error:(id*)error;	// 0xd0df39
+(BOOL)setPassword:(id)password forService:(id)service account:(id)account;	// 0xd0deed
+(BOOL)deletePasswordForService:(id)service account:(id)account error:(id*)error;	// 0xd0de49
+(BOOL)deletePasswordForService:(id)service account:(id)account;	// 0xd0de0d
+(id)passwordForService:(id)service account:(id)account error:(id*)error;	// 0xd0dd49
+(id)passwordForService:(id)service account:(id)account;	// 0xd0dd05
@end

