/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "APayAutoRotateView.h"


@interface APayLoadView : APayAutoRotateView {
}
-(void)layoutSubviews;	// 0xcea99d
-(void)setup;	// 0xcea8c5
-(id)init;	// 0xcea881
-(id)initWithFrame:(CGRect)frame;	// 0xcea829
@end

