/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface AppCommunicate : XXUnknownSuperclass {
}
+(id)appCommunicateDataForAppIDForiOS7Plus:(id)appIDForiOS7Plus;	// 0xcc2dc1
+(id)appCommunicateDataForAppID:(id)appID;	// 0xcc2cf1
+(BOOL)setAppCommunicateDataForiOS7Plus:(id)plus forAppID:(id)appID;	// 0xcc2ca9
+(BOOL)setAppCommunicateData:(id)data forAppID:(id)appID;	// 0xcc2bb9
+(id)fileDataForAppID:(id)appID;	// 0xcc2b4d
+(BOOL)setFileData:(id)data forAppID:(id)appID;	// 0xcc2aa9
+(BOOL)setPropertyListForiOS7Plus:(id)plus forAppID:(id)appID;	// 0xcc29b9
+(BOOL)setPropertyList:(id)list forAppID:(id)appID;	// 0xcc28e1
+(id)propertyListForAppIDForiOS7Plus:(id)appIDForiOS7Plus;	// 0xcc28ad
+(id)propertyListForAppID:(id)appID;	// 0xcc2879
+(id)propertyListForAllAppForiOS7Plus;	// 0xcc2761
+(id)propertyListForAllApp;	// 0xcc2691
+(id)getFilePasteboard;	// 0xcc2639
+(id)getDataPasteboardForiOS7Plus;	// 0xcc261d
+(id)getDataPasteboard;	// 0xcc25c5
+(id)getFilePasteboardName;	// 0xcc25b9
+(id)getDataPasteboardName;	// 0xcc25ad
-(void)dealloc;	// 0xcc2581
-(id)init;	// 0xcc2555
@end

