/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ASSCommon : XXUnknownSuperclass {
}
+(BOOL)useURLWhitelist;	// 0xd0334d
+(id)getServerHost;	// 0xd032d9
+(id)getRPCURL;	// 0xd03289
+(void)setupEnvironmentMode:(int)mode;	// 0xd03279
@end

