/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ASSJsonWrapper : XXUnknownSuperclass {
}
+(id)convertoDictionaryWithJsonString:(id)jsonString;	// 0xcff105
+(id)convertoDictionaryWithJsonData:(id)jsonData;	// 0xcff0b5
+(id)convertToJsonStringWithDictionary:(id)dictionary;	// 0xcff041
+(id)convertToJsonDataWithDictionary:(id)dictionary;	// 0xcfefc5
@end

