/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ASSPerformanceLog : XXUnknownSuperclass {
}
+(void)endTimer:(id)timer;	// 0xd05141
+(void)startTimer;	// 0xd05101
@end

