/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface ASSPhotoInfoCollector : XXUnknownSuperclass {
}
+(id)getDeviceOldPhotoNames;	// 0xd08249
@end

