/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"
#import "PlayerProtocol.h"

@class NSString, NSMutableData, Effect, NSObject, AVAssetReader, AVAssetReaderOutput, AudioProcessPool, AudioGraphEx;
@protocol SongProtocol, OS_dispatch_queue;

@interface AudioProcess : XXUnknownSuperclass <PlayerProtocol> {
	AudioProcessPool* previewPool;
	AudioProcessPool* recordPool;
	AudioProcessPool* savePool;
	double graphSampleRate;
	struct {
		id<SongProtocol> song;
		OpaqueExtAudioFile* file;
		Effect* effect;
		BOOL effectEnable;
		BOOL isRecord;
		long long totalSize;
		double sampleRate;
		BOOL isSilence;
		AVAssetReader* assetReader;
		AVAssetReaderOutput* assetReaderOutput;
		NSMutableData* remainBuf;
	} songs[3];
	float volumes[3];
	AudioGraphEx* recordGraphEx;
	AudioGraphEx* saveGraphEx;
	int songBus;
	int recordBus;
	BOOL recordEnable;
	unsigned long endFlag;
	OpaqueExtAudioFile* savedFile;
	unsigned long long framePlayed;
	int status;
	int prevStatus;
	NSObject<OS_dispatch_queue>* dqueue;
	BOOL isHeadphone;
	void* hugeBuffer;
	BOOL m_isBusy;
	int _pitch;
	float version;
	BOOL _inSeeking;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign) BOOL inSeeking;	// G=0x4a8455; S=0x4a8469; 
@property(assign) BOOL isHeadphone;	// G=0x4a8431; S=0x4a8445; 
@property(readonly, assign) int status;	// G=0x4a8421; 
@property(assign) unsigned long endFlag;	// G=0x4a8401; S=0x4a8411; 
@property(assign) double graphSampleRate;	// G=0x4a8399; S=0x4a83cd; 
-(void)removeObserver:(id)observer forKeyPath:(id)keyPath;	// 0x4a8329
-(void)addObserver:(id)observer forKeyPath:(id)keyPath options:(unsigned)options context:(void*)context;	// 0x4a82b1
-(void)fixIOS7_66628;	// 0x4a8279
-(void)barrier;	// 0x4a8245
-(void)setVersion:(float)version;	// 0x4a8235
-(id)getObserver;	// 0x4a8231
-(void)record:(id)record saveTo:(id)to;	// 0x4a810d
-(void)_record:(id)record saveTo:(id)to;	// 0x4a7c61
-(void)setEQParam:(int)param gain:(float)gain;	// 0x4a7bcd
-(void)setCacheTime:(id)time;	// 0x4a7bc9
-(void)enableBus:(unsigned long)bus isEnable:(BOOL)enable;	// 0x4a7bc5
-(void)enableEffect:(unsigned long)effect enable:(BOOL)enable;	// 0x4a7ba9
-(float)pitch;	// 0x4a7b8d
-(void)setPitch:(float)pitch;	// 0x4a7a51
-(void)setEffectParam:(unsigned long)param param:(id)param2;	// 0x4a7a21
-(void)_setEffectParam:(unsigned long)param param:(id)param2;	// 0x4a7961
-(BOOL)setEffect:(unsigned long)effect effect:(id)effect2;	// 0x4a7919
-(void)setProgress:(float)progress;	// 0x4a76dd
-(float)progress;	// 0x4a7649
-(double)getDuration:(unsigned long)duration;	// 0x4a73f9
-(double)absoluteTime;	// 0x4a73ed
-(double)currentTime;	// 0x4a7395
-(void)setVolume:(float)volume;	// 0x4a7311
-(void)_setVolume:(float)volume;	// 0x4a729d
-(void)setVolume:(unsigned long)volume volume:(float)volume2;	// 0x4a720d
-(void)_setVolume:(unsigned long)volume volume:(float)volume2;	// 0x4a7175
-(float)getVolume:(unsigned long)volume;	// 0x4a7149
-(float)getVolume;	// 0x4a7121
-(void)seek:(unsigned long long)seek time:(float)time;	// 0x4a704d
-(void)resume;	// 0x4a6f49
-(void)pause;	// 0x4a6e3d
-(void)stop;	// 0x4a6d65
-(void)play;	// 0x4a6b51
-(void)silence:(unsigned long)silence;	// 0x4a6ac9
-(void)_stop;	// 0x4a6799
-(void)_seek:(long long)seek time:(float)time;	// 0x4a6475
-(void)_start;	// 0x4a63d1
-(void)finishSaving;	// 0x4a6301
-(long)readAudio:(unsigned long)audio inNumberFrames:(unsigned long)numberFrames ioData:(AudioBufferList*)data;	// 0x4a61d9
-(long)doEffect:(unsigned long)effect bList:(AudioBufferList*)list inNumberFrames:(unsigned long)numberFrames;	// 0x4a6189
-(void)printASBD:(AudioStreamBasicDescription)asbd;	// 0x4a60dd
-(void)createSaveAUGraphEx:(BOOL)ex;	// 0x4a5bf9
-(void)createRecordAUGraphEx;	// 0x4a5699
-(void)saveAudio:(id)audio;	// 0x4a5571
-(void)_saveAudio:(id)audio;	// 0x4a5399
-(BOOL)createSaveFile:(id)file;	// 0x4a5251
-(BOOL)closeSaveFile;	// 0x4a5221
-(void)setupSaveStreamFormat:(unsigned long)format;	// 0x4a5191
-(void)setupStreamFormat;	// 0x4a5119
-(id)initWithSongs:(id)songs recorder:(id)recorder outSampleRate:(double)rate;	// 0x4a50a9
-(void)attachAudio:(unsigned long)audio song:(id)song;	// 0x4a4ff1
-(void)_attachAudio:(unsigned long)audio song:(id)song;	// 0x4a4bf1
-(BOOL)createAsset:(unsigned long)asset;	// 0x4a4859
-(void)dealloc;	// 0x4a46d1
-(id)initWithSampleRate:(double)sampleRate;	// 0x4a4541
-(id)init;	// 0x4a4389
@end

