/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, Verifiedinfo;

__attribute__((visibility("hidden")))
@interface Author : XXUnknownSuperclass {
	BOOL _followed;
	BOOL _verified;
	NSString* _uid;
	NSString* _nickname;
	NSString* _avatar;
	NSString* _location;
	Verifiedinfo* _verifiedInfo;
	int _balance;
}
@property(assign) int balance;	// G=0x2fc5a1; S=0x2fc5b1; 
@property(retain, nonatomic) Verifiedinfo* verifiedInfo;	// G=0x2fc569; S=0x2fc579; 
@property(assign, nonatomic) BOOL verified;	// G=0x2fc549; S=0x2fc559; 
@property(assign, nonatomic) BOOL followed;	// G=0x2fc529; S=0x2fc539; 
@property(retain, nonatomic) NSString* location;	// G=0x2fc4f1; S=0x2fc501; 
@property(retain, nonatomic) NSString* avatar;	// G=0x2fc4b9; S=0x2fc4c9; 
@property(retain, nonatomic) NSString* nickname;	// G=0x2fc481; S=0x2fc491; 
@property(retain, nonatomic) NSString* uid;	// G=0x2fc449; S=0x2fc459; 
+(id)responseWithInfo:(id)info;	// 0x2fc145
-(void).cxx_destruct;	// 0x2fc5c1
@end

