/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSFileHandle, NSObject, VideoEncoder, NSMutableArray;
@protocol OS_dispatch_source, OS_dispatch_queue;

@interface AVEncoder : XXUnknownSuperclass {
	VideoEncoder* _headerWriter;
	VideoEncoder* _writer;
	NSFileHandle* _inputFile;
	NSObject<OS_dispatch_queue>* _readQueue;
	NSObject<OS_dispatch_source>* _readSource;
	BOOL _swapping;
	int _currentFile;
	int _height;
	int _width;
	NSData* _avcC;
	int _lengthSize;
	POCState _pocState;
	int _prevPOC;
	BOOL _foundMDAT;
	unsigned long long _posMDAT;
	int _bytesToNextAtom;
	BOOL _needParams;
	int _prev_nal_idc;
	int _prev_nal_type;
	NSMutableArray* _pendingNALU;
	NSMutableArray* _times;
	NSMutableArray* _frames;
	id _outputBlock;
	id _paramsBlock;
	int _bitspersecond;
	double _firstptsMS;
	long _adaptorHeight;
	long _adaptorWidth;
}
@property(readonly, assign) int bitspersecond;	// G=0x839145; 
+(id)encoderForHeight:(int)height andWidth:(int)width adaptorHeight:(int)height3 adaptorWidth:(int)width4;	// 0x836565
-(id).cxx_construct;	// 0x83923d
-(void).cxx_destruct;	// 0x839155
-(void)shutdown;	// 0x838f55
-(id)getConfigData;	// 0x838f29
-(void)onNALU:(id)nalu;	// 0x838c11
-(void)onEncodedFrame;	// 0x8387b1
-(void)processStoredFrames;	// 0x838471
-(void)deliverFrame:(id)frame withTime:(double)time;	// 0x838209
-(void)onFileUpdate;	// 0x837f95
-(void)readAndDeliver:(unsigned)deliver;	// 0x837db5
-(void)swapFiles:(id)files;	// 0x837a0d
-(void)encodeFrame:(opaqueCMSampleBuffer*)frame fromFile:(BOOL)file;	// 0x83727d
-(void)onParamsCompletion;	// 0x836ff5
-(BOOL)parseParams:(id)params;	// 0x836a95
-(void)encodeWithBlock:(id)block onParams:(id)params;	// 0x8369e1
-(void)initForHeight:(int)height andWidth:(int)width adaptorHeight:(int)height3 adaptorWidth:(int)width4;	// 0x836771
-(id)makeFilename;	// 0x836645
@end

