/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface CreateChatRoomReq : BaseReq {
	NSString* groupId;
	NSString* chatRoomName;
	NSString* extMsg;
	NSString* chatRoomNickName;
}
@property(retain, nonatomic) NSString* extMsg;	// G=0xcc7519; S=0xcc7529; 
@property(retain, nonatomic) NSString* chatRoomNickName;	// G=0xcc754d; S=0xcc755d; 
@property(retain, nonatomic) NSString* chatRoomName;	// G=0xcc74e5; S=0xcc74f5; 
@property(retain, nonatomic) NSString* groupId;	// G=0xcc74b1; S=0xcc74c1; 
-(void)dealloc;	// 0xcc7431
@end

