/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface CustomNaviController : XXUnknownSuperclass {
}
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;	// 0x13f899
-(int)preferredInterfaceOrientationForPresentation;	// 0x13f895
-(unsigned)supportedInterfaceOrientations;	// 0x13f891
-(BOOL)shouldAutorotate;	// 0x13f88d
-(void)didReceiveMemoryWarning;	// 0x13f861
-(void)viewDidAppear:(BOOL)view;	// 0x13f835
-(void)viewDidLoad;	// 0x13f795
@end

