/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface DDLog : XXUnknownSuperclass {
	NSMutableArray* __loggers;
}
@property(retain, nonatomic) NSMutableArray* _loggers;	// G=0xccaf1; S=0xccb01; 
+(void)setLevel:(unsigned)level forClassWithName:(id)name;	// 0xcbdbd
+(void)setLevel:(unsigned)level forClass:(Class)aClass;	// 0xcbd81
+(unsigned)levelForClassWithName:(id)name;	// 0xcbd5d
+(unsigned)levelForClass:(Class)aClass;	// 0xcbd25
+(id)registeredClassNames;	// 0xcbbe9
+(id)registeredClasses;	// 0xcbafd
+(BOOL)isRegisteredClass:(Class)aClass;	// 0xcba75
+(void)flushLog;	// 0xcb9a9
+(void)log:(BOOL)log message:(id)message;	// 0xcb935
+(void)log:(BOOL)log message:(id)message level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag;	// 0xcb7b1
+(void)log:(BOOL)log level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag format:(id)format args:(void*)args;	// 0xcb661
+(void)log:(BOOL)log level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag format:(id)format;	// 0xcb509
+(id)allLoggers;	// 0xcb289
+(void)removeAllLoggers;	// 0xcb1bd
+(void)removeLogger:(id)logger;	// 0xcb095
+(void)addLogger:(id)logger withLevel:(unsigned)level;	// 0xcaf51
+(void)addLogger:(id)logger;	// 0xcaeed
+(id)loggingQueue;	// 0xcaecd
+(void)initialize;	// 0xcad01
+(id)sharedInstance;	// 0xcac41
-(void).cxx_destruct;	// 0xccb29
-(void)lt_flush;	// 0xcc921
-(void)lt_log:(id)log;	// 0xcc589
-(id)lt_allLoggers;	// 0xcc45d
-(void)lt_removeAllLoggers;	// 0xcc28d
-(void)lt_removeLogger:(id)logger;	// 0xcc095
-(void)lt_addLogger:(id)logger level:(unsigned)level;	// 0xcbde5
-(void)flushLog;	// 0xcb9e1
-(void)log:(BOOL)log message:(id)message;	// 0xcb991
-(void)log:(BOOL)log message:(id)message level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag;	// 0xcb839
-(void)log:(BOOL)log level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag format:(id)format args:(void*)args;	// 0xcb6ed
-(void)log:(BOOL)log level:(unsigned)level flag:(unsigned)flag context:(int)context file:(const char*)file function:(const char*)function line:(unsigned)line tag:(id)tag format:(id)format;	// 0xcb5b5
-(void)queueLogMessage:(id)message asynchronously:(BOOL)asynchronously;	// 0xcb3fd
-(id)allLoggers;	// 0xcb2d1
-(void)removeAllLoggers;	// 0xcb1f5
-(void)removeLogger:(id)logger;	// 0xcb0e5
-(void)addLogger:(id)logger withLevel:(unsigned)level;	// 0xcafad
-(void)addLogger:(id)logger;	// 0xcaf3d
-(void)applicationWillTerminate:(id)application;	// 0xcaedd
-(id)init;	// 0xcadf1
@end

