/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableSet, NSArray;

__attribute__((visibility("hidden")))
@interface DDLoggingContextSet : XXUnknownSuperclass {
	int _lock;
	NSMutableSet* _set;
}
@property(readonly, copy) NSArray* currentSet;	// G=0x3a90d9; 
-(void).cxx_destruct;	// 0x3a91a1
-(BOOL)isInSet:(unsigned)set;	// 0x3a9129
-(void)removeFromSet:(unsigned)set;	// 0x3a9065
-(void)addToSet:(unsigned)set;	// 0x3a8ff1
-(id)init;	// 0x3a8f75
@end

