/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "DDLogger.h"
#import "DDAbstractLogger.h"

@class NSString, NSMutableDictionary, NSObject, NSMutableArray;
@protocol OS_dispatch_queue, DDLogFormatter;

__attribute__((visibility("hidden")))
@interface DDTTYLogger : DDAbstractLogger <DDLogger> {
	unsigned _calendarUnitFlags;
	NSString* _appName;
	char* _app;
	unsigned long _appLen;
	NSString* _processID;
	char* _pid;
	unsigned long _pidLen;
	BOOL _colorsEnabled;
	NSMutableArray* _colorProfilesArray;
	NSMutableDictionary* _colorProfilesDict;
	BOOL _automaticallyAppendNewlineForCustomFormatters;
}
@property(readonly, assign, nonatomic) NSString* loggerName;	// G=0x2ccf61; 
@property(readonly, assign, nonatomic) NSObject<OS_dispatch_queue>* loggerQueue;
@property(retain, nonatomic) id<DDLogFormatter> logFormatter;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL automaticallyAppendNewlineForCustomFormatters;	// G=0x2ccf79; S=0x2ccf89; 
@property(assign) BOOL colorsEnabled;	// G=0x2cb445; S=0x2cb5e1; 
+(id)sharedInstance;	// 0x2caf69
+(unsigned)codeIndexForColor:(UIColor*)color;	// 0x2cadfd
+(void)getRed:(float*)red green:(float*)green blue:(float*)blue fromColor:(UIColor*)color;	// 0x2cacdd
+(void)initialize_colors_256;	// 0x2c6d39
+(void)initialize_colors_16;	// 0x2c65e1
-(void).cxx_destruct;	// 0x2ccf99
-(void)logMessage:(id)message;	// 0x2cc819
-(void)clearAllColors;	// 0x2cc659
-(void)clearColorsForAllTags;	// 0x2cc4b1
-(void)clearColorsForAllFlags;	// 0x2cc309
-(void)clearColorsForTag:(id)tag;	// 0x2cc111
-(void)clearColorsForFlag:(unsigned)flag context:(int)context;	// 0x2cbe1d
-(void)clearColorsForFlag:(unsigned)flag;	// 0x2cbe09
-(void)setForegroundColor:(UIColor*)color backgroundColor:(UIColor*)color2 forTag:(id)tag;	// 0x2cbb81
-(void)setForegroundColor:(UIColor*)color backgroundColor:(UIColor*)color2 forFlag:(unsigned)flag context:(int)context;	// 0x2cb7cd
-(void)setForegroundColor:(UIColor*)color backgroundColor:(UIColor*)color2 forFlag:(unsigned)flag;	// 0x2cb78d
-(void)loadDefaultColorProfiles;	// 0x2cb381
-(id)init;	// 0x2cb0d5
@end

