/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UINavigationControllerDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "HJActionSheetDelegate.h"
#import "DSImageCutViewDelegate.h"
#import "DSViewController.h"
#import "UITextFieldDelegate.h"
#import "living-Structs.h"

@class NSString, CustomButton, UITextField, UILabel, UIButton, UIView;

__attribute__((visibility("hidden")))
@interface DSEnrolNameViewController : DSViewController <UITextFieldDelegate, HJActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, DSImageCutViewDelegate> {
	BOOL _hasAvatar;
	NSString* _viewControllerID;
	UIView* _topLine;
	UITextField* _nameField;
	CustomButton* _finishedButton;
	UILabel* _errorView;
	UIButton* _avatarButton;
	UIButton* _cameraButton;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL hasAvatar;	// G=0x405949; S=0x405959; 
@property(retain, nonatomic) UIButton* cameraButton;	// G=0x4040b1; S=0x405921; 
@property(retain, nonatomic) UIButton* avatarButton;	// G=0x403e15; S=0x4058f9; 
@property(retain, nonatomic) UILabel* errorView;	// G=0x404725; S=0x4058d1; 
@property(retain, nonatomic) CustomButton* finishedButton;	// G=0x403c91; S=0x4058a9; 
@property(retain, nonatomic) UITextField* nameField;	// G=0x403a49; S=0x405881; 
@property(retain, nonatomic) UIView* topLine;	// G=0x4039a9; S=0x405859; 
@property(retain, nonatomic) NSString* viewControllerID;	// G=0x405821; S=0x405831; 
-(void).cxx_destruct;	// 0x405969
-(id)getString:(id)string length:(int)length;	// 0x405729
-(int)getLength:(id)length;	// 0x405685
-(BOOL)isChinese:(unsigned short)chinese;	// 0x40564d
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;	// 0x405409
-(BOOL)textFieldShouldReturn:(id)textField;	// 0x405391
-(void)textFieldDidChange:(id)textField;	// 0x40521d
-(void)btnAction:(id)action;	// 0x40490d
-(BOOL)isDeviceAllowed;	// 0x404909
-(void)finishedEnroll;	// 0x404869
-(void)cut_Controller:(id)controller getImage:(id)image;	// 0x4045e9
-(void)imagePickerControllerDidCancel:(id)imagePickerController;	// 0x4045d1
-(void)imagePickerController:(id)controller didFinishPickingMediaWithInfo:(id)info;	// 0x40450d
-(void)actionSheet:(id)sheet clickedButtonIndex:(int)index;	// 0x404435
-(void)modifyTheAvatarImage:(id)image;	// 0x404299
-(void)didReceiveMemoryWarning;	// 0x40397d
-(void)viewWillDisappear:(BOOL)view;	// 0x4038d5
-(void)viewWillAppear:(BOOL)view;	// 0x403785
-(void)onTap;	// 0x40374d
-(void)viewDidLoad;	// 0x403579
-(void)loadView;	// 0x402ded
@end

