/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "DSViewController.h"
#import "UITextFieldDelegate.h"

@class UIImage, NSString, UITextField, UIImageView, UIButton, HJTalkViewController, HJCameraViewController, HJSeedLiveServerResponse;

__attribute__((visibility("hidden")))
@interface DSSessionViewController : DSViewController <UITextFieldDelegate> {
	HJCameraViewController* cameraController;
	UIImageView* imgvVolume;
	HJTalkViewController* talkController;
	BOOL isNeedStop;
	id _CloseButtonClicked;
	NSString* _currentLiveId;
	UITextField* _txtTitle;
	UIButton* _btnGPS;
	UIButton* _btnweibo;
	NSString* _currentSN;
	UIImage* _liveImg;
	NSString* _rotion;
	HJSeedLiveServerResponse* _currentServerResponse;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) HJSeedLiveServerResponse* currentServerResponse;	// G=0x326a69; S=0x326a79; 
@property(copy, nonatomic) NSString* rotion;	// G=0x326a45; S=0x326a59; 
@property(retain, nonatomic) UIImage* liveImg;	// G=0x326a0d; S=0x326a1d; 
@property(copy, nonatomic) NSString* currentSN;	// G=0x3269e9; S=0x3269fd; 
@property(retain, nonatomic) UIButton* btnweibo;	// G=0x3269b1; S=0x3269c1; 
@property(retain, nonatomic) UIButton* btnGPS;	// G=0x326979; S=0x326989; 
@property(retain, nonatomic) UITextField* txtTitle;	// G=0x326941; S=0x326951; 
@property(copy, nonatomic) NSString* currentLiveId;	// G=0x32691d; S=0x326931; 
@property(copy, nonatomic) id CloseButtonClicked;	// G=0x3268f9; S=0x32690d; 
-(void).cxx_destruct;	// 0x326aa1
-(BOOL)prefersStatusBarHidden;	// 0x3268f5
-(void)didReceiveMemoryWarning;	// 0x3268c9
-(void)viewWillDisappear:(BOOL)view;	// 0x326859
-(void)viewWillAppear:(BOOL)view;	// 0x3266c5
-(void)initLive;	// 0x326609
-(void)dealloc;	// 0x32659d
-(id)thumbnailWithImage:(id)image presetSize:(float)size;	// 0x326441
-(void)sessioning;	// 0x325fd5
-(void)refreshVolume:(double)volume;	// 0x325f21
-(void)refreshVolumeChanged:(id)changed;	// 0x325e09
-(void)setupEndSessionView:(id)view;	// 0x325311
-(void)setEndResponse:(id)response;	// 0x324d31
-(BOOL)textFieldShouldReturn:(id)textField;	// 0x324c8d
-(void)setupCreateSessionView;	// 0x322a31
-(void)refreshStartButtonStatus:(int)status;	// 0x322995
-(void)closeSetupCreateSessionView;	// 0x3228e9
-(void)syncWeiboClicked:(id)clicked;	// 0x321f11
-(void)gpsClicked:(id)clicked;	// 0x321435
-(void)submit:(id)submit;	// 0x3212d9
-(void)backHome;	// 0x3211dd
-(void)stopPlayDelay;	// 0x321065
-(void)notificationHandle:(id)handle;	// 0x320e05
-(void)stopLiveByBG;	// 0x320ce5
-(void)setupCamera;	// 0x31fb59
-(void)speedTestFinishedHandle:(int)handle;	// 0x31fa19
-(void)updateLocationButton;	// 0x31f8c1
-(void)viewDidLoad;	// 0x31f7b1
@end

