/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"


__attribute__((visibility("hidden")))
@interface DSTableViewController : XXUnknownSuperclass {
	BOOL _appear;
	UIEdgeInsets _tableInsets;
}
@property(assign, nonatomic, getter=isAppear) BOOL appear;	// G=0x2fab11; S=0x2fab21; 
@property(assign, nonatomic) UIEdgeInsets tableInsets;	// G=0x2faaf9; S=0x2faa89; 
-(void)beginRefreshingTableView;	// 0x2fa88d
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x2fa889
-(int)numberOfSectionsInTableView:(id)tableView;	// 0x2fa885
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;	// 0x2fa879
-(int)preferredInterfaceOrientationForPresentation;	// 0x2fa875
-(unsigned)supportedInterfaceOrientations;	// 0x2fa871
-(BOOL)shouldAutorotate;	// 0x2fa86d
-(void)showTips:(id)tips;	// 0x2fa869
-(void)setTitle:(id)title;	// 0x2fa6dd
-(void)onBack:(id)back;	// 0x2fa699
-(void)setupBackBarButton;	// 0x2fa4e5
-(void)didReceiveMemoryWarning;	// 0x2fa4b9
-(void)setupTableView;	// 0x2fa35d
-(void)doRefreshWhenTabBarChanged;	// 0x2fa359
-(void)handleTabBarNotification:(id)notification;	// 0x2fa1f1
-(void)viewDidLoad;	// 0x2f9fb9
-(id)initWithNibName:(id)nibName bundle:(id)bundle;	// 0x2f9f4d
@end

