/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DTRpcBaseOperation.h"

@class NSMutableDictionary, DTRpcMethod, NSArray;

@interface DTRpcOperation : DTRpcBaseOperation {
	DTRpcMethod* _method;
	NSArray* _params;
	id _resultObject;
	NSMutableDictionary* _userInfo;
	double _startTime;
}
@property(retain, nonatomic) NSMutableDictionary* userInfo;	// G=0xd141f1; S=0xd14201; 
@property(retain, nonatomic) id resultObject;	// G=0xd141cd; S=0xd141dd; 
@property(retain, nonatomic) NSArray* params;	// G=0xd14195; S=0xd141a5; 
@property(retain, nonatomic) DTRpcMethod* method;	// G=0xd1415d; S=0xd1416d; 
@property(assign, nonatomic) double startTime;	// G=0xd14131; S=0xd14149; 
-(void).cxx_destruct;	// 0xd14229
-(void)didFinish;	// 0xd1399d
-(void)didStart;	// 0xd13971
-(id)buildRequestDataWithMethod:(id)method params:(id)params;	// 0xd13781
-(id)copy;	// 0xd136b1
-(void)start;	// 0xd13651
-(id)initWithURL:(id)url method:(id)method params:(id)params;	// 0xd135fd
-(id)initWithURL:(id)url method:(id)method params:(id)params timeout:(double)timeout;	// 0xd132e9
@end

