/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface DTURLCache : XXUnknownSuperclass {
}
+(id)synthesisRequest:(id)request;	// 0xd147c5
+(BOOL)hasETagInResponse:(id)response;	// 0xd14675
+(id)CalculateETag:(id)tag;	// 0xd1460d
+(id)diskPath;	// 0xd14391
+(id)sharedCache;	// 0xd14285
-(id)ETagForRequest:(id)request;	// 0xd144d9
-(void)storeCachedResponse:(id)response forRequest:(id)request;	// 0xd1442d
-(id)cachedResponseForRequest:(id)request;	// 0xd143a9
@end

