/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface Effect : XXUnknownSuperclass {
	void* effect;
}
@property(assign) void* effect;	// G=0x4a4309; S=0x4a4319; 
+(id)createWithEffectName:(id)effectName frameRate:(double)rate;	// 0x4a3d59
+(id)getAllEffectNames;	// 0x4a3cdd
-(id)getClassName;	// 0x4a42cd
-(void)setParam:(id)param;	// 0x4a4185
-(void)setParam:(id)param param:(id)param2;	// 0x4a411d
-(id)getParam:(id)param;	// 0x4a4085
-(void)reset;	// 0x4a4071
-(void)update;	// 0x4a405d
-(long)process:(int*)process inputR:(int*)r outputL:(int*)l outputR:(int*)r4 numsamples:(long)numsamples;	// 0x4a4021
-(long)process:(int*)process outputL:(int*)l outputR:(int*)r numsamples:(long)numsamples;	// 0x4a3fe9
@end

