/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface Feed : XXUnknownSuperclass {
	BOOL _favorited;
	NSString* _title;
	NSString* _image;
	NSString* _praises;
	NSString* _watches;
	NSString* _reposts;
	NSString* _relateid;
	NSString* _publishtime;
	NSString* _location;
	NSString* _replies;
	int _width;
	int _height;
	NSString* _mp4;
	NSString* _device;
	int _duration;
	NSString* _m3u8;
	NSString* _network;
	NSString* _sn;
	NSString* _subtitle;
	int _reward;
}
@property(assign, nonatomic) int reward;	// G=0x720fd; S=0x7210d; 
@property(retain, nonatomic) NSString* subtitle;	// G=0x720c5; S=0x720d5; 
@property(retain, nonatomic) NSString* sn;	// G=0x7208d; S=0x7209d; 
@property(retain, nonatomic) NSString* network;	// G=0x72055; S=0x72065; 
@property(retain, nonatomic) NSString* m3u8;	// G=0x7201d; S=0x7202d; 
@property(assign, nonatomic) int duration;	// G=0x71ffd; S=0x7200d; 
@property(retain, nonatomic) NSString* device;	// G=0x71fc5; S=0x71fd5; 
@property(retain, nonatomic) NSString* mp4;	// G=0x71f8d; S=0x71f9d; 
@property(assign, nonatomic) int height;	// G=0x71f6d; S=0x71f7d; 
@property(assign, nonatomic) int width;	// G=0x71f4d; S=0x71f5d; 
@property(assign, nonatomic) BOOL favorited;	// G=0x71f2d; S=0x71f3d; 
@property(retain, nonatomic) NSString* replies;	// G=0x71ef5; S=0x71f05; 
@property(retain, nonatomic) NSString* location;	// G=0x71ebd; S=0x71ecd; 
@property(retain, nonatomic) NSString* publishtime;	// G=0x71e85; S=0x71e95; 
@property(retain, nonatomic) NSString* relateid;	// G=0x71e4d; S=0x71e5d; 
@property(retain, nonatomic) NSString* reposts;	// G=0x71e15; S=0x71e25; 
@property(retain, nonatomic) NSString* watches;	// G=0x71ddd; S=0x71ded; 
@property(retain, nonatomic) NSString* praises;	// G=0x71da5; S=0x71db5; 
@property(retain, nonatomic) NSString* image;	// G=0x71d6d; S=0x71d7d; 
@property(retain, nonatomic) NSString* title;	// G=0x71d35; S=0x71d45; 
+(id)responseWithInfo:(id)info;	// 0x71605
-(void).cxx_destruct;	// 0x7211d
@end

