/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "QQBaseResp.h"

@class QQApiObject;

__attribute__((visibility("hidden")))
@interface GetMessageFromQQResp : QQBaseResp {
	QQApiObject* message;
}
@property(retain, nonatomic) QQApiObject* message;	// G=0xb51745; S=0xb51755; 
+(id)respWithContent:(id)content;	// 0xb516d5
@end

