/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString, NSURL;

__attribute__((visibility("hidden")))
@interface GiftModel : XXUnknownSuperclass {
	BOOL _selected;
	NSURL* _imageUrl;
	NSDictionary* _property;
	float _price;
	float _discount;
	NSString* _imageString;
	NSString* _giftID;
	NSString* _name;
	NSString* _content;
	NSString* _addTime;
	int _gifttype;
	NSString* _pic;
	int _playCount;
}
@property(assign, nonatomic) int playCount;	// G=0x3e8a01; S=0x3e8a11; 
@property(copy, nonatomic) NSString* pic;	// G=0x3e89dd; S=0x3e89f1; 
@property(assign, nonatomic) BOOL selected;	// G=0x3e89bd; S=0x3e89cd; 
@property(assign, nonatomic) int gifttype;	// G=0x3e899d; S=0x3e89ad; 
@property(copy, nonatomic) NSString* addTime;	// G=0x3e8979; S=0x3e898d; 
@property(copy, nonatomic) NSString* content;	// G=0x3e8955; S=0x3e8969; 
@property(copy, nonatomic) NSString* name;	// G=0x3e8931; S=0x3e8945; 
@property(copy, nonatomic) NSString* giftID;	// G=0x3e890d; S=0x3e8921; 
@property(copy, nonatomic) NSString* imageString;	// G=0x3e88f9; S=0x3e7cc1; 
@property(assign, nonatomic) float discount;	// G=0x3e88d9; S=0x3e88e9; 
@property(assign, nonatomic) float price;	// G=0x3e88b9; S=0x3e88c9; 
@property(retain, nonatomic) NSDictionary* property;	// G=0x3e8881; S=0x3e8891; 
@property(retain, nonatomic) NSURL* imageUrl;	// G=0x3e8849; S=0x3e8859; 
+(id)dictonaryToModel:(id)model;	// 0x3e838d
+(id)resultToModelList:(id)modelList;	// 0x3e823d
+(void)syncGiftListWithSuccess:(id)success failure:(id)failure;	// 0x3e7e35
+(id)getList;	// 0x3e7d89
-(void).cxx_destruct;	// 0x3e8a21
@end

