/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface GMAppleDoubleEntry : XXUnknownSuperclass {
	int entryID_;
	NSData* data_;
}
+(id)entryWithID:(int)anId data:(id)data;	// 0x452201
-(void).cxx_destruct;	// 0x452315
-(id)data;	// 0x452301
-(int)entryID;	// 0x4522f1
-(id)initWithEntryID:(int)entryID data:(id)data;	// 0x45225d
@end

