/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageZoomBlurFilter : GPUImageFilter {
	int blurSizeUniform;
	int blurCenterUniform;
	float _blurSize;
	CGPoint _blurCenter;
}
@property(assign, nonatomic) CGPoint blurCenter;	// G=0x829141; S=0x829091; 
@property(assign, nonatomic) float blurSize;	// G=0x829131; S=0x829039; 
-(void)setInputRotation:(int)rotation atIndex:(int)index;	// 0x828fd5
-(id)init;	// 0x828ef9
@end

