/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageTwoInputFilter.h"


@interface GPUImageLinearBurnBlendFilter : GPUImageTwoInputFilter {
}
-(id)init;	// 0x8188a5
@end

