/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilterGroup.h"

@class GPUImageGrayscaleFilter, GPUImageNonMaximumSuppressionFilter, GPUImage3x3TextureSamplingFilter;

@interface GPUImageFASTCornerDetectionFilter : GPUImageFilterGroup {
	GPUImageGrayscaleFilter* luminanceReductionFilter;
	GPUImage3x3TextureSamplingFilter* featureDetectionFilter;
	GPUImageNonMaximumSuppressionFilter* nonMaximumSuppressionFilter;
}
-(void).cxx_destruct;	// 0x8156fd
-(id)initWithFASTDetectorVariant:(int)fastdetectorVariant;	// 0x8156b5
-(id)init;	// 0x815681
@end

