/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageSobelEdgeDetectionFilter.h"


@interface GPUImageXYDerivativeFilter : GPUImageSobelEdgeDetectionFilter {
}
-(id)init;	// 0x7fb035
@end

