/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImagePerlinNoiseFilter : GPUImageFilter {
	int scaleUniform;
	int colorStartUniform;
	int colorFinishUniform;
	float _scale;
	GPUVector4 _colorStart;
	GPUVector4 _colorFinish;
}
@property(assign, nonatomic) float scale;	// G=0x8177d5; S=0x817695; 
@property(assign, nonatomic) GPUVector4 colorFinish;	// G=0x8177fd; S=0x817761; 
@property(assign, nonatomic) GPUVector4 colorStart;	// G=0x8177e5; S=0x8176ed; 
-(id)init;	// 0x81756d
@end

