/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageTwoPassTextureSamplingFilter.h"


@interface GPUImageDilationFilter : GPUImageTwoPassTextureSamplingFilter {
}
-(id)init;	// 0x81537d
-(id)initWithRadius:(unsigned)radius;	// 0x815295
@end

