/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImage3x3ConvolutionFilter.h"


@interface GPUImageLaplacianFilter : GPUImage3x3ConvolutionFilter {
}
-(id)init;	// 0x7f8999
@end

