/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageTwoInputFilter.h"


@interface GPUImageAlphaBlendFilter : GPUImageTwoInputFilter {
	int mixUniform;
	float _mix;
}
@property(assign, nonatomic) float mix;	// G=0x828ee9; S=0x828e91; 
-(id)init;	// 0x828df1
@end

