/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageLineGenerator : GPUImageFilter {
	int lineWidthUniform;
	int lineColorUniform;
	float* lineCoordinates;
	float _lineWidth;
}
@property(assign, nonatomic) float lineWidth;	// G=0x80d63d; S=0x80d599; 
-(void)setLineColorRed:(float)red green:(float)green blue:(float)blue;	// 0x80d5e9
-(void)renderToTextureWithVertices:(const float*)vertices textureCoordinates:(const float*)coordinates;	// 0x80d595
-(void)renderLinesFromArray:(float*)array count:(unsigned)count frameTime:(XXStruct_pwHToB)time;	// 0x80d26d
-(void)generateLineCoordinates;	// 0x80d24d
-(void)dealloc;	// 0x80d209
-(id)init;	// 0x80d0bd
@end

