/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageFilter.h"


@interface GPUImageOpacityFilter : GPUImageFilter {
	int opacityUniform;
	float _opacity;
}
@property(assign, nonatomic) float opacity;	// G=0x7f15d5; S=0x7f157d; 
-(id)init;	// 0x7f14dd
@end

