/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageTwoPassTextureSamplingFilter.h"


@interface GPUImageErosionFilter : GPUImageTwoPassTextureSamplingFilter {
}
-(id)init;	// 0x7eab75
-(id)initWithRadius:(unsigned)radius;	// 0x7eaa7d
@end

