/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "IFImageFilter.h"


__attribute__((visibility("hidden")))
@interface GPUImageGodLightFilter : IFImageFilter {
	int mtimeUniform;
	int eyeaUniform;
	int eyebUniform;
	int noseUniform;
	int detectUniform;
	CGPoint eyeaHis[4];
	CGPoint eyebHis[4];
	float _mtime;
	float _mdetect;
	CGPoint _meyea;
	CGPoint _meyeb;
	CGPoint _mnose;
}
@property(assign, nonatomic) CGPoint mnose;	// G=0x201d49; S=0x201bd5; 
@property(assign, nonatomic) CGPoint meyeb;	// G=0x201d2d; S=0x201b2d; 
@property(assign, nonatomic) CGPoint meyea;	// G=0x201d11; S=0x201a85; 
@property(assign, nonatomic) float mdetect;	// G=0x201d01; S=0x201c31; 
@property(assign, nonatomic) float mtime;	// G=0x201cf1; S=0x201a2d; 
-(CGPoint)smooth:(CGPoint)smooth withHistory:(CGPoint*)history;	// 0x201985
-(id)initWithPrepareBlock:(id)prepareBlock;	// 0x201879
@end

