/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilterGroup.h"

@class GPUImageParallelCoordinateLineTransformFilter, GPUImageThresholdedNonMaximumSuppressionFilter, NSMutableArray;

@interface GPUImageHoughTransformLineDetector : GPUImageFilterGroup {
	GPUImageOutput<GPUImageInput>* thresholdEdgeDetectionFilter;
	GPUImageParallelCoordinateLineTransformFilter* parallelCoordinateLineTransformFilter;
	GPUImageThresholdedNonMaximumSuppressionFilter* nonMaximumSuppressionFilter;
	float* linesArray;
	char* rawImagePixels;
	id linesDetectedBlock;
	float edgeThreshold;
	float lineDetectionThreshold;
	NSMutableArray* _intermediateImages;
}
@property(readonly, assign, nonatomic) NSMutableArray* intermediateImages;	// G=0x83e4d9; 
@property(copy, nonatomic) id linesDetectedBlock;	// G=0x83e495; S=0x83e4a9; 
@property(assign, nonatomic) float lineDetectionThreshold;	// G=0x83e475; S=0x83e455; 
@property(assign, nonatomic) float edgeThreshold;	// G=0x83e4b9; S=0x83e4c9; 
-(void).cxx_destruct;	// 0x83e4e9
-(BOOL)wantsMonochromeInput;	// 0x83e451
-(void)extractLineParametersFromImageAtFrameTime:(XXStruct_pwHToB)frameTime;	// 0x83e1e1
-(void)dealloc;	// 0x83e18d
-(id)init;	// 0x83df11
@end

