/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageMovie.h"

@class AVComposition, AVVideoComposition, AVAudioMix;

@interface GPUImageMovieComposition : GPUImageMovie {
	AVComposition* _compositon;
	AVVideoComposition* _videoComposition;
	AVAudioMix* _audioMix;
}
@property(retain) AVAudioMix* audioMix;	// G=0x7ffc85; S=0x7ffc99; 
@property(retain) AVVideoComposition* videoComposition;	// G=0x7ffc61; S=0x7ffc75; 
@property(retain) AVComposition* compositon;	// G=0x7ffc3d; S=0x7ffc51; 
-(void).cxx_destruct;	// 0x7ffca9
-(id)createAssetReader;	// 0x7ff911
-(id)initWithComposition:(id)composition andVideoComposition:(id)composition2 andAudioMix:(id)mix;	// 0x7ff845
@end

