/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageTwoInputFilter.h"
#import "living-Structs.h"


@interface GPUImageVoroniConsumerFilter : GPUImageTwoInputFilter {
	int sizeUniform;
	CGSize _sizeInPixels;
}
@property(assign, nonatomic) CGSize sizeInPixels;	// G=0x7f12fd; S=0x7f11ed; 
-(id)init;	// 0x7f1165
@end

