/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImage3x3TextureSamplingFilter.h"


@interface GPUImageNonMaximumSuppressionFilter : GPUImage3x3TextureSamplingFilter {
}
-(id)init;	// 0x82ad19
@end

