/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageTransformFilter : GPUImageFilter {
	int transformMatrixUniform;
	int orthographicMatrixUniform;
	GPUMatrix4x4 orthographicMatrix;
	BOOL _ignoreAspectRatio;
	BOOL _anchorTopLeft;
	CGAffineTransform affineTransform;
	CATransform3D _transform3D;
}
@property(assign, nonatomic) BOOL anchorTopLeft;	// G=0x833035; S=0x832fb9; 
@property(assign, nonatomic) BOOL ignoreAspectRatio;	// G=0x833025; S=0x832e8d; 
@property(assign, nonatomic) CATransform3D transform3D;	// G=0x832fe5; S=0x832d65; 
@property(assign, nonatomic) CGAffineTransform affineTransform;	// G=0x832c8d; S=0x832bed; 
-(void)setupFilterForSize:(CGSize)size;	// 0x832abd
-(void)newFrameReadyAtTime:(XXStruct_pwHToB)time atIndex:(int)index;	// 0x832955
-(void)convert3DTransform:(CATransform3D*)transform toMatrix:(GPUMatrix4x4*)matrix;	// 0x832911
-(void)loadOrthoMatrix:(float*)matrix left:(float)left right:(float)right bottom:(float)bottom top:(float)top near:(float)near far:(float)far;	// 0x832855
-(id)init;	// 0x832735
@end

