/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageTwoInputFilter.h"


@interface GPUImageSourceOverBlendFilter : GPUImageTwoInputFilter {
}
-(id)init;	// 0x7fd649
@end

