/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageFilterGroup.h"

@class GPUImageDissolveBlendFilter, GPUImageBuffer;

@interface GPUImageLowPassFilter : GPUImageFilterGroup {
	GPUImageBuffer* bufferFilter;
	GPUImageDissolveBlendFilter* dissolveBlendFilter;
	float filterStrength;
}
@property(assign, nonatomic) float filterStrength;	// G=0x7ec1a5; S=0x7ec185; 
-(void).cxx_destruct;	// 0x7ec2e5
-(void)addTarget:(id)target atTextureLocation:(int)textureLocation;	// 0x7ec1c5
-(id)init;	// 0x7ec001
@end

