/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"

@class NSMutableArray, GPUImageFramebuffer;

@interface GPUImageTwoInputFilter : GPUImageFilter {
	GPUImageFramebuffer* secondInputFramebuffer;
	int filterSecondTextureCoordinateAttribute;
	int filterInputTextureUniform2;
	int inputRotation2;
	XXStruct_pwHToB firstFrameTime;
	XXStruct_pwHToB secondFrameTime;
	BOOL hasSetFirstTexture;
	BOOL hasReceivedFirstFrame;
	BOOL hasReceivedSecondFrame;
	BOOL firstFrameWasVideo;
	BOOL secondFrameWasVideo;
	BOOL firstFrameCheckDisabled;
	BOOL secondFrameCheckDisabled;
	id _prepareBlock;
	BOOL prepared;
	NSMutableArray* auxPics;
}
-(void).cxx_destruct;	// 0x80a339
-(void)newFrameReadyAtTime:(XXStruct_pwHToB)time atIndex:(int)index;	// 0x80a185
-(void)resetAux;	// 0x80a121
-(CGSize)rotatedSize:(CGSize)size forIndex:(int)index;	// 0x80a0d5
-(void)setInputRotation:(int)rotation atIndex:(int)index;	// 0x80a0b1
-(void)setInputSize:(CGSize)size atIndex:(int)index;	// 0x80a02d
-(void)setInputFramebuffer:(id)framebuffer atIndex:(int)index;	// 0x809f89
-(int)nextAvailableTextureIndex;	// 0x809f71
-(void)renderToTextureWithVertices:(const float*)vertices textureCoordinates:(const float*)coordinates;	// 0x809bf1
-(void)disableSecondFrameCheck;	// 0x809bdd
-(void)disableFirstFrameCheck;	// 0x809bc9
-(void)initializeAttributes;	// 0x809b71
-(id)initWithVertexShaderFromString:(id)string fragmentShaderFromString:(id)string2 withPrepareBlock:(id)prepareBlock;	// 0x8098f1
-(id)initWithFragmentShaderFromString:(id)string;	// 0x8098b1
-(id)initWithFragmentShaderFromString:(id)string withPrepareBlock:(id)prepareBlock;	// 0x809859
-(void)addAuxPics:(id)pics;	// 0x809839
@end

