/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilterGroup.h"

@class GPUImageGaussianBlurFilter, GPUImageToonFilter;

@interface GPUImageSmoothToonFilter : GPUImageFilterGroup {
	GPUImageGaussianBlurFilter* blurFilter;
	GPUImageToonFilter* toonFilter;
	float threshold;
	float blurRadiusInPixels;
	float quantizationLevels;
	float texelWidth;
	float texelHeight;
}
@property(assign, nonatomic) float quantizationLevels;	// G=0x80d8fd; S=0x80d8dd; 
@property(assign, nonatomic) float threshold;	// G=0x80d8bd; S=0x80d89d; 
@property(assign, nonatomic) float blurRadiusInPixels;	// G=0x80d7fd; S=0x80d7dd; 
@property(assign, nonatomic) float texelHeight;	// G=0x80d87d; S=0x80d85d; 
@property(assign, nonatomic) float texelWidth;	// G=0x80d83d; S=0x80d81d; 
-(void).cxx_destruct;	// 0x80d91d
-(id)init;	// 0x80d64d
@end

