/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageFilter.h"
#import "living-Structs.h"


@interface GPUImageBulgeDistortionFilter : GPUImageFilter {
	int aspectRatioUniform;
	int radiusUniform;
	int centerUniform;
	int scaleUniform;
	float _aspectRatio;
	float _radius;
	float _scale;
	CGPoint _center;
}
@property(assign, nonatomic) float aspectRatio;	// G=0x809705; S=0x8094e5; 
@property(assign, nonatomic) float scale;	// G=0x809741; S=0x80960d; 
@property(assign, nonatomic) float radius;	// G=0x809731; S=0x8095b5; 
@property(assign, nonatomic) CGPoint center;	// G=0x809715; S=0x809665; 
-(void)setInputRotation:(int)rotation atIndex:(int)index;	// 0x80953d
-(void)setInputSize:(CGSize)size atIndex:(int)index;	// 0x809419
-(void)forceProcessingAtSize:(CGSize)size;	// 0x8093d9
-(void)adjustAspectRatio;	// 0x809369
-(id)init;	// 0x809239
@end

