/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageGaussianBlurFilter.h"


@interface GPUImageBoxBlurFilter : GPUImageGaussianBlurFilter {
}
+(id)fragmentShaderForOptimizedBlurOfRadius:(unsigned)radius sigma:(float)sigma;	// 0x803cb5
+(id)vertexShaderForOptimizedBlurOfRadius:(unsigned)radius sigma:(float)sigma;	// 0x803b85
-(void)setBlurRadiusInPixels:(float)pixels;	// 0x803fb9
-(id)init;	// 0x803ef1
-(void)setupFilterForSize:(CGSize)size;	// 0x803ec1
@end

