/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageFilter.h"


@interface GPUImageContrastFilter : GPUImageFilter {
	int contrastUniform;
	float _contrast;
}
@property(assign, nonatomic) float contrast;	// G=0x8041b1; S=0x804159; 
-(id)init;	// 0x8040b9
@end

