/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageOutput.h"

@class NSObject;
@protocol OS_dispatch_semaphore;

@interface GPUImagePicture : GPUImageOutput {
	CGSize pixelSizeOfImage;
	BOOL hasProcessedImage;
	NSObject<OS_dispatch_semaphore>* imageUpdateSemaphore;
	BOOL _ignorePushToDownStream;
}
@property(assign, nonatomic) BOOL ignorePushToDownStream;	// G=0x7ebdd1; S=0x7ebde1; 
-(void).cxx_destruct;	// 0x7ebdf1
-(void)addTarget:(id)target atTextureLocation:(int)textureLocation;	// 0x7ebd19
-(CGSize)outputImageSize;	// 0x7ebcfd
-(void)processImageUpToFilter:(id)filter withCompletionHandler:(id)completionHandler;	// 0x7ebbe9
-(BOOL)processImageWithCompletionHandler:(id)completionHandler;	// 0x7eb8f9
-(void)processImage;	// 0x7eb8e5
-(void)removeAllTargets;	// 0x7eb8a5
-(void)dealloc;	// 0x7eb845
-(id)initWithCGImage:(CGImageRef)cgimage smoothlyScaleOutput:(BOOL)output;	// 0x7eb389
-(id)initWithImage:(id)image smoothlyScaleOutput:(BOOL)output;	// 0x7eb335
-(id)initWithCGImage:(CGImageRef)cgimage;	// 0x7eb305
-(id)initWithImage:(id)image;	// 0x7eb2d5
-(id)initWithData:(id)data;	// 0x7eb24d
-(id)initWithURL:(id)url;	// 0x7eb1c5
-(void)replaceTextureWithSubCGImage:(CGImageRef)subCGImage inRect:(CGRect)rect;	// 0x8044a1
-(void)replaceTextureWithSubimage:(id)subimage inRect:(CGRect)rect;	// 0x804441
-(void)replaceTextureWithSubCGImage:(CGImageRef)subCGImage;	// 0x8043cd
-(void)replaceTextureWithSubimage:(id)subimage;	// 0x804385
@end

