/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageFilter.h"


@interface GPUImageGrayscaleFilter : GPUImageFilter {
}
-(id)init;	// 0x809799
-(BOOL)providesMonochromeOutput;	// 0x809795
-(BOOL)wantsMonochromeInput;	// 0x809791
-(void)renderToTextureWithVertices:(const float*)vertices textureCoordinates:(const float*)coordinates;	// 0x809751
@end

