/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageMotionBlurFilter : GPUImageFilter {
	int directionalTexelStepUniform;
	float _blurSize;
	float _blurAngle;
}
@property(assign, nonatomic) float blurAngle;	// G=0x816d89; S=0x816d39; 
@property(assign, nonatomic) float blurSize;	// G=0x816d79; S=0x816d59; 
-(void)setInputRotation:(int)rotation atIndex:(int)index;	// 0x816cf9
-(void)recalculateTexelOffsets;	// 0x816b61
-(void)setInputSize:(CGSize)size atIndex:(int)index;	// 0x816a91
-(id)init;	// 0x8169d1
@end

