/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, GPUImageOutput, NSMutableArray;
@protocol GPUImageInput;

@interface GPUImageFilterPipeline : XXUnknownSuperclass {
	NSString* stringValue;
	NSMutableArray* _filters;
	GPUImageOutput* _input;
	id<GPUImageInput> _output;
}
@property(retain) id<GPUImageInput> output;	// G=0x805f15; S=0x805f29; 
@property(retain) GPUImageOutput* input;	// G=0x805ef1; S=0x805f05; 
@property(retain) NSMutableArray* filters;	// G=0x805ecd; S=0x805ee1; 
-(void).cxx_destruct;	// 0x805f39
-(CGImageRef)newCGImageFromCurrentFilteredFrame;	// 0x805e85
-(id)currentFilteredFrameWithOrientation:(int)orientation;	// 0x805e2d
-(id)currentFilteredFrame;	// 0x805dd9
-(void)_refreshFilters;	// 0x805c45
-(void)replaceAllFilters:(id)filters;	// 0x805be9
-(void)removeAllFilters;	// 0x805b99
-(void)removeFilterAtIndex:(unsigned)index;	// 0x805b45
-(void)removeFilter:(id)filter;	// 0x805ad9
-(void)replaceFilterAtIndex:(unsigned)index withFilter:(id)filter;	// 0x805a69
-(void)addFilter:(id)filter;	// 0x8059fd
-(void)addFilter:(id)filter atIndex:(unsigned)index;	// 0x80598d
-(id)initWithOrderedFilters:(id)orderedFilters input:(id)input output:(id)output;	// 0x8058a9
-(BOOL)_parseConfiguration:(id)configuration;	// 0x804e99
-(id)initWithConfigurationFile:(id)configurationFile input:(id)input output:(id)output;	// 0x804e09
-(id)initWithConfiguration:(id)configuration input:(id)input output:(id)output;	// 0x804d39
@end

