/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageInput.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, GLProgram, GPUImageFramebuffer;

@interface GPUImageView : XXUnknownSuperclass <GPUImageInput> {
	int inputRotation;
	GPUImageFramebuffer* inputFramebufferForDisplay;
	unsigned displayRenderbuffer;
	unsigned displayFramebuffer;
	GLProgram* displayProgram;
	int displayPositionAttribute;
	int displayTextureCoordinateAttribute;
	int displayInputTextureUniform;
	CGSize inputImageSize;
	float imageVertices[8];
	float backgroundColorRed;
	float backgroundColorGreen;
	float backgroundColorBlue;
	float backgroundColorAlpha;
	CGSize boundsSizeAtFrameBufferEpoch;
	BOOL enabled;
	unsigned aspectRatio;
	int _fillMode;
	CGSize _sizeInPixels;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned aspectRatio;	// G=0x8326b1; S=0x8326c1; 
@property(assign, nonatomic) BOOL enabled;	// G=0x8326e1; S=0x8326f1; 
@property(readonly, assign, nonatomic) CGSize sizeInPixels;	// G=0x832621; 
@property(assign, nonatomic) int fillMode;	// G=0x8326d1; S=0x832691; 
+(const float*)textureCoordinatesForRotation:(int)rotation;	// 0x8321b5
+(Class)layerClass;	// 0x831599
-(void).cxx_destruct;	// 0x832701
-(void)setCurrentlyReceivingMonochromeInput:(BOOL)input;	// 0x83261d
-(BOOL)wantsMonochromeInput;	// 0x832619
-(BOOL)shouldIgnoreUpdatesToThisTarget;	// 0x832615
-(void)endProcessing;	// 0x832611
-(CGSize)maximumOutputSize;	// 0x832539
-(void)setInputSize:(CGSize)size atIndex:(int)index;	// 0x832441
-(void)setInputRotation:(int)rotation atIndex:(int)index;	// 0x832431
-(void)setInputFramebuffer:(id)framebuffer atIndex:(int)index;	// 0x8323e5
-(int)nextAvailableTextureIndex;	// 0x8323e1
-(void)newFrameReadyAtTime:(XXStruct_pwHToB)time atIndex:(int)index;	// 0x8321cd
-(void)setBackgroundColorRed:(float)red green:(float)green blue:(float)blue alpha:(float)alpha;	// 0x832165
-(void)recalculateViewGeometry;	// 0x831fb5
-(void)presentFramebuffer;	// 0x831f59
-(void)setDisplayFramebuffer;	// 0x831ef1
-(void)destroyDisplayFramebuffer;	// 0x831e91
-(void)createDisplayFramebuffer;	// 0x831cf9
-(void)dealloc;	// 0x831c65
-(void)layoutSubviews;	// 0x831afd
-(void)commonInit;	// 0x83166d
-(id)initWithCoder:(id)coder;	// 0x831615
-(id)initWithFrame:(CGRect)frame;	// 0x8315b5
@end

