/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageFalseColorFilter : GPUImageFilter {
	int firstColorUniform;
	int secondColorUniform;
	GPUVector4 _secondColor;
	GPUVector4 _firstColor;
}
@property(assign, nonatomic) GPUVector4 secondColor;	// G=0x80d08d; S=0x80cfa1; 
@property(assign, nonatomic) GPUVector4 firstColor;	// G=0x80d0a5; S=0x80cf5d; 
-(void)setSecondColorRed:(float)red green:(float)green blue:(float)blue;	// 0x80d039
-(void)setFirstColorRed:(float)red green:(float)green blue:(float)blue;	// 0x80cfe5
-(id)init;	// 0x80ce69
@end

