/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilterGroup.h"

@class GPUImageGaussianBlurFilter, GPUImageFilter;

@interface GPUImageTiltShiftFilter : GPUImageFilterGroup {
	GPUImageGaussianBlurFilter* blurFilter;
	GPUImageFilter* tiltShiftFilter;
	float blurRadiusInPixels;
	float _focusFallOffRate;
	float _theta;
	float _originX;
	float _originY;
	float _focusRadius;
}
@property(assign, nonatomic) float focusRadius;	// G=0x80ded1; S=0x80ddb1; 
@property(assign, nonatomic) float originY;	// G=0x80dec1; S=0x80de21; 
@property(assign, nonatomic) float originX;	// G=0x80deb1; S=0x80dde9; 
@property(assign, nonatomic) float theta;	// G=0x80dea1; S=0x80de59; 
@property(assign, nonatomic) float focusFallOffRate;	// G=0x80de91; S=0x80dd79; 
@property(assign, nonatomic) float blurRadiusInPixels;	// G=0x80dd59; S=0x80dd39; 
-(void).cxx_destruct;	// 0x80dee1
-(id)init;	// 0x80db41
@end

