/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageExposureFilter : GPUImageFilter {
	int exposureUniform;
	float _exposure;
}
@property(assign, nonatomic) float exposure;	// G=0x8150d5; S=0x81507d; 
-(id)init;	// 0x814fe1
@end

