/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GPUImageTwoInputFilter.h"
#import "living-Structs.h"


@interface GPUImageTwoInputCrossTextureSamplingFilter : GPUImageTwoInputFilter {
	int texelWidthUniform;
	int texelHeightUniform;
	float texelWidth;
	float texelHeight;
	BOOL hasOverriddenImageSizeFactor;
	float _texelWidth;
	float _texelHeight;
}
@property(assign, nonatomic) float texelHeight;	// G=0x7fc9c1; S=0x7fc949; 
@property(assign, nonatomic) float texelWidth;	// G=0x7fc9b1; S=0x7fc8e1; 
-(void)setupFilterForSize:(CGSize)size;	// 0x7fc76d
-(id)initWithFragmentShaderFromString:(id)string;	// 0x7fc6c1
@end

