/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface GPUImageTiltShiftHelperFilter : GPUImageFilter {
	float blurRadiusInPixels;
	float _focusFallOffRate;
	float _theta;
	float _originX;
	float _originY;
	float _focusRadius;
}
@property(assign, nonatomic) float focusRadius;	// G=0x80e139; S=0x80e029; 
@property(assign, nonatomic) float originY;	// G=0x80e129; S=0x80e081; 
@property(assign, nonatomic) float originX;	// G=0x80e119; S=0x80e055; 
@property(assign, nonatomic) float theta;	// G=0x80e109; S=0x80e0ad; 
@property(assign, nonatomic) float focusFallOffRate;	// G=0x80e0f9; S=0x80dffd; 
@property(assign, nonatomic) float blurRadiusInPixels;	// G=0x80e0d9; S=0x80e0e9; 
-(id)init;	// 0x80df15
@end

