/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface GuestTipViewController : XXUnknownSuperclass {
	NSString* _msg;
	UILabel* _label;
}
@property(retain, nonatomic) UILabel* label;	// G=0x327011; S=0x327021; 
@property(retain, nonatomic) NSString* msg;	// G=0x326fd9; S=0x326fe9; 
-(void).cxx_destruct;	// 0x327049
-(void)viewDidLayoutSubviews;	// 0x326ecd
-(void)viewDidLoad;	// 0x326ba1
@end

