/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface GWButtonWithImageOnRight : XXUnknownSuperclass {
}
-(void)sizeToFitWidth;	// 0xb4461
-(CGRect)titleRectForContentRect:(CGRect)contentRect;	// 0xb41e9
-(CGRect)imageRectForContentRect:(CGRect)contentRect;	// 0xb3eb9
@end

