/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface HBReq : BaseReq {
	NSString* nonceStr;
	NSString* package;
	unsigned long timeStamp;
	NSString* sign;
}
@property(retain, nonatomic) NSString* sign;	// G=0xcc69c5; S=0xcc69d5; 
@property(retain, nonatomic) NSString* package;	// G=0xcc6971; S=0xcc6981; 
@property(assign, nonatomic) unsigned long timeStamp;	// G=0xcc69a5; S=0xcc69b5; 
@property(retain, nonatomic) NSString* nonceStr;	// G=0xcc693d; S=0xcc694d; 
@end

