/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJTableViewCell.h"

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface HJAccountAndSecurityCell : HJTableViewCell {
	UIImageView* _iconImageVIew;
	UILabel* _titleLable;
}
@property(assign, nonatomic) __weak UILabel* titleLable;	// G=0xc9b25; S=0xc9b45; 
@property(assign, nonatomic) __weak UIImageView* iconImageVIew;	// G=0xc9af1; S=0xc9b11; 
-(void).cxx_destruct;	// 0xc9b59
-(id)initWithCoder:(id)coder;	// 0xc99fd
@end

