/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "HJBaseUserInfoViewDelegate.h"
#import "HJLiveInfoDelegate.h"

@class UITapGestureRecognizer, HJUserProfilesResponse, NSString, HJAnchorInfoView, UIViewController, NSTimer, UILabel, UIImageView, UIButton, UIView;
@protocol HJAnchorViewDelegate;

__attribute__((visibility("hidden")))
@interface HJAnchorView : XXUnknownSuperclass <UIGestureRecognizerDelegate, HJBaseUserInfoViewDelegate, HJLiveInfoDelegate> {
	UIView* _maskView;
	float _maxWidth;
	UITapGestureRecognizer* _tapDismiss;
	BOOL _beShownNow;
	BOOL _isLiving;
	HJUserProfilesResponse* _userProfiles;
	NSString* _gpsLocation;
	int _anchorType;
	id<HJAnchorViewDelegate> _delegate;
	NSString* _liveId;
	UIViewController* _parentVC;
	id _goToMainPageBlock;
	UIImageView* _bgImageV;
	UILabel* _titleLabel;
	UILabel* _timeLabel;
	UIButton* _avatarView;
	UIView* _containerView;
	HJAnchorInfoView* _anchorInfoView;
	UIButton* _followBtn;
	NSTimer* _timer1;
	NSTimer* _timer2;
	int _count;
	UIButton* _actionButton;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIButton* actionButton;	// G=0x3d8429; S=0x3d8fd5; 
@property(assign, nonatomic) int count;	// G=0x3d8fb5; S=0x3d8fc5; 
@property(retain, nonatomic) NSTimer* timer2;	// G=0x3d8f7d; S=0x3d8f8d; 
@property(retain, nonatomic) NSTimer* timer1;	// G=0x3d8f45; S=0x3d8f55; 
@property(retain, nonatomic) UIButton* followBtn;	// G=0x3d86a1; S=0x3d8f1d; 
@property(retain, nonatomic) HJAnchorInfoView* anchorInfoView;	// G=0x3d8ee5; S=0x3d8ef5; 
@property(retain, nonatomic) UIView* containerView;	// G=0x3d8ead; S=0x3d8ebd; 
@property(retain, nonatomic) UIButton* avatarView;	// G=0x3d8011; S=0x3d8e85; 
@property(retain, nonatomic) UILabel* timeLabel;	// G=0x3d827d; S=0x3d8e5d; 
@property(retain, nonatomic) UILabel* titleLabel;	// G=0x3d84fd; S=0x3d8e35; 
@property(assign, nonatomic) __weak UIImageView* bgImageV;	// G=0x3d8e01; S=0x3d8e21; 
@property(copy, nonatomic) id goToMainPageBlock;	// G=0x3d8ddd; S=0x3d8df1; 
@property(assign, nonatomic) __weak UIViewController* parentVC;	// G=0x3d8da9; S=0x3d8dc9; 
@property(retain, nonatomic) NSString* liveId;	// G=0x3d8d71; S=0x3d8d81; 
@property(assign, nonatomic) BOOL isLiving;	// G=0x3d8d51; S=0x3d8d61; 
@property(assign, nonatomic) __weak id<HJAnchorViewDelegate> delegate;	// G=0x3d8d1d; S=0x3d8d3d; 
@property(assign, nonatomic) int anchorType;	// G=0x3d8cfd; S=0x3d8d0d; 
@property(copy, nonatomic) NSString* gpsLocation;	// G=0x3d8cd9; S=0x3d8ced; 
@property(assign, nonatomic) BOOL beShownNow;	// G=0x3d8cb9; S=0x3d8cc9; 
@property(retain, nonatomic) HJUserProfilesResponse* userProfiles;	// G=0x3d8ca9; S=0x3d5d41; 
-(void).cxx_destruct;	// 0x3d8ffd
-(void)onTapTellHimButton:(id)button user:(id)user;	// 0x3d8c09
-(void)onTapMainPageAction:(id)action user:(id)user;	// 0x3d8b69
-(void)onClickCloseButonInUserInfoView:(id)userInfoView;	// 0x3d8b59
-(void)onAnchorInfoUpdate:(id)update;	// 0x3d8aed
-(void)dealloc;	// 0x3d8a81
-(void)followBtnDidClick:(id)followBtn;	// 0x3d8869
-(void)onTapDetailMask;	// 0x3d7d21
-(void)resetAnchorView;	// 0x3d7cb1
-(void)setTitle:(id)title;	// 0x3d7119
-(void)setLiveTime:(id)time;	// 0x3d66b1
-(void)handleAction:(id)action;	// 0x3d64a1
-(BOOL)gestureRecognizer:(id)recognizer shouldReceiveTouch:(id)touch;	// 0x3d644d
-(id)initWithFrame:(CGRect)frame anchorType:(int)type;	// 0x3d5cc1
-(id)initWithFrame:(CGRect)frame;	// 0x3d5c3d
-(id)uxy_roundedRectWith:(float)with byRoundingCorners:(unsigned)corners;	// 0x3d5ac1
-(void)layoutSubviews;	// 0x3d5a95
-(void)showFollowBtn:(id)btn;	// 0x3d59a5
-(void)autoHideFollowBtn:(id)btn;	// 0x3d586d
-(void)updateAnchorViewFrame:(id)frame;	// 0x3d5725
-(void)stopTimer2;	// 0x3d56d5
-(void)startTimer2;	// 0x3d5665
-(void)stopTimer1;	// 0x3d5615
-(void)startTimer1;	// 0x3d55a5
-(void)commonInit;	// 0x3d5079
@end

