/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJBaseUserInfoView.h"

@class NSString, UILabel;

__attribute__((visibility("hidden")))
@interface HJAnchorInfoView : HJBaseUserInfoView {
	UILabel* _mobileLabel;
	UILabel* _locationLabel;
	NSString* _gpsLocation;
	NSString* _model_alis;
}
@property(retain, nonatomic) NSString* model_alis;	// G=0x23b74d; S=0x23b75d; 
@property(assign, nonatomic) __weak NSString* gpsLocation;	// G=0x23b719; S=0x23b739; 
@property(assign, nonatomic) __weak UILabel* locationLabel;	// G=0x23b6e5; S=0x23b705; 
@property(assign, nonatomic) __weak UILabel* mobileLabel;	// G=0x23b6b1; S=0x23b6d1; 
-(void).cxx_destruct;	// 0x23b785
-(void)doRefreshUI;	// 0x23b5d9
-(void)awakeFromNib;	// 0x23b595
@end

