/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface HJAudienceCell : XXUnknownSuperclass {
	NSArray* aryAudience;
}
+(id)cellWithTableView:(id)tableView withData:(id)data;	// 0x17ec8d
-(void).cxx_destruct;	// 0x17f5bd
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;	// 0x17f58d
-(void)loadData:(id)data;	// 0x17ee4d
-(void)showUserInfo:(id)info;	// 0x17edbd
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;	// 0x17ed4d
-(void)awakeFromNib;	// 0x17ec89
@end

