/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UILabel, UIButton, HJUserIntf, UIView, HJUserProfilesResponse, NSLayoutConstraint, HJUserManager;
@protocol HJBaseUserInfoViewDelegate;

__attribute__((visibility("hidden")))
@interface HJBaseUserInfoView : XXUnknownSuperclass {
	NSString* _uid;
	HJUserIntf* _userIntf;
	HJUserManager* _watchIntf;
	BOOL _isFollowing;
	int _fans;
	BOOL _isAnchor;
	BOOL _hasPunished;
	UIView* _backgroundBorderView;
	UIView* _iconMask;
	UIButton* _iconView;
	UILabel* _nickNameLabel;
	UILabel* _praiseCountLabel;
	UILabel* _fansCountLabel;
	UILabel* _livesCountLabel;
	UIButton* _closeButton;
	UIButton* _followButton;
	UIButton* _mainPageButton;
	UIButton* _tellHimButton;
	UIView* _buttonView;
	NSLayoutConstraint* _middleButtonTrailing;
	NSLayoutConstraint* _middleButtonRightButton;
	UIButton* _locationButton;
	HJUserProfilesResponse* _data;
	id<HJBaseUserInfoViewDelegate> _delegate;
}
@property(assign) BOOL hasPunished;	// G=0x25c811; S=0x25c825; 
@property(assign) BOOL isAnchor;	// G=0x25c7ed; S=0x25c801; 
@property(assign, nonatomic) __weak id<HJBaseUserInfoViewDelegate> delegate;	// G=0x25c7b9; S=0x25c7d9; 
@property(retain, nonatomic) HJUserProfilesResponse* data;	// G=0x25c781; S=0x25c791; 
@property(copy, nonatomic) NSString* uid;	// G=0x25c75d; S=0x25c771; 
@property(assign, nonatomic) __weak UIButton* locationButton;	// G=0x25c729; S=0x25c749; 
@property(assign, nonatomic) __weak NSLayoutConstraint* middleButtonRightButton;	// G=0x25c6f5; S=0x25c715; 
@property(assign, nonatomic) __weak NSLayoutConstraint* middleButtonTrailing;	// G=0x25c6c1; S=0x25c6e1; 
@property(assign, nonatomic) __weak UIView* buttonView;	// G=0x25c68d; S=0x25c6ad; 
@property(assign, nonatomic) __weak UIButton* tellHimButton;	// G=0x25c659; S=0x25c679; 
@property(assign, nonatomic) __weak UIButton* mainPageButton;	// G=0x25c625; S=0x25c645; 
@property(assign, nonatomic) __weak UIButton* followButton;	// G=0x25c5f1; S=0x25c611; 
@property(assign, nonatomic) __weak UIButton* closeButton;	// G=0x25c5bd; S=0x25c5dd; 
@property(assign, nonatomic) __weak UILabel* livesCountLabel;	// G=0x25c589; S=0x25c5a9; 
@property(assign, nonatomic) __weak UILabel* fansCountLabel;	// G=0x25c555; S=0x25c575; 
@property(assign, nonatomic) __weak UILabel* praiseCountLabel;	// G=0x25c521; S=0x25c541; 
@property(assign, nonatomic) __weak UILabel* nickNameLabel;	// G=0x25c4ed; S=0x25c50d; 
@property(assign, nonatomic) __weak UIButton* iconView;	// G=0x25c4b9; S=0x25c4d9; 
@property(assign, nonatomic) __weak UIView* iconMask;	// G=0x25c485; S=0x25c4a5; 
@property(assign, nonatomic) __weak UIView* backgroundBorderView;	// G=0x25c451; S=0x25c471; 
-(void).cxx_destruct;	// 0x25c835
-(void)onClickWatchButton:(id)button;	// 0x25be09
-(void)onSendGiftButtonClick:(id)click;	// 0x25bd59
-(void)onTellHimButton:(id)button;	// 0x25bca9
-(void)onViewMainPageButton:(id)button;	// 0x25bbf9
-(void)onClickCloseButton:(id)button;	// 0x25bb6d
-(void)hideTellHimButton;	// 0x25baa5
-(void)doFetch;	// 0x25b8b1
-(void)doRefreshUI;	// 0x25aef9
-(void)layoutSubviews;	// 0x25ad1d
-(void)awakeFromNib;	// 0x25abe1
-(void)postNotification:(BOOL)notification;	// 0x25ab39
-(void)changeFollow:(BOOL)follow;	// 0x25aab5
-(void)updateWatchButton;	// 0x25a899
-(void)setunfollowedButton;	// 0x25a711
-(void)setFollowedButton;	// 0x25a5a9
@end

