/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJBlockedManager : XXUnknownSuperclass {
}
+(id)shareManager;	// 0x17bddd
-(BOOL)isPlistFileExists;	// 0x17bf8d
-(id)getPlistPath;	// 0x17bec9
-(id)init;	// 0x17be9d
-(void)updateBlockedListSuccess:(id)success failure:(id)failure;	// 0x17bb09
-(void)getBlockedListSuccess:(id)success failure:(id)failure;	// 0x17b899
-(void)user:(id)user inBlockedList:(id)blockedList outBlockedList:(id)list;	// 0x17b509
-(void)unblockUser:(id)user nickname:(id)nickname;	// 0x17b205
-(void)blockUser:(id)user nickname:(id)nickname;	// 0x17abd9
@end

