/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"


__attribute__((visibility("hidden")))
@interface HJChatAchievementCellData : XXUnknownSuperclass {
	int _count;
	CGSize _titleSize;
}
@property(assign, nonatomic) CGSize titleSize;	// G=0x2cd801; S=0x2cd81d; 
@property(assign, nonatomic) int count;	// G=0x2cd7e1; S=0x2cd7f1; 
@end

