/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"

@class HJChatUser;

__attribute__((visibility("hidden")))
@interface HJChatUserJoinCellData : XXUnknownSuperclass {
	HJChatUser* _user;
	CGSize _titleSize;
}
@property(assign, nonatomic) CGSize titleSize;	// G=0x2cd869; S=0x2cd885; 
@property(retain, nonatomic) HJChatUser* user;	// G=0x2cd831; S=0x2cd841; 
-(void).cxx_destruct;	// 0x2cd899
@end

