/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"

@class NSString, HJChatFollowMassage;

__attribute__((visibility("hidden")))
@interface HJChatUserFollowOwnerData : XXUnknownSuperclass {
	HJChatFollowMassage* _user;
	NSString* _target;
	CGSize _titleSize;
}
@property(assign, nonatomic) CGSize titleSize;	// G=0x2cd999; S=0x2cd9b5; 
@property(retain, nonatomic) NSString* target;	// G=0x2cd961; S=0x2cd971; 
@property(retain, nonatomic) HJChatFollowMassage* user;	// G=0x2cd929; S=0x2cd939; 
-(void).cxx_destruct;	// 0x2cd9c9
@end

