/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextViewDelegate.h"
#import "HJLocationManagerDelegate.h"
#import "HJVideoViewDelegate.h"
#import "DSViewController.h"
#import "living-Structs.h"

@class NSDictionary, UIImage, NSString, HJImageUploadModel, UISwitch, NSURL, UILabel, HJTextView, UIButton, UIView;

__attribute__((visibility("hidden")))
@interface HJComposeViewController : DSViewController <UITextViewDelegate, HJLocationManagerDelegate, HJVideoViewDelegate> {
	UIImage* _originalImage;
	UIImage* _smallImage;
	id _imageUploadModelBlock;
	NSURL* _recordedFileURL;
	HJTextView* _textView;
	UIButton* _locationBtn;
	UILabel* _wordCountLabel;
	UISwitch* _locationSwitch;
	UIView* _shareView;
	UIButton* _imageButton;
	HJImageUploadModel* _imageUploadModel;
	UIButton* _wxShare;
	UIButton* _weiboShare;
	UIButton* _qqShare;
	UIButton* _friendsShare;
	NSDictionary* _shareTextDic;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSDictionary* shareTextDic;	// G=0x30c06d; S=0x30c07d; 
@property(retain, nonatomic) UIButton* friendsShare;	// G=0x30c035; S=0x30c045; 
@property(retain, nonatomic) UIButton* qqShare;	// G=0x30bffd; S=0x30c00d; 
@property(retain, nonatomic) UIButton* weiboShare;	// G=0x30bfc5; S=0x30bfd5; 
@property(retain, nonatomic) UIButton* wxShare;	// G=0x30bf8d; S=0x30bf9d; 
@property(retain, nonatomic) HJImageUploadModel* imageUploadModel;	// G=0x30af29; S=0x30bf65; 
@property(assign, nonatomic) __weak UIButton* imageButton;	// G=0x30bf31; S=0x30bf51; 
@property(assign, nonatomic) __weak UIView* shareView;	// G=0x30befd; S=0x30bf1d; 
@property(assign, nonatomic) __weak UISwitch* locationSwitch;	// G=0x30bec9; S=0x30bee9; 
@property(assign, nonatomic) __weak UILabel* wordCountLabel;	// G=0x30be95; S=0x30beb5; 
@property(assign, nonatomic) __weak UIButton* locationBtn;	// G=0x30be61; S=0x30be81; 
@property(assign, nonatomic) __weak HJTextView* textView;	// G=0x30be2d; S=0x30be4d; 
@property(retain, nonatomic) NSURL* recordedFileURL;	// G=0x30bdf5; S=0x30be05; 
@property(copy, nonatomic) id imageUploadModelBlock;	// G=0x30bdd1; S=0x30bde5; 
@property(retain, nonatomic) UIImage* smallImage;	// G=0x30bd99; S=0x30bda9; 
@property(retain, nonatomic) UIImage* originalImage;	// G=0x30bd61; S=0x30bd71; 
-(void).cxx_destruct;	// 0x30c0a5
-(void)playEnd:(id)end;	// 0x30bd4d
-(void)readyStartPlaying:(id)playing;	// 0x30bd39
-(void)removeVideoView:(id)view;	// 0x30bb51
-(void)showBigImg:(id)img;	// 0x30b85d
-(void)onWeiboShare;	// 0x30b701
-(void)onWXShare;	// 0x30b635
-(void)onQQShare;	// 0x30b599
-(void)onFriendsShare;	// 0x30b4cd
-(id)getShareTextByKey:(id)key;	// 0x30b36d
-(void)onLocationSwitchStatusChanged:(BOOL)changed;	// 0x30b369
-(void)onLocationInfoChanged:(id)changed;	// 0x30b0b5
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x30af85
-(void)textDidChange;	// 0x30ae35
-(void)Compose:(id)compose;	// 0x30ad89
-(void)dismissComposeViewController:(id)controller;	// 0x30ac31
-(void)pubishContect;	// 0x30a8fd
-(void)switchValueChanged:(id)changed;	// 0x30a7f9
-(void)tapOnView;	// 0x30a7bd
-(void)viewDidLoad;	// 0x30a391
-(void)viewDidAppear:(BOOL)view;	// 0x30a331
-(void)viewDidDisappear:(BOOL)view;	// 0x30a2c1
-(void)viewWillDisappear:(BOOL)view;	// 0x30a1e9
-(void)setupRightItem;	// 0x30a00d
-(void)viewWillAppear:(BOOL)view;	// 0x309d71
-(void)setupShareButton;	// 0x3087e9
@end

