/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJCoinRankUserInfo : XXUnknownSuperclass {
	NSString* _score;
	NSString* _uid;
	NSString* _avatar;
	NSString* _nickname;
}
@property(retain, nonatomic) NSString* nickname;	// G=0x2951c1; S=0x2951d1; 
@property(retain, nonatomic) NSString* avatar;	// G=0x295189; S=0x295199; 
@property(retain, nonatomic) NSString* uid;	// G=0x295151; S=0x295161; 
@property(retain, nonatomic) NSString* score;	// G=0x295119; S=0x295129; 
-(void).cxx_destruct;	// 0x2951f9
@end

