/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UILabel, UIImageView, NSNumber, UIButton, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface HJCommitSuccessViewController : XXUnknownSuperclass {
	NSString* _tid;
	NSString* _title;
	NSNumber* _money;
	UILabel* _titleLabel;
	UILabel* _alertLabel;
	UIButton* weibo;
	UIButton* qzone;
	UIButton* friend;
	UIButton* QQ;
	UIButton* weixin;
	UIImageView* line;
	UIImageView* reward;
	NSMutableDictionary* _mutableSessions;
}
@property(retain, nonatomic) NSMutableDictionary* mutableSessions;	// G=0xce895; S=0xce8a5; 
-(void).cxx_destruct;	// 0xce8cd
-(void)viewWillDisappear:(BOOL)view;	// 0xce7c5
-(void)didReceiveMemoryWarning;	// 0xce799
-(int)preferredStatusBarStyle;	// 0xce795
-(id)attributedStringForTitle;	// 0xce4f5
-(void)onClickShare:(id)share;	// 0xce279
-(id)imageWithScreenContents;	// 0xce1b1
-(void)viewWillAppear:(BOOL)view;	// 0xce0b5
-(void)viewDidLoad;	// 0xcdb49
@end

