/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITextFieldDelegate.h"

@class NSString, UITextField, UIButton, UIView;

__attribute__((visibility("hidden")))
@interface HJCommentsPublisher : XXUnknownSuperclass <UITextFieldDelegate> {
	UIButton* _sendBtn;
	UITextField* _inputTextField;
	NSString* _qId;
	NSString* _preTitle;
	UIView* _topLine;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIView* topLine;	// G=0x2f1469; S=0x2f1479; 
@property(retain, nonatomic) NSString* preTitle;	// G=0x2f1431; S=0x2f1441; 
@property(retain, nonatomic) NSString* qId;	// G=0x2f13f9; S=0x2f1409; 
@property(assign, nonatomic) __weak UITextField* inputTextField;	// G=0x2f13c5; S=0x2f13e5; 
@property(assign, nonatomic) __weak UIButton* sendBtn;	// G=0x2f1391; S=0x2f13b1; 
-(void).cxx_destruct;	// 0x2f14a1
-(void)textFieldDidChange:(id)textField;	// 0x2f1235
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;	// 0x2f10d9
-(void)onSendBtnClick;	// 0x2f0d65
-(void)setQuoteInfo:(id)info qId:(id)anId;	// 0x2f0bf5
-(void)awakeFromNib;	// 0x2f09fd
@end

