/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, Feeds;

__attribute__((visibility("hidden")))
@interface HJCommentTableViewCell : XXUnknownSuperclass {
	Feeds* _feed;
	float _homeCellHeight;
	NSMutableArray* _labels;
}
@property(retain, nonatomic) NSMutableArray* labels;	// G=0x2d6a19; S=0x2d6a29; 
@property(assign, nonatomic) float homeCellHeight;	// G=0x2d69f9; S=0x2d6a09; 
@property(retain, nonatomic) Feeds* feed;	// G=0x2d69e9; S=0x2d6239; 
-(void).cxx_destruct;	// 0x2d6a51
-(void)setup;	// 0x2d60f1
-(id)initWithFrame:(CGRect)frame;	// 0x2d6099
-(id)initWithCoder:(id)coder;	// 0x2d6055
@end

