/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJCoinRanCellDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UILabel, UIImageView, NSMutableArray, UITableView;
@protocol HJCoinRankViewDelegate;

__attribute__((visibility("hidden")))
@interface HJCoinRankView : XXUnknownSuperclass <UITableViewDelegate, UITableViewDataSource, HJCoinRanCellDelegate> {
	id<HJCoinRankViewDelegate> _delegate;
	UITableView* _rankTableView;
	NSString* _userID;
	NSMutableArray* _dataArr;
	UIImageView* _backGroundImageView;
	UILabel* _toastLabel;
	float _bgViewHeight;
	CGPoint _bgOrignal;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float bgViewHeight;	// G=0x366385; S=0x366145; 
@property(assign, nonatomic) CGPoint bgOrignal;	// G=0x366369; S=0x365e9d; 
@property(retain, nonatomic) UILabel* toastLabel;	// G=0x366331; S=0x366341; 
@property(retain, nonatomic) UIImageView* backGroundImageView;	// G=0x3662f9; S=0x366309; 
@property(retain, nonatomic) NSMutableArray* dataArr;	// G=0x3662c1; S=0x3662d1; 
@property(retain, nonatomic) NSString* userID;	// G=0x3662b1; S=0x364f95; 
@property(retain, nonatomic) UITableView* rankTableView;	// G=0x366279; S=0x366289; 
@property(assign, nonatomic) __weak id<HJCoinRankViewDelegate> delegate;	// G=0x366245; S=0x366265; 
+(id)createCoinRankView;	// 0x364e31
-(void).cxx_destruct;	// 0x366395
-(void)resetBgviewFrame;	// 0x3661b5
-(void)removeSelf;	// 0x366135
-(void)remove;	// 0x365f01
-(void)showInView:(id)view;	// 0x365c31
-(void)viewBetapped;	// 0x365c1d
-(void)didClickUserHead:(id)head;	// 0x365b79
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x365a69
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x365a2d
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x365a25
-(void)setupViews;	// 0x3655a5
-(void)showRankTableView;	// 0x365535
-(void)showBlankToast:(id)toast;	// 0x365491
-(void)fatchData;	// 0x364fe5
-(id)initWithFrame:(CGRect)frame;	// 0x364ee1
@end

