/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJServices.h"
#import "living-Structs.h"


__attribute__((visibility("hidden")))
@interface HJCrashIntf : HJServices {
}
+(id)allocWithZone:(NSZone*)zone;	// 0x2af3fd
+(id)new;	// 0x2af3dd
+(id)sharedIntfs;	// 0x2af309
-(void)crash_uploadData:(id)data success:(id)success failure:(id)failure;	// 0x2af46d
-(id)init;	// 0x2af41d
@end

