/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class LiveFeedExt, UILabel, UIImageView, UIButton;

__attribute__((visibility("hidden")))
@interface HJDiscoveryClipCell : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _nameLabel;
	UIButton* _feedImage;
	UIImageView* _liveIcon;
	UIImageView* _vIcon;
	LiveFeedExt* _data;
}
@property(retain, nonatomic) LiveFeedExt* data;	// G=0x136471; S=0x134f45; 
@property(assign, nonatomic) __weak UIImageView* vIcon;	// G=0x13643d; S=0x13645d; 
@property(assign, nonatomic) __weak UIImageView* liveIcon;	// G=0x136409; S=0x136429; 
@property(assign, nonatomic) __weak UIButton* feedImage;	// G=0x1363d5; S=0x1363f5; 
@property(assign, nonatomic) __weak UILabel* nameLabel;	// G=0x1363a1; S=0x1363c1; 
@property(assign, nonatomic) __weak UILabel* titleLabel;	// G=0x13636d; S=0x13638d; 
+(id)identifier;	// 0x134d1d
+(void)registerCellWithTableView:(id)tableView;	// 0x134ca5
-(void).cxx_destruct;	// 0x136481
-(void)onDescriptionLabelTapped:(id)tapped;	// 0x13627d
-(void)onFeedImageTapped:(id)tapped;	// 0x135845
-(void)prepareForReuse;	// 0x134f05
-(void)reset;	// 0x134dc1
-(void)awakeFromNib;	// 0x134d35
@end

