/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSTableViewController.h"
#import "UIScrollViewDelegate.h"
#import "living-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, HJLoadingView2, LiveFeeds, HJDiscoveryV3Model, UIView, NSMutableArray, HJDiscoverCommandCards, NSIndexPath, YIFullScreenScroll, HJErrorView;

__attribute__((visibility("hidden")))
@interface HJDiscoveryViewControllerV3 : DSTableViewController <UIScrollViewDelegate, UITableViewDataSource, UITableViewDelegate> {
	BOOL _refreshing;
	BOOL _more;
	BOOL _isNeedFull;
	BOOL _bannerEnabled;
	NSMutableArray* _groupArr;
	UIView* _errorView;
	HJErrorView* _theErrorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	NSString* _strOffset;
	LiveFeeds* _liveFeeds;
	NSIndexPath* _preIndex;
	int _preRow;
	YIFullScreenScroll* _fullScreenDelegate;
	UIView* _displayMoreView;
	HJDiscoverCommandCards* _commandScrollView;
	HJDiscoveryV3Model* _discoveryModel;
	int _defaultFeedCount;
	int _recommandCount;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int recommandCount;	// G=0x148b7d; S=0x148b8d; 
@property(assign, nonatomic) int defaultFeedCount;	// G=0x148b5d; S=0x148b6d; 
@property(assign, nonatomic) BOOL bannerEnabled;	// G=0x148b3d; S=0x148b4d; 
@property(retain, nonatomic) HJDiscoveryV3Model* discoveryModel;	// G=0x148b05; S=0x148b15; 
@property(retain, nonatomic) HJDiscoverCommandCards* commandScrollView;	// G=0x148acd; S=0x148add; 
@property(retain, nonatomic) UIView* displayMoreView;	// G=0x148a95; S=0x148aa5; 
@property(assign, nonatomic) BOOL isNeedFull;	// G=0x148a75; S=0x148a85; 
@property(retain, nonatomic) YIFullScreenScroll* fullScreenDelegate;	// G=0x148a3d; S=0x148a4d; 
@property(assign, nonatomic) int preRow;	// G=0x148a1d; S=0x148a2d; 
@property(retain, nonatomic) NSIndexPath* preIndex;	// G=0x1489e5; S=0x1489f5; 
@property(retain, nonatomic) LiveFeeds* liveFeeds;	// G=0x1489ad; S=0x1489bd; 
@property(assign, nonatomic) BOOL more;	// G=0x14898d; S=0x14899d; 
@property(assign, nonatomic) BOOL refreshing;	// G=0x14896d; S=0x14897d; 
@property(retain, nonatomic) NSString* strOffset;	// G=0x148935; S=0x148945; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x1488fd; S=0x14890d; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x145a05; S=0x1488d5; 
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x14889d; S=0x1488ad; 
@property(retain, nonatomic) UIView* errorView;	// G=0x14570d; S=0x148875; 
@property(retain, nonatomic) NSMutableArray* groupArr;	// G=0x146c65; S=0x14884d; 
-(void).cxx_destruct;	// 0x148b9d
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x147e91
-(id)tableView:(id)view viewForHeaderInSection:(int)section;	// 0x14736d
-(float)tableView:(id)view heightForFooterInSection:(int)section;	// 0x147361
-(float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0x14731d
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x147169
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x147025
-(int)numberOfSectionsInTableView:(id)tableView;	// 0x146f8d
-(void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x146ef5
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x146e5d
-(void)scrollViewDidScrollToTop:(id)scrollView;	// 0x146e29
-(BOOL)scrollViewShouldScrollToTop:(id)scrollView;	// 0x146ded
-(void)scrollViewDidScroll:(id)scrollView;	// 0x146db9
-(void)scrollViewWillBeginDragging:(id)scrollView;	// 0x146d35
-(void)pullUpRefreshPath:(id)path currentPath:(id)path2 hasMore:(BOOL)more;	// 0x146bb9
-(void)showLivePage;	// 0x146afd
-(void)checkError:(id)error;	// 0x146a31
-(void)checkEmpty;	// 0x14698d
-(void)viewDidLayoutSubviews;	// 0x14689d
-(void)onTapErrorView:(id)view;	// 0x14687d
-(void)searchHandle:(id)handle;	// 0x14676d
-(void)setupCommandScrollView;	// 0x146479
-(void)pushDiscoveryPeopleVC;	// 0x1463a9
-(void)setupSearch;	// 0x145ce9
-(void)didReceiveMemoryWarning;	// 0x145cbd
-(void)loadImageWall:(BOOL)wall;	// 0x144f11
-(void)loadPopularLive;	// 0x14491d
-(void)refreshPopularLive;	// 0x144681
-(void)loadContents;	// 0x144671
-(void)refresh;	// 0x1445f1
-(void)endRefresh;	// 0x1444b1
-(void)initRefresh;	// 0x144201
-(void)registerCells;	// 0x14417d
-(void)dealloc;	// 0x144111
-(void)viewDidDisappear:(BOOL)view;	// 0x1440e5
-(void)viewWillDisappear:(BOOL)view;	// 0x143fa5
-(void)viewDidAppear:(BOOL)view;	// 0x143f19
-(void)viewWillAppear:(BOOL)view;	// 0x143df5
-(void)viewDidLoad;	// 0x143a29
@end

