/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJDownload : XXUnknownSuperclass {
	BOOL _isNeedUnZip;
	NSString* _identity;
	unsigned _downloadType;
	float _progross;
	NSString* _downloadUrl;
	NSString* _unZipPath;
}
@property(assign, nonatomic) BOOL isNeedUnZip;	// G=0x14a2e5; S=0x14a2f5; 
@property(copy, nonatomic) NSString* unZipPath;	// G=0x14a2c1; S=0x14a2d5; 
@property(copy, nonatomic) NSString* downloadUrl;	// G=0x14a29d; S=0x14a2b1; 
@property(assign, nonatomic) float progross;	// G=0x14a27d; S=0x14a28d; 
@property(assign, nonatomic) unsigned downloadType;	// G=0x14a25d; S=0x14a26d; 
@property(copy, nonatomic) NSString* identity;	// G=0x14a239; S=0x14a24d; 
-(void).cxx_destruct;	// 0x14a305
@end

