/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJEffect : XXUnknownSuperclass {
	NSString* _name;
	NSString* _ID;
	int _type;
	int _loop;
	NSString* _musicName;
	NSMutableArray* _effectImages;
	NSString* _dir;
}
@property(retain, nonatomic) NSString* dir;	// G=0x317611; S=0x317621; 
@property(retain, nonatomic) NSMutableArray* effectImages;	// G=0x3175d9; S=0x3175e9; 
@property(retain, nonatomic) NSString* musicName;	// G=0x3175a1; S=0x3175b1; 
@property(assign, nonatomic) int loop;	// G=0x317581; S=0x317591; 
@property(assign, nonatomic) int type;	// G=0x317561; S=0x317571; 
@property(assign, nonatomic) NSString* ID;	// G=0x317541; S=0x317551; 
@property(retain, nonatomic) NSString* name;	// G=0x317509; S=0x317519; 
-(void).cxx_destruct;	// 0x317649
-(id)initWithJsonString:(id)jsonString dir:(id)dir;	// 0x316d8d
@end

