/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJFaceuOBJ : XXUnknownSuperclass {
	NSString* _faceu_id;
}
@property(retain, nonatomic) NSString* faceu_id;	// G=0x3e3a8d; S=0x3e3a9d; 
-(void).cxx_destruct;	// 0x3e3ac5
@end

