/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface HJFollowHeaderView : XXUnknownSuperclass {
	UILabel* _titleLabel;
	UILabel* _replayCount;
}
@property(assign, nonatomic) __weak UILabel* replayCount;	// G=0x18cbed; S=0x18cc0d; 
@property(assign, nonatomic) __weak UILabel* titleLabel;	// G=0x18cbb9; S=0x18cbd9; 
+(id)headerView;	// 0x18cb31
-(void).cxx_destruct;	// 0x18cc21
@end

