/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJForetellDetailResponse.h"


__attribute__((visibility("hidden")))
@interface HJForetellInfo : HJForetellDetailResponse {
	int _foreTimes;
}
@property(assign, nonatomic) int foreTimes;	// G=0x1b6639; S=0x1b6649; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x1b63b9
@end

