/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJGlobalEmptyCell : XXUnknownSuperclass {
}
+(id)identifier;	// 0x37a695
+(void)registerCellWithTableView:(id)tableView;	// 0x37a61d
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;	// 0x37a6b1
-(void)awakeFromNib;	// 0x37a6ad
@end

