/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJGuardListService : XXUnknownSuperclass {
}
+(id)sharedIntfs;	// 0x1219a5
-(void)getFirstGuardUserInfoWithUserId:(id)userId success:(id)success;	// 0x1220ed
-(void)getGuardRankWithParameters:(id)parameters success:(id)success failure:(id)failure;	// 0x121a65
@end

