/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView, HJImageUploadModel, UIButton, THProgressView;

__attribute__((visibility("hidden")))
@interface HJImageUploadProgressCell : XXUnknownSuperclass {
	UIImageView* _smallImageView;
	UILabel* _statusLabel;
	UIButton* _tryAgainBtn;
	UIButton* _giveUpBtn;
	THProgressView* _progressView;
	HJImageUploadModel* _imageUploadModel;
	id _tryAgainBlock;
	id _cancelBlock;
}
@property(copy, nonatomic) id cancelBlock;	// G=0x6db51; S=0x6db65; 
@property(copy, nonatomic) id tryAgainBlock;	// G=0x6db2d; S=0x6db41; 
@property(retain, nonatomic) HJImageUploadModel* imageUploadModel;	// G=0x6db1d; S=0x6d5a1; 
@property(assign, nonatomic) __weak THProgressView* progressView;	// G=0x6dae9; S=0x6db09; 
@property(assign, nonatomic) __weak UIButton* giveUpBtn;	// G=0x6dab5; S=0x6dad5; 
@property(assign, nonatomic) __weak UIButton* tryAgainBtn;	// G=0x6da81; S=0x6daa1; 
@property(assign, nonatomic) __weak UILabel* statusLabel;	// G=0x6da4d; S=0x6da6d; 
@property(assign, nonatomic) __weak UIImageView* smallImageView;	// G=0x6da19; S=0x6da39; 
+(id)cellWithTableView:(id)tableView;	// 0x6d4e1
-(void).cxx_destruct;	// 0x6db75
-(void)giveUpBtnDidClick:(id)giveUpBtn;	// 0x6d9a9
-(void)tryAgainBtnDidClick:(id)tryAgainBtn;	// 0x6d939
-(void)awakeFromNib;	// 0x6d415
@end

