/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "HJServices.h"
#import "HJServicesConstraits.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface HJInviteUtil : HJServices <HJServicesConstraits> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)allocWithZone:(NSZone*)zone;	// 0x154ad
+(id)new;	// 0x1548d
+(id)sharedIntfs;	// 0x153b9
-(void)invite_activeWithCode:(id)code success:(id)success failure:(id)failure;	// 0x15d51
-(void)invite_getExchangeWithInviteid:(id)inviteid success:(id)success failure:(id)failure;	// 0x15b3d
-(void)invite_getInviteeListOffset:(id)offset success:(id)success failure:(id)failure;	// 0x158e9
-(void)invite_getCodeWithInviter:(id)inviter success:(id)success failure:(id)failure;	// 0x1551d
-(id)init;	// 0x154cd
@end

