/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJMessage.h"

@class NSString, HJVerifiedInfo;

__attribute__((visibility("hidden")))
@interface HJKickOut : HJMessage {
	BOOL _isVerified;
	NSString* _liveid;
	NSString* _userid;
	NSString* _nickname;
	NSString* _avatar;
	HJVerifiedInfo* _verifiedInfo;
	NSString* _level;
	NSString* _exp;
}
@property(copy, nonatomic) NSString* exp;	// G=0x340755; S=0x340769; 
@property(copy, nonatomic) NSString* level;	// G=0x340731; S=0x340745; 
@property(retain, nonatomic) HJVerifiedInfo* verifiedInfo;	// G=0x3406f9; S=0x340709; 
@property(assign, nonatomic) BOOL isVerified;	// G=0x3406d9; S=0x3406e9; 
@property(copy, nonatomic) NSString* avatar;	// G=0x3406b5; S=0x3406c9; 
@property(copy, nonatomic) NSString* nickname;	// G=0x340691; S=0x3406a5; 
@property(copy, nonatomic) NSString* userid;	// G=0x34066d; S=0x340681; 
@property(copy, nonatomic) NSString* liveid;	// G=0x340649; S=0x34065d; 
-(void).cxx_destruct;	// 0x340779
@end

