/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SKScene, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJLaunchAnimView : XXUnknownSuperclass {
	SKScene* _scene;
	NSMutableArray* giftFrames;
}
-(void).cxx_destruct;	// 0xa31f9
-(void)onApplicationNotification:(id)notification;	// 0xa310d
-(void)stopAnim;	// 0xa3069
-(void)startAnimWithType:(int)type;	// 0xa2a99
-(void)startAnimWithType:(int)type completion:(id)completion;	// 0xa2589
-(id)initWithMyFrame:(CGRect)myFrame;	// 0xa22d1
@end

