/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSTableViewController.h"

@class YIFullScreenScroll, UIView, HJLoadingView2, NSMutableArray, HJLeadingRolesResponse, NSIndexPath;

__attribute__((visibility("hidden")))
@interface HJLeadingRoleViewController : DSTableViewController {
	NSMutableArray* leadingRoles;
	int cellHeight;
	int _preRow;
	NSIndexPath* _preIndex;
	long _lastOperationTime;
	BOOL _appear;
	HJLeadingRolesResponse* _lastResp;
	HJLoadingView2* _loadingView;
	UIView* _errorView;
	UIView* _emtpyView;
	YIFullScreenScroll* _fullScreenDelegate;
}
@property(retain, nonatomic) YIFullScreenScroll* fullScreenDelegate;	// G=0x195f99; S=0x195fa9; 
@property(retain, nonatomic) UIView* emtpyView;	// G=0x19442d; S=0x195f71; 
@property(retain, nonatomic) UIView* errorView;	// G=0x194185; S=0x195f49; 
@property(retain, nonatomic) HJLoadingView2* loadingView;	// G=0x1940fd; S=0x195f21; 
@property(retain, nonatomic) HJLeadingRolesResponse* lastResp;	// G=0x195ee9; S=0x195ef9; 
-(void).cxx_destruct;	// 0x195fd1
-(void)didReceiveMemoryWarning;	// 0x195ebd
-(void)scrollViewDidScrollToTop:(id)scrollView;	// 0x195e9d
-(BOOL)scrollViewShouldScrollToTop:(id)scrollView;	// 0x195e7d
-(void)scrollViewDidScroll:(id)scrollView;	// 0x195e41
-(void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x195e21
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;	// 0x195de5
-(void)scrollViewWillBeginDragging:(id)scrollView;	// 0x195d51
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x195d31
-(int)numberOfSectionsInTableView:(id)tableView;	// 0x195d2d
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x195cf1
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x195afd
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x195ac1
-(float)tableView:(id)view heightForFooterInSection:(int)section;	// 0x195ab5
-(float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0x195ab1
-(void)onItemClicked:(id)clicked;	// 0x19590d
-(void)viewDidAppear:(BOOL)view;	// 0x195835
-(void)dealloc;	// 0x1957c9
-(void)viewDidLoad;	// 0x1954f1
-(void)viewWillAppear:(BOOL)view;	// 0x19546d
-(void)viewWillDisappear:(BOOL)view;	// 0x1953e9
-(void)setupSubviews;	// 0x195301
-(void)loadData:(BOOL)data;	// 0x194c99
-(void)hideError;	// 0x194c5d
-(void)showError;	// 0x194bc1
-(void)hideEmpty;	// 0x194b85
-(void)showEmpty;	// 0x194ae9
-(void)hideLoading;	// 0x194a81
-(void)showLoading;	// 0x1948fd
-(void)setupbackgroundImage;	// 0x1946c9
-(void)onTapEmptyView;	// 0x194429
-(void)onTapErrorView;	// 0x194171
-(void)pullUpRefreshPath:(id)path currentPath:(id)path2 hasMore:(BOOL)more;	// 0x19408d
-(void)handleRefresh:(id)refresh;	// 0x194079
-(void)setTitle:(id)title;	// 0x193ef9
-(void)setupRefresh;	// 0x193e5d
-(void)refreshIfNecessary:(id)necessary;	// 0x193ded
-(void)renewLastOperationTime;	// 0x193dd1
@end

