/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@protocol HJLiveWatchEmptyCellDelegate;

__attribute__((visibility("hidden")))
@interface HJLiveWatchEmptyCell : XXUnknownSuperclass {
	id<HJLiveWatchEmptyCellDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<HJLiveWatchEmptyCellDelegate> delegate;	// G=0x13e929; S=0x13e949; 
-(void).cxx_destruct;	// 0x13e95d
-(void)onClickGotoButton:(id)button;	// 0x13e8b5
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;	// 0x13e885
-(void)awakeFromNib;	// 0x13e881
@end

