/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSString, HJSeedAnchorResponse;

__attribute__((visibility("hidden")))
@interface HJLiveCloseParamsModel : XXUnknownSuperclass {
	BOOL _backHome;
	NSString* _relateid;
	UIImage* _snap;
	NSString* _title;
	UIImage* _avatarImage;
	int _playingTime;
	float _balance;
	int _totalAudienceCount;
	int _praiseCount;
	unsigned _chatCount;
	NSString* _signature;
	HJSeedAnchorResponse* _anchor;
}
@property(retain, nonatomic) HJSeedAnchorResponse* anchor;	// G=0x25e2ad; S=0x25e2bd; 
@property(retain, nonatomic) NSString* signature;	// G=0x25e275; S=0x25e285; 
@property(assign, nonatomic) unsigned chatCount;	// G=0x25e255; S=0x25e265; 
@property(assign, nonatomic) int praiseCount;	// G=0x25e235; S=0x25e245; 
@property(assign, nonatomic) int totalAudienceCount;	// G=0x25e215; S=0x25e225; 
@property(assign, nonatomic) float balance;	// G=0x25e1f5; S=0x25e205; 
@property(assign, nonatomic) int playingTime;	// G=0x25e1d5; S=0x25e1e5; 
@property(retain, nonatomic) UIImage* avatarImage;	// G=0x25e19d; S=0x25e1ad; 
@property(retain, nonatomic) NSString* title;	// G=0x25e165; S=0x25e175; 
@property(retain, nonatomic) UIImage* snap;	// G=0x25e12d; S=0x25e13d; 
@property(retain, nonatomic) NSString* relateid;	// G=0x25e0f5; S=0x25e105; 
@property(assign, nonatomic) BOOL backHome;	// G=0x25e0d5; S=0x25e0e5; 
+(id)liveCloseParamsModelWithbackHome:(BOOL)home liveID:(id)anId image:(id)image title:(id)title;	// 0x25dfb5
-(void).cxx_destruct;	// 0x25e2e5
@end

