/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "HJPlaybackDelegate.h"
#import "HJCategorySelectorDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"

@class HJLoadingView2, UISwipeGestureRecognizer, NSMutableDictionary, HJCategorySelectorView, HJSegmentedView, NSString, HJErrorView, NSArray, UIButton, UIView, UIScrollView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJLiveListViewController : XXUnknownSuperclass <UIScrollViewDelegate, HJPlaybackDelegate, HJCategorySelectorDelegate> {
	UIButton* _leftButton;
	NSMutableArray* _views;
	HJSegmentedView* _segmentedView;
	NSMutableDictionary* _itemsMap;
	NSArray* _categories;
	UISwipeGestureRecognizer* _leftswipeGesture;
	UISwipeGestureRecognizer* _rightswipeGesture;
	UIView* _currentView;
	UIScrollView* _scrollView;
	UIView* _errorView;
	HJErrorView* _theErrorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	HJCategorySelectorView* _selectorView;
	UIScrollView* _headerView;
	NSArray* _cats;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSArray* cats;	// G=0x40edf5; S=0x40ee05; 
@property(retain, nonatomic) UIScrollView* headerView;	// G=0x40edbd; S=0x40edcd; 
@property(retain, nonatomic) HJCategorySelectorView* selectorView;	// G=0x40ed85; S=0x40ed95; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x40ed4d; S=0x40ed5d; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x40c8bd; S=0x40ed25; 
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x40eced; S=0x40ecfd; 
@property(retain, nonatomic) UIView* errorView;	// G=0x40c6b1; S=0x40ecc5; 
@property(retain, nonatomic) UIScrollView* scrollView;	// G=0x40ec8d; S=0x40ec9d; 
@property(retain, nonatomic) UIView* currentView;	// G=0x40ec55; S=0x40ec65; 
@property(retain, nonatomic) UISwipeGestureRecognizer* rightswipeGesture;	// G=0x40ec1d; S=0x40ec2d; 
@property(retain, nonatomic) UISwipeGestureRecognizer* leftswipeGesture;	// G=0x40ebe5; S=0x40ebf5; 
@property(retain, nonatomic) NSArray* categories;	// G=0x40ebad; S=0x40ebbd; 
@property(retain, nonatomic) NSMutableDictionary* itemsMap;	// G=0x40eb75; S=0x40eb85; 
@property(retain, nonatomic) HJSegmentedView* segmentedView;	// G=0x40eb3d; S=0x40eb4d; 
@property(retain, nonatomic) NSMutableArray* views;	// G=0x40eb05; S=0x40eb15; 
-(void).cxx_destruct;	// 0x40ee2d
-(void)onCategorySelected:(int)selected Data:(id)data;	// 0x40e375
-(void)onUnFoldBtnClick:(id)click;	// 0x40e241
-(void)refresh;	// 0x40e051
-(void)viewDidLayoutSubviews;	// 0x40df61
-(void)onTapErrorView:(id)view;	// 0x40df51
-(void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x40d939
-(void)scrollViewWillEndDragging:(id)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint*)offset;	// 0x40d935
-(void)scrollViewWillBeginDragging:(id)scrollView;	// 0x40d87d
-(void)notifyContentViews:(unsigned)views;	// 0x40d61d
-(void)handleGesture:(id)gesture;	// 0x40d061
-(void)segmentedViewValueChanged:(id)changed;	// 0x40ce41
-(void)searchHandle:(id)handle;	// 0x40cd85
-(void)setupSearch;	// 0x40cc41
-(void)didReceiveMemoryWarning;	// 0x40cc15
-(void)jumpToLatest:(id)latest;	// 0x40cb31
-(void)loadContents;	// 0x40b7c5
-(void)dealloc;	// 0x40b715
-(void)iconChanged:(id)changed;	// 0x40b591
-(void)viewWillDisappear:(BOOL)view;	// 0x40b345
-(void)viewWillAppear:(BOOL)view;	// 0x40b131
-(void)viewDidLoad;	// 0x40a4dd
-(void)showPrevue;	// 0x40a3f9
-(void)pushToProfileVc;	// 0x409f19
-(void)setupLeftBarItem;	// 0x409c11
-(void)setUpTitleView;	// 0x4098d1
@end

