/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJLogMgr : XXUnknownSuperclass {
}
+(void)doSendRunLog:(id)log mssuccess:(id)mssuccess msfailure:(id)msfailure progress:(id)progress;	// 0xa6d99
+(void)uploadLog:(BOOL)log inBackground:(BOOL)background onOK:(id)ok onFail:(id)fail progress:(id)progress;	// 0xa5fdd
+(void)deleteLogs:(id)logs;	// 0xa5f01
+(id)tempLogFilePaths;	// 0xa5cb1
+(void)moveCrashReportsToTempLogs:(id)tempLogs;	// 0xa5a11
+(id)getErrorLog;	// 0xa5289
+(void)moveDDLogsToTempLogs:(id)tempLogs;	// 0xa5045
+(id)DDLogFilePaths;	// 0xa4ed5
+(id)uploadDir;	// 0xa4d65
+(id)crashReportDir;	// 0xa4bf5
+(void)uploadLogBaseOnStateWithProgress:(id)progress;	// 0xa4b4d
+(void)stopLog;	// 0xa4ad1
+(void)startLog;	// 0xa4a25
+(void)startAppLog;	// 0xa4a21
+(void)appendAppLog:(id)log;	// 0xa48fd
+(void)startSDKLog;	// 0xa48b5
+(id)getAppLogPath;	// 0xa4815
+(id)getTransportLogPath;	// 0xa4775
+(id)getSDKLogPath;	// 0xa46d5
+(void)log:(id)log;	// 0xa44f9
@end

