/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "CLLocationManagerDelegate.h"

@class NSArray, NSString, NSTimer, CLLocationManager, CLGeocoder;

__attribute__((visibility("hidden")))
@interface HJLocationAgent : XXUnknownSuperclass <CLLocationManagerDelegate> {
	int _authorizationStatus;
	id _updateHandler;
	id _updateHandlerForAD;
	id _authUpdateHandler;
	id _authDenyed;
	CLLocationManager* _locationManager;
	NSArray* _locationList;
	CLGeocoder* _adGeocoder;
	NSTimer* _timer;
	XXStruct_zYrK5D _currentPosition;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSTimer* timer;	// G=0x246ce9; S=0x246cf9; 
@property(retain, nonatomic) CLGeocoder* adGeocoder;	// G=0x246cb1; S=0x246cc1; 
@property(retain, nonatomic) NSArray* locationList;	// G=0x246c79; S=0x246c89; 
@property(retain, nonatomic) CLLocationManager* locationManager;	// G=0x246c41; S=0x246c51; 
@property(readonly, assign, nonatomic) int authorizationStatus;	// G=0x246b89; 
@property(copy, nonatomic) id authDenyed;	// G=0x246c1d; S=0x246c31; 
@property(copy, nonatomic) id authUpdateHandler;	// G=0x246bf9; S=0x246c0d; 
@property(readonly, assign, nonatomic) XXStruct_zYrK5D currentPosition;	// G=0x246be1; 
@property(copy, nonatomic) id updateHandlerForAD;	// G=0x246bbd; S=0x246bd1; 
@property(copy, nonatomic) id updateHandler;	// G=0x246b99; S=0x246bad; 
+(id)locationList;	// 0x2466f9
+(XXStruct_zYrK5D)currentLocation;	// 0x2466ad
+(id)sharedLocationAgent;	// 0x245c09
-(void).cxx_destruct;	// 0x246d21
-(void)locationManager:(id)manager didChangeAuthorizationStatus:(int)status;	// 0x246a65
-(void)locationManager:(id)manager didFailWithError:(id)error;	// 0x2469dd
-(void)locationManager:(id)manager didUpdateLocations:(id)locations;	// 0x246865
-(void)locationListWithCompletion:(id)completion;	// 0x246861
-(void)locationManager:(id)manager didUpdateToLocation:(id)location fromLocation:(id)location3;	// 0x246741
-(void)updateLocate;	// 0x24669d
-(void)stopLocate;	// 0x246655
-(void)startLocate;	// 0x246635
-(void)getLocationService:(id)service;	// 0x245f1d
-(void)removeADLocationHandler;	// 0x245f05
-(void)cancelAdGeocoder;	// 0x245ecd
-(void)removeTimer;	// 0x245e95
-(void)addTimer;	// 0x245e21
-(id)init;	// 0x245ce1
@end

