/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MJRefreshAutoGifFooter.h"


__attribute__((visibility("hidden")))
@interface HJLoadFooter : MJRefreshAutoGifFooter {
}
-(void)prepare;	// 0x33cc2d
@end

