/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, UILabel, UIButton, UIView, HJBlurView;

__attribute__((visibility("hidden")))
@interface HJMenuBgView : XXUnknownSuperclass {
	UIView* _btnsView;
	HJBlurView* _blurView;
	UIButton* _picBtn;
	UIButton* _feedBtn;
	UIButton* _closedBtn;
	UILabel* _liveLabel;
	UILabel* _picLabel;
	UILabel* _videoLabel;
	id _closeMenuViewBlock;
	id _uploadImageBlock;
	id _feedingBlock;
	id _videoBlock;
	UIImage* _shotScreenImage;
}
@property(retain, nonatomic) UIImage* shotScreenImage;	// G=0x3d294d; S=0x3d24c9; 
@property(copy, nonatomic) id videoBlock;	// G=0x3d2929; S=0x3d293d; 
@property(copy, nonatomic) id feedingBlock;	// G=0x3d2905; S=0x3d2919; 
@property(copy, nonatomic) id uploadImageBlock;	// G=0x3d28e1; S=0x3d28f5; 
@property(copy, nonatomic) id closeMenuViewBlock;	// G=0x3d28bd; S=0x3d28d1; 
@property(assign, nonatomic) __weak UILabel* videoLabel;	// G=0x3d2889; S=0x3d28a9; 
@property(assign, nonatomic) __weak UILabel* picLabel;	// G=0x3d2855; S=0x3d2875; 
@property(assign, nonatomic) __weak UILabel* liveLabel;	// G=0x3d2821; S=0x3d2841; 
@property(assign, nonatomic) __weak UIButton* closedBtn;	// G=0x3d27ed; S=0x3d280d; 
@property(assign, nonatomic) __weak UIButton* feedBtn;	// G=0x3d27b9; S=0x3d27d9; 
@property(assign, nonatomic) __weak UIButton* picBtn;	// G=0x3d2785; S=0x3d27a5; 
@property(assign, nonatomic) __weak HJBlurView* blurView;	// G=0x3d2751; S=0x3d2771; 
@property(assign, nonatomic) __weak UIView* btnsView;	// G=0x3d271d; S=0x3d273d; 
-(void).cxx_destruct;	// 0x3d295d
-(void)video:(id)video;	// 0x3d26d1
-(void)feeding:(id)feeding;	// 0x3d2685
-(void)uploadImage:(id)image;	// 0x3d2639
-(void)closeMenu:(id)menu;	// 0x3d25ed
-(id)init;	// 0x3d2531
-(void)awakeFromNib;	// 0x3d2161
@end

