/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJMessageCenterBaseMessageTableViewCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface HJMessageCenterNoticeCell : HJMessageCenterBaseMessageTableViewCell {
	UIImageView* _contentImageView;
}
@property(assign, nonatomic) __weak UIImageView* contentImageView;	// G=0x3e9aa9; S=0x3e9ac9; 
+(float)getCellHeightWithAttributedString:(id)attributedString;	// 0x3e8d35
+(float)getCellHeightWithContent:(id)content;	// 0x3e8c7d
-(void).cxx_destruct;	// 0x3e9add
-(void)contentImageAction:(id)action;	// 0x3e8ded
-(void)setTheMessage:(id)message;	// 0x3e8b31
-(void)awakeFromNib;	// 0x3e8acd
@end

