/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJMessageCenterBaseMessageTableViewCell.h"


__attribute__((visibility("hidden")))
@interface HJMessageCenterFollowingTableViewCell : HJMessageCenterBaseMessageTableViewCell {
}
+(float)getCellHeightWithAttributedString:(id)attributedString;	// 0x271f39
+(float)getCellHeightWithContent:(id)content;	// 0x271e95
@end

