/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HJCircleProgress, UILabel, UIImageView, UIButton, UIView, HJMusicInfoResponse;

__attribute__((visibility("hidden")))
@interface HJMusicSearchCell : XXUnknownSuperclass {
	HJMusicInfoResponse* _data;
	int _playState;
	UILabel* _musicNameLabel;
	UILabel* _singerNameLabel;
	UIButton* _downloadStatusBtn;
	UIImageView* _downloadIcon;
	UIView* _bottomLine;
	int _downloadState;
	HJCircleProgress* _progress;
}
@property(retain, nonatomic) HJCircleProgress* progress;	// G=0x3f47c1; S=0x3f47d1; 
@property(assign, nonatomic) int downloadState;	// G=0x3f47b1; S=0x3f3f2d; 
@property(retain, nonatomic) UIView* bottomLine;	// G=0x3f4779; S=0x3f4789; 
@property(assign, nonatomic) __weak UIImageView* downloadIcon;	// G=0x3f4745; S=0x3f4765; 
@property(assign, nonatomic) __weak UIButton* downloadStatusBtn;	// G=0x3f4711; S=0x3f4731; 
@property(assign, nonatomic) __weak UILabel* singerNameLabel;	// G=0x3f46dd; S=0x3f46fd; 
@property(assign, nonatomic) __weak UILabel* musicNameLabel;	// G=0x3f46a9; S=0x3f46c9; 
@property(assign, nonatomic) int playState;	// G=0x3f4699; S=0x3f41a9; 
@property(retain, nonatomic) HJMusicInfoResponse* data;	// G=0x3f4689; S=0x3f3c9d; 
+(id)identifier;	// 0x3f382d
+(void)registerCellWithTableView:(id)tableView;	// 0x3f37b5
-(void).cxx_destruct;	// 0x3f47f9
-(void)downloadStatusBtnAction:(id)action;	// 0x3f42ad
-(void)setDownloadProgress:(float)progress;	// 0x3f4271
-(void)awakeFromNib;	// 0x3f3845
@end

