/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "living-Structs.h"
#import "DSViewController.h"

@class NSString, HJLoadingView2, NSMutableDictionary, UISwipeGestureRecognizer, NSArray, HJSegmentedView, UIView, UIScrollView, NSMutableArray, YIFullScreenScroll, HJErrorView;

__attribute__((visibility("hidden")))
@interface HJNewDiscoveryVC : DSViewController <UIScrollViewDelegate> {
	NSMutableArray* _views;
	HJSegmentedView* _segmentedView;
	NSMutableDictionary* _itemsMap;
	UISwipeGestureRecognizer* _leftswipeGesture;
	UISwipeGestureRecognizer* _rightswipeGesture;
	UIView* _currentView;
	UIScrollView* _scrollView;
	UIView* _errorView;
	HJErrorView* _theErrorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	UIScrollView* _headerView;
	NSArray* _cats;
	YIFullScreenScroll* _fullScreenDelegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) YIFullScreenScroll* fullScreenDelegate;	// G=0x142bcd; S=0x142bdd; 
@property(retain, nonatomic) NSArray* cats;	// G=0x142b95; S=0x142ba5; 
@property(retain, nonatomic) UIScrollView* headerView;	// G=0x142b5d; S=0x142b6d; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x142b25; S=0x142b35; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x141421; S=0x142afd; 
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x142ac5; S=0x142ad5; 
@property(retain, nonatomic) UIView* errorView;	// G=0x141215; S=0x142a9d; 
@property(retain, nonatomic) UIScrollView* scrollView;	// G=0x142a65; S=0x142a75; 
@property(retain, nonatomic) UIView* currentView;	// G=0x142a2d; S=0x142a3d; 
@property(retain, nonatomic) UISwipeGestureRecognizer* rightswipeGesture;	// G=0x1429f5; S=0x142a05; 
@property(retain, nonatomic) UISwipeGestureRecognizer* leftswipeGesture;	// G=0x1429bd; S=0x1429cd; 
@property(retain, nonatomic) NSMutableDictionary* itemsMap;	// G=0x142985; S=0x142995; 
@property(retain, nonatomic) HJSegmentedView* segmentedView;	// G=0x14294d; S=0x14295d; 
@property(retain, nonatomic) NSMutableArray* views;	// G=0x142915; S=0x142925; 
-(void).cxx_destruct;	// 0x142c05
-(void)refresh;	// 0x142911
-(void)viewDidLayoutSubviews;	// 0x142821
-(void)onTapErrorView:(id)view;	// 0x142811
-(void)scrollViewDidEndDecelerating:(id)scrollView;	// 0x142211
-(void)scrollViewWillEndDragging:(id)scrollView withVelocity:(CGPoint)velocity targetContentOffset:(inout CGPoint*)offset;	// 0x14220d
-(void)scrollViewWillBeginDragging:(id)scrollView;	// 0x142155
-(void)notifyContentViews:(unsigned)views;	// 0x141ef5
-(void)handleGesture:(id)gesture;	// 0x141939
-(void)segmentedViewValueChanged:(id)changed;	// 0x141805
-(void)setupSearch;	// 0x1416c1
-(void)didReceiveMemoryWarning;	// 0x141695
-(void)onTopClicked:(id)clicked;	// 0x140fc5
-(void)loadContents;	// 0x140e49
-(void)dealloc;	// 0x140da9
-(void)viewWillDisappear:(BOOL)view;	// 0x140d3d
-(void)viewWillAppear:(BOOL)view;	// 0x140cd1
-(void)viewDidLoad;	// 0x140521
-(void)searchHandle:(id)handle;	// 0x140411
-(void)pushDiscoveryPeopleVC;	// 0x140389
-(void)setupDiscoveryMorePeople;	// 0x1401bd
-(void)setupSearchPeople;	// 0x13fff1
-(void)setUpTitleView;	// 0x13f8a9
@end

