/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSViewController.h"
#import "LDNetDiagnoServiceDelegate.h"

@class UITextView, NSArray, NSString, UIButton, NSMutableString, LDNetDiagnoService;

__attribute__((visibility("hidden")))
@interface HJNetDiagnoseViewController : DSViewController <LDNetDiagnoServiceDelegate> {
	NSArray* webAddressArray;
	LDNetDiagnoService* netDiagnoService;
	int websetIndex;
	NSMutableString* resultText;
	UITextView* textView;
	UIButton* copyButton;
	float _process;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) float process;	// G=0x273841; S=0x2736cd; 
-(void).cxx_destruct;	// 0x273851
-(void)copyAction;	// 0x2737c5
-(void)netDiagnosisDidEnd:(id)netDiagnosis;	// 0x2734f1
-(void)netDiagnosisStepInfo:(id)info;	// 0x273435
-(void)netDiagnosisDidStarted;	// 0x273431
-(void)diagnoseNetworkForIndex:(int)index;	// 0x2732f5
-(void)viewDidLoad;	// 0x272c21
@end

