/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface HJPopularAll : XXUnknownSuperclass {
	BOOL _hasmore;
	NSArray* _users;
	int _offset;
}
@property(assign, nonatomic) BOOL hasmore;	// G=0x1b79f1; S=0x1b7a01; 
@property(assign, nonatomic) int offset;	// G=0x1b79d1; S=0x1b79e1; 
@property(retain, nonatomic) NSArray* users;	// G=0x1b7999; S=0x1b79a9; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x1b7749
-(void).cxx_destruct;	// 0x1b7a11
@end

