/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HJUserProfileLive, NSString, UILabel, UIImageView, UIView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface HJProfileLiveSmallCell : XXUnknownSuperclass {
	NSString* _nickName;
	HJUserProfileLive* _data;
	UILabel* _liveTitleLabel;
	NSLayoutConstraint* _titleLabelHeight;
	UILabel* _timeLabel;
	UIImageView* _markView;
	UIImageView* _liveImageView;
	UIView* _liveView;
	NSLayoutConstraint* _separatorHeight;
	UIView* _separatorLine;
	UILabel* _titleLabel;
	UILabel* _watchCountLabel;
	UILabel* _heartCountLabel;
	UIView* _sepView;
}
@property(assign, nonatomic) __weak UIView* sepView;	// G=0x27ec0d; S=0x27ec2d; 
@property(assign, nonatomic) __weak UILabel* heartCountLabel;	// G=0x27ebd9; S=0x27ebf9; 
@property(assign, nonatomic) __weak UILabel* watchCountLabel;	// G=0x27eba5; S=0x27ebc5; 
@property(assign, nonatomic) __weak UILabel* titleLabel;	// G=0x27eb71; S=0x27eb91; 
@property(assign, nonatomic) __weak UIView* separatorLine;	// G=0x27eb3d; S=0x27eb5d; 
@property(assign, nonatomic) __weak NSLayoutConstraint* separatorHeight;	// G=0x27eb09; S=0x27eb29; 
@property(assign, nonatomic) __weak UIView* liveView;	// G=0x27ead5; S=0x27eaf5; 
@property(assign, nonatomic) __weak UIImageView* liveImageView;	// G=0x27eaa1; S=0x27eac1; 
@property(assign, nonatomic) __weak UIImageView* markView;	// G=0x27ea6d; S=0x27ea8d; 
@property(assign, nonatomic) __weak UILabel* timeLabel;	// G=0x27ea39; S=0x27ea59; 
@property(assign, nonatomic) __weak NSLayoutConstraint* titleLabelHeight;	// G=0x27ea05; S=0x27ea25; 
@property(assign, nonatomic) __weak UILabel* liveTitleLabel;	// G=0x27e9d1; S=0x27e9f1; 
@property(retain, nonatomic) HJUserProfileLive* data;	// G=0x27e9c1; S=0x27e211; 
@property(copy, nonatomic) NSString* nickName;	// G=0x27e9ad; S=0x27ddd1; 
+(id)identifier;	// 0x27ddb9
+(void)registerCellWithTableView:(id)tableView;	// 0x27dd41
-(void).cxx_destruct;	// 0x27ec41
-(void)layoutSubviews;	// 0x27e641
@end

