/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HJUserIntf, UILabel, UIImageView, UIButton, UIView, HJPrevueDetailWatchButton, HJUserManager, HJUserProfilesResponse, HJForetellListItemResponseExt;
@protocol HJPrevueDetailViewDelegate;

__attribute__((visibility("hidden")))
@interface HJPrevueDetailView : XXUnknownSuperclass {
	HJUserIntf* _userIntf;
	HJUserManager* _watchIntf;
	BOOL _isFollowing;
	long long _praiseCount;
	id<HJPrevueDetailViewDelegate> _delegate;
	HJForetellListItemResponseExt* _data;
	HJUserProfilesResponse* _userInfo;
	UILabel* _timeTitleLabel;
	UILabel* _timeLabel;
	UIImageView* _iconView;
	UILabel* _nicknameLabel;
	UIView* _praiseContainer;
	UILabel* _praiseCountLabel;
	HJPrevueDetailWatchButton* _watchButton;
	UIButton* _shareButton;
	UIButton* _reportButton;
}
@property(assign, nonatomic) __weak UIButton* reportButton;	// G=0x172e69; S=0x172e89; 
@property(assign, nonatomic) __weak UIButton* shareButton;	// G=0x172e35; S=0x172e55; 
@property(assign, nonatomic) __weak HJPrevueDetailWatchButton* watchButton;	// G=0x172e01; S=0x172e21; 
@property(assign, nonatomic) __weak UILabel* praiseCountLabel;	// G=0x172dcd; S=0x172ded; 
@property(assign, nonatomic) __weak UIView* praiseContainer;	// G=0x172d99; S=0x172db9; 
@property(assign, nonatomic) __weak UILabel* nicknameLabel;	// G=0x172d65; S=0x172d85; 
@property(assign, nonatomic) __weak UIImageView* iconView;	// G=0x172d31; S=0x172d51; 
@property(assign, nonatomic) __weak UILabel* timeLabel;	// G=0x172cfd; S=0x172d1d; 
@property(assign, nonatomic) __weak UILabel* timeTitleLabel;	// G=0x172cc9; S=0x172ce9; 
@property(retain, nonatomic) HJUserProfilesResponse* userInfo;	// G=0x172c91; S=0x172ca1; 
@property(assign, nonatomic) __weak HJForetellListItemResponseExt* data;	// G=0x172c5d; S=0x172c7d; 
@property(assign, nonatomic) __weak id<HJPrevueDetailViewDelegate> delegate;	// G=0x172c29; S=0x172c49; 
-(void).cxx_destruct;	// 0x172e9d
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x172819
-(id)timeText;	// 0x172681
-(void)doRefresh;	// 0x172651
-(void)doRefreshUI;	// 0x17228d
-(void)_refreshTime;	// 0x172199
-(void)_requestUserInfo;	// 0x171f85
-(void)doLoad;	// 0x171f45
-(void)layoutSubviews;	// 0x171e41
-(void)onTap;	// 0x171e3d
-(void)awakeFromNib;	// 0x171941
-(void)onReportClick:(id)click;	// 0x1717e9
-(void)onClickShareButton:(id)button;	// 0x171775
-(void)onClickWatchButton:(id)button;	// 0x171359
-(void)onClickCloseButton:(id)button;	// 0x1712e5
@end

