/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "HJProfileHeader.h"

@class UILabel, UIImageView, UIButton, HJUserProfilesResponse;
@protocol HJProfileHeaderViewDelegate;

__attribute__((visibility("hidden")))
@interface HJProfileHeaderView : HJProfileHeader {
	BOOL _isMyself;
	HJUserProfilesResponse* _userProfile;
	float _heightOfHeader;
	id<HJProfileHeaderViewDelegate> _delegate;
	UIImageView* _avatarView;
	UILabel* _praiseLabel;
	UILabel* _nameLabel;
	UILabel* _signatureLabel;
	UIButton* _btnView;
	UIButton* _editView;
	UIImageView* _heartView;
	float _iHeightOfHeader;
	UIButton* _chattingRoomBtn;
}
@property(retain, nonatomic) UIButton* chattingRoomBtn;	// G=0x2b2119; S=0x2b2d85; 
@property(assign, nonatomic) float iHeightOfHeader;	// G=0x2b2d65; S=0x2b2d75; 
@property(retain, nonatomic) UIImageView* heartView;	// G=0x2b2acd; S=0x2b2d3d; 
@property(retain, nonatomic) UIButton* editView;	// G=0x2b28f5; S=0x2b2d15; 
@property(retain, nonatomic) UIButton* btnView;	// G=0x2b1ff1; S=0x2b2ced; 
@property(retain, nonatomic) UILabel* signatureLabel;	// G=0x2b26f5; S=0x2b2cc5; 
@property(retain, nonatomic) UILabel* nameLabel;	// G=0x2b2555; S=0x2b2c9d; 
@property(retain, nonatomic) UILabel* praiseLabel;	// G=0x2b23b1; S=0x2b2c75; 
@property(retain, nonatomic) UIImageView* avatarView;	// G=0x2b1df1; S=0x2b2c4d; 
@property(assign, nonatomic) BOOL isMyself;	// G=0x2b2c2d; S=0x2b2c3d; 
@property(assign, nonatomic) __weak id<HJProfileHeaderViewDelegate> delegate;	// G=0x2b2bf9; S=0x2b2c19; 
@property(assign, nonatomic) float heightOfHeader;	// G=0x2b10ed; S=0x2b2be9; 
@property(retain, nonatomic) HJUserProfilesResponse* userProfile;	// G=0x2b2bd9; S=0x2afd19; 
-(void).cxx_destruct;	// 0x2b2dad
-(id)headImageView;	// 0x2b2bc9
-(void)editHead;	// 0x2b1d55
-(void)editAction;	// 0x2b1cb9
-(void)setUserFollowed:(BOOL)followed;	// 0x2b1c09
-(void)chattingRoomAction:(id)action;	// 0x2b1ae9
-(void)btnAction:(id)action;	// 0x2b10fd
-(void)setButtonStatus:(BOOL)status;	// 0x2b0ea9
-(void)setViewFrames;	// 0x2b03a9
-(void)setDatas;	// 0x2afe15
-(void)layoutSubviews;	// 0x2afba1
-(void)commonInit;	// 0x2afa35
-(id)initWithFrame:(CGRect)frame;	// 0x2af9dd
@end

