/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJPraiseButton : XXUnknownSuperclass {
	NSString* _praise;
}
@property(retain, nonatomic) NSString* praise;	// G=0xadfa5; S=0xadf2d; 
+(id)createPraiseButton;	// 0xadd7d
-(void).cxx_destruct;	// 0xadfb5
@end

