/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImage, UILabel, UIImageView, UIColor;

__attribute__((visibility("hidden")))
@interface HJPrevueShareButton : XXUnknownSuperclass {
	UIImageView* _shareIconView;
	UILabel* _shareTextLabel;
	UIColor* _shareNormalBgColor;
	UIColor* _shareHighlightBgColor;
	UIColor* _shareDisabledBgColor;
	UIImage* _shareIconImage;
	NSString* _shareText;
	UIColor* _shareBorderColor;
	UIColor* _shareTextColor;
}
@property(retain, nonatomic) UIColor* shareTextColor;	// G=0x184b19; S=0x184b29; 
@property(retain, nonatomic) UIColor* shareBorderColor;	// G=0x184ae1; S=0x184af1; 
@property(copy, nonatomic) NSString* shareText;	// G=0x184acd; S=0x1849a9; 
@property(retain, nonatomic) UIImage* shareIconImage;	// G=0x184a95; S=0x184aa5; 
@property(retain, nonatomic) UIColor* shareDisabledBgColor;	// G=0x184a5d; S=0x184a6d; 
@property(retain, nonatomic) UIColor* shareHighlightBgColor;	// G=0x184a25; S=0x184a35; 
@property(retain, nonatomic) UIColor* shareNormalBgColor;	// G=0x1849ed; S=0x1849fd; 
-(void).cxx_destruct;	// 0x184b51
-(void)awakeFromNib;	// 0x1847d5
-(void)relayout;	// 0x184295
-(void)layoutSubviews;	// 0x184255
@end

