/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class AppDelegate, NSDictionary, DSTabBarController, DSNavigationController;

__attribute__((visibility("hidden")))
@interface HJPushTransfer : XXUnknownSuperclass {
	NSDictionary* _currentPush;
	DSNavigationController* _liveNavi;
	DSTabBarController* _tabController;
	AppDelegate* _theAppDelegate;
}
@property(assign, nonatomic) __weak AppDelegate* theAppDelegate;	// G=0x178e1; S=0x1897d; 
@property(retain, nonatomic) DSTabBarController* tabController;	// G=0x179b1; S=0x18955; 
@property(retain, nonatomic) DSNavigationController* liveNavi;	// G=0x17a81; S=0x1892d; 
@property(retain, nonatomic) NSDictionary* currentPush;	// G=0x1891d; S=0x1885d; 
+(id)allocWithZone:(NSZone*)zone;	// 0x17c49
+(id)new;	// 0x17c29
+(id)sharedPushTransfer;	// 0x17b55
-(void).cxx_destruct;	// 0x18991
-(void)handlePush;	// 0x17d05
-(id)init;	// 0x17c69
@end

