/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HJRankUserResponse, UILabel, UIImageView, UIView;

__attribute__((visibility("hidden")))
@interface HJRankUserCell : XXUnknownSuperclass {
	HJRankUserResponse* _data;
	UILabel* _rankLabel;
	UIImageView* _rankLogo;
	UIImageView* _headImageView;
	UILabel* _nameLabel;
	UILabel* _signatureLabel;
	UILabel* _likeLabel;
	UIImageView* _likeIcon;
	UIImageView* _followIcon;
	UIView* _followView;
	UIView* _topLine;
}
@property(retain, nonatomic) UIView* topLine;	// G=0x2c64d1; S=0x2c64e1; 
@property(assign, nonatomic) __weak UIView* followView;	// G=0x2c649d; S=0x2c64bd; 
@property(assign, nonatomic) __weak UIImageView* followIcon;	// G=0x2c6469; S=0x2c6489; 
@property(assign, nonatomic) __weak UIImageView* likeIcon;	// G=0x2c6435; S=0x2c6455; 
@property(assign, nonatomic) __weak UILabel* likeLabel;	// G=0x2c6401; S=0x2c6421; 
@property(assign, nonatomic) __weak UILabel* signatureLabel;	// G=0x2c63cd; S=0x2c63ed; 
@property(assign, nonatomic) __weak UILabel* nameLabel;	// G=0x2c6399; S=0x2c63b9; 
@property(assign, nonatomic) __weak UIImageView* headImageView;	// G=0x2c6365; S=0x2c6385; 
@property(assign, nonatomic) __weak UIImageView* rankLogo;	// G=0x2c6331; S=0x2c6351; 
@property(assign, nonatomic) __weak UILabel* rankLabel;	// G=0x2c62fd; S=0x2c631d; 
@property(retain, nonatomic) HJRankUserResponse* data;	// G=0x2c62ed; S=0x2c589d; 
+(id)identifier;	// 0x2c531d
+(void)registerCellWithTableView:(id)tableView;	// 0x2c52a5
-(void).cxx_destruct;	// 0x2c6509
-(void)onFollowBtnClick;	// 0x2c60fd
-(void)updateFollowButton;	// 0x2c5fd1
-(void)prepareForReuse;	// 0x2c5811
-(void)awakeFromNib;	// 0x2c5335
@end

