/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "living-Structs.h"

@class NSString, UICollectionView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJRedPacketViewController : XXUnknownSuperclass <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout> {
	NSMutableArray* _redPacketArr;
	id _topRedPacketTapAction;
	UICollectionView* _collectionView;
	NSMutableArray* _dataSourceArr;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* dataSourceArr;	// G=0x2c7d9; S=0x2c7e9; 
@property(retain, nonatomic) UICollectionView* collectionView;	// G=0x2c7a1; S=0x2c7b1; 
@property(copy, nonatomic) id topRedPacketTapAction;	// G=0x2c77d; S=0x2c791; 
@property(retain, nonatomic) NSMutableArray* redPacketArr;	// G=0x2c745; S=0x2c755; 
-(void).cxx_destruct;	// 0x2c811
-(void)loadNextRedPacket;	// 0x2c539
-(void)removeTimer:(id)timer;	// 0x2c279
-(void)room:(id)room didRecieveRedPacketReward:(id)reward;	// 0x2c0d1
-(void)collectionView:(id)view didSelectItemAtIndexPath:(id)indexPath;	// 0x2c019
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;	// 0x2bf4d
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;	// 0x2bf11
-(int)numberOfSectionsInCollectionView:(id)collectionView;	// 0x2bf0d
-(void)viewDidLayoutSubviews;	// 0x2be49
-(void)viewDidLoad;	// 0x2bb99
@end

