/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJResponse : XXUnknownSuperclass {
}
+(id)responseWithUserInfo:(id)userInfo;	// 0x1397f9
-(id)propertys;	// 0x139961
@end

