/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJReplay.h"

@class UIColor;

__attribute__((visibility("hidden")))
@interface HJReplayExt : HJReplay {
	BOOL _popular;
	UIColor* _stateColor;
}
@property(retain, nonatomic) UIColor* stateColor;	// G=0x13b121; S=0x13b131; 
@property(assign, nonatomic) BOOL popular;	// G=0x13b101; S=0x13b111; 
-(void).cxx_destruct;	// 0x13b159
@end

