/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJBaseCell.h"

@class HJReplay;

__attribute__((visibility("hidden")))
@interface HJReplayBaseCell : HJBaseCell {
	HJReplay* _data;
}
@property(retain, nonatomic) HJReplay* data;	// G=0x31bfc5; S=0x31bfd5; 
-(void).cxx_destruct;	// 0x31bffd
@end

