/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, NSString, HJRedPacketRewardIteminfo, HJChatUser;

__attribute__((visibility("hidden")))
@interface HJRedPacketData : XXUnknownSuperclass {
	BOOL _isFirst;
	NSString* _traceid;
	NSString* _liveid;
	int _getAmount;
	HJRedPacketRewardIteminfo* _iteminfo;
	HJChatUser* _sender;
	NSTimer* _timer;
	long long _host_income;
	long long _host_amount;
	CGSize _titleSize;
}
@property(retain, nonatomic) NSTimer* timer;	// G=0x2ce12d; S=0x2ce13d; 
@property(assign, nonatomic) CGSize titleSize;	// G=0x2ce0fd; S=0x2ce119; 
@property(retain, nonatomic) HJChatUser* sender;	// G=0x2ce0c5; S=0x2ce0d5; 
@property(retain, nonatomic) HJRedPacketRewardIteminfo* iteminfo;	// G=0x2ce08d; S=0x2ce09d; 
@property(assign, nonatomic) BOOL isFirst;	// G=0x2ce06d; S=0x2ce07d; 
@property(assign, nonatomic) int getAmount;	// G=0x2ce04d; S=0x2ce05d; 
@property(assign, nonatomic) long long host_amount;	// G=0x2ce021; S=0x2ce039; 
@property(assign, nonatomic) long long host_income;	// G=0x2cdff5; S=0x2ce00d; 
@property(copy, nonatomic) NSString* liveid;	// G=0x2cdfd1; S=0x2cdfe5; 
@property(copy, nonatomic) NSString* traceid;	// G=0x2cdfad; S=0x2cdfc1; 
-(void).cxx_destruct;	// 0x2ce165
@end

