/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJServices.h"
#import "HJServicesConstraits.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface HJReplyIntf : HJServices <HJServicesConstraits> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedIntfs;	// 0x32d9bd
-(id)reply_getRepliesWithRelatedId:(id)relatedId offset:(id)offset direction:(id)direction complete:(id)complete failured:(id)failured;	// 0x32de9d
-(void)reply_addWithRelatedId:(id)relatedId quoteId:(id)anId content:(id)content type:(id)type complete:(id)complete failured:(id)failured;	// 0x32dae1
-(id)init;	// 0x32da91
@end

