/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MGSwipeTableCell.h"

@class HJReplyInfo, UILabel, UIImageView, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface HJReplyCell : MGSwipeTableCell {
	UIImageView* _headerView;
	UILabel* _name;
	UILabel* _reply;
	UILabel* _time;
	HJReplyInfo* _data;
	NSLayoutConstraint* _diveideHeight;
}
@property(assign, nonatomic) __weak NSLayoutConstraint* diveideHeight;	// G=0x13932d; S=0x13934d; 
@property(retain, nonatomic) HJReplyInfo* data;	// G=0x13931d; S=0x138d4d; 
@property(assign, nonatomic) __weak UILabel* time;	// G=0x1392e9; S=0x139309; 
@property(assign, nonatomic) __weak UILabel* reply;	// G=0x1392b5; S=0x1392d5; 
@property(assign, nonatomic) __weak UILabel* name;	// G=0x139281; S=0x1392a1; 
@property(assign, nonatomic) __weak UIImageView* headerView;	// G=0x13924d; S=0x13926d; 
+(id)identifier;	// 0x138bdd
+(void)registerCellWithTableView:(id)tableView;	// 0x138b65
-(void).cxx_destruct;	// 0x139361
-(void)setAttrReply:(id)reply;	// 0x1391fd
-(void)awakeFromNib;	// 0x138bf5
@end

