/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJRedEvelopeReceiverItem : XXUnknownSuperclass {
	int _uid;
	int _money;
	NSString* _message;
	NSString* _nickName;
	NSString* _headUrl;
}
@property(copy, nonatomic) NSString* headUrl;	// G=0xdae45; S=0xdae59; 
@property(copy, nonatomic) NSString* nickName;	// G=0xdae21; S=0xdae35; 
@property(copy, nonatomic) NSString* message;	// G=0xdadfd; S=0xdae11; 
@property(assign, nonatomic) int money;	// G=0xdaddd; S=0xdaded; 
@property(assign, nonatomic) int uid;	// G=0xdadbd; S=0xdadcd; 
-(void).cxx_destruct;	// 0xdae69
-(id)initWithResult:(id)result;	// 0xdac25
@end

