/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJReplayBaseCell.h"

@class UILabel, UIImageView, UIButton, UIView, HJReplay, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface HJReplayBigCell : HJReplayBaseCell {
	BOOL _endLive;
	BOOL _firstIn;
	HJReplay* _data;
	UILabel* _timeLabel;
	UIImageView* _maskView;
	UIImageView* _liveImageView;
	NSLayoutConstraint* _imageHeight;
	NSLayoutConstraint* _viewHeight;
	UIView* _bgView;
	UIButton* _liveBtn;
	UIButton* _iconBtn;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UILabel* _watchInfoLabel;
	UILabel* _personCountLabel;
	UILabel* _heartCountLabel;
	UILabel* _durationLabel;
}
@property(assign, nonatomic, getter=isFirstIn) BOOL firstIn;	// G=0x28c43d; S=0x28c44d; 
@property(assign, nonatomic, getter=isEndLive) BOOL endLive;	// G=0x28c41d; S=0x28c42d; 
@property(assign, nonatomic) __weak UILabel* durationLabel;	// G=0x28c3e9; S=0x28c409; 
@property(assign, nonatomic) __weak UILabel* heartCountLabel;	// G=0x28c3b5; S=0x28c3d5; 
@property(assign, nonatomic) __weak UILabel* personCountLabel;	// G=0x28c381; S=0x28c3a1; 
@property(assign, nonatomic) __weak UILabel* watchInfoLabel;	// G=0x28c34d; S=0x28c36d; 
@property(assign, nonatomic) __weak UILabel* subtitleLabel;	// G=0x28c319; S=0x28c339; 
@property(assign, nonatomic) __weak UILabel* titleLabel;	// G=0x28c2e5; S=0x28c305; 
@property(assign, nonatomic) __weak UIButton* iconBtn;	// G=0x28c2b1; S=0x28c2d1; 
@property(assign, nonatomic) __weak UIButton* liveBtn;	// G=0x28c27d; S=0x28c29d; 
@property(assign, nonatomic) __weak UIView* bgView;	// G=0x28c249; S=0x28c269; 
@property(assign, nonatomic) __weak NSLayoutConstraint* viewHeight;	// G=0x28c215; S=0x28c235; 
@property(assign, nonatomic) __weak NSLayoutConstraint* imageHeight;	// G=0x28c1e1; S=0x28c201; 
@property(assign, nonatomic) __weak UIImageView* liveImageView;	// G=0x28c1ad; S=0x28c1cd; 
@property(assign, nonatomic) __weak UIImageView* maskView;	// G=0x28c179; S=0x28c199; 
@property(assign, nonatomic) __weak UILabel* timeLabel;	// G=0x28c145; S=0x28c165; 
+(id)identifier;	// 0x28afc1
+(void)registerCellWithTableView:(id)tableView;	// 0x28af49
-(id)data;	// 0x28c135
-(void).cxx_destruct;	// 0x28c45d
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;	// 0x28c105
-(void)prepareForReuse;	// 0x28c0cd
-(void)layoutSubviews;	// 0x28bdc5
-(void)onClickIconButton:(id)button;	// 0x28bcf9
-(void)setData:(id)data;	// 0x28b155
-(void)awakeFromNib;	// 0x28afd9
@end

