/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class HJSegmentedItem, NSArray, UIView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJSegmentedView : XXUnknownSuperclass {
	BOOL _isFullSizeMarkView;
	BOOL _showMarkView;
	BOOL _inAnimation;
	unsigned _selectedIndex;
	UIView* _markView;
	NSArray* _items;
	NSMutableArray* _segmentedViews;
	int _spacing;
	int _contentWith;
	float _markViewOriginX;
}
@property(assign, nonatomic) float markViewOriginX;	// G=0x278ef9; S=0x278f09; 
@property(assign, nonatomic) int contentWith;	// G=0x278ed9; S=0x278ee9; 
@property(assign, nonatomic) int spacing;	// G=0x278eb9; S=0x278ec9; 
@property(assign, nonatomic) BOOL inAnimation;	// G=0x278e99; S=0x278ea9; 
@property(retain, nonatomic) NSMutableArray* segmentedViews;	// G=0x278e61; S=0x278e71; 
@property(retain, nonatomic) NSArray* items;	// G=0x278e51; S=0x277e49; 
@property(readonly, assign, nonatomic) HJSegmentedItem* selectedItem;	// G=0x278b11; 
@property(assign, nonatomic) BOOL showMarkView;	// G=0x278e41; S=0x277df5; 
@property(assign, nonatomic) BOOL isFullSizeMarkView;	// G=0x278e21; S=0x278e31; 
@property(retain, nonatomic) UIView* markView;	// G=0x278de9; S=0x278df9; 
@property(assign, nonatomic) unsigned selectedIndex;	// G=0x278dc9; S=0x278dd9; 
-(void).cxx_destruct;	// 0x278f19
-(void)disableItemAtIndex:(unsigned)index;	// 0x278d59
-(void)onSegmentedViewClick:(id)click;	// 0x278bb1
-(void)setSelectedIndex:(unsigned)index animated:(BOOL)animated;	// 0x278659
-(float)viewWidth;	// 0x278635
-(id)viewWithIndex:(int)index;	// 0x2785e9
-(id)selectedView;	// 0x278591
-(void)setItems:(id)items withSpacing:(float)spacing;	// 0x278185
-(void)layoutSubviews;	// 0x277809
-(void)setMaskViewColor:(id)color;	// 0x2777b9
-(id)initWithFrame:(CGRect)frame;	// 0x277649
@end

