/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface HJSeedLiveInfoResponse : XXUnknownSuperclass {
	NSString* _content;
	int _praises;
	int _watches;
	NSString* _image;
	NSString* _ration;
	int _addtime;
	NSString* _model_alis;
	NSString* _network;
}
@property(retain, nonatomic) NSString* network;	// G=0x4c69d; S=0x4c6ad; 
@property(retain, nonatomic) NSString* model_alis;	// G=0x4c665; S=0x4c675; 
@property(assign, nonatomic) int addtime;	// G=0x4c645; S=0x4c655; 
@property(retain, nonatomic) NSString* ration;	// G=0x4c60d; S=0x4c61d; 
@property(retain, nonatomic) NSString* image;	// G=0x4c5d5; S=0x4c5e5; 
@property(assign, nonatomic) int watches;	// G=0x4c5b5; S=0x4c5c5; 
@property(assign, nonatomic) int praises;	// G=0x4c595; S=0x4c5a5; 
@property(retain, nonatomic) NSString* content;	// G=0x4c55d; S=0x4c56d; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x4c239
-(void).cxx_destruct;	// 0x4c6d5
@end

