/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class HJSeedRepostListResponse, NSNumber, HJReplayResponse, HJShareResponse, HJSeedLiveResponse, HJSeedAnchorResponse;

__attribute__((visibility("hidden")))
@interface HJSeedItemResponse : XXUnknownSuperclass {
	BOOL _isEmpty;
	HJSeedLiveResponse* _live;
	HJSeedAnchorResponse* _anchor;
	HJSeedRepostListResponse* _repost;
	HJShareResponse* _share;
	HJReplayResponse* _replay;
	NSNumber* _type;
}
@property(assign, nonatomic) BOOL isEmpty;	// G=0x4b141; S=0x4b151; 
@property(retain, nonatomic) NSNumber* type;	// G=0x4b109; S=0x4b119; 
@property(retain, nonatomic) HJReplayResponse* replay;	// G=0x4b0d1; S=0x4b0e1; 
@property(retain, nonatomic) HJShareResponse* share;	// G=0x4b099; S=0x4b0a9; 
@property(retain, nonatomic) HJSeedRepostListResponse* repost;	// G=0x4b061; S=0x4b071; 
@property(retain, nonatomic) HJSeedAnchorResponse* anchor;	// G=0x4b029; S=0x4b039; 
@property(retain, nonatomic) HJSeedLiveResponse* live;	// G=0x4aff1; S=0x4b001; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x4ad55
-(void).cxx_destruct;	// 0x4b161
@end

