/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel;

__attribute__((visibility("hidden")))
@interface HJSearchHeaderView : XXUnknownSuperclass {
	UILabel* _titleLabel;
}
@property(assign, nonatomic) __weak UILabel* titleLabel;	// G=0x17c955; S=0x17c975; 
-(void).cxx_destruct;	// 0x17c989
@end

