/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIFont, UIColor;

__attribute__((visibility("hidden")))
@interface HJSegmentedItem : XXUnknownSuperclass {
	int _tag;
	NSString* _cid;
	id _context;
	NSString* _title;
	UIColor* _titleColor;
	UIColor* _hilightedTitleColor;
	UIFont* _titleFont;
}
@property(retain, nonatomic) UIFont* titleFont;	// G=0x27758d; S=0x27759d; 
@property(retain, nonatomic) UIColor* hilightedTitleColor;	// G=0x277555; S=0x277565; 
@property(retain, nonatomic) UIColor* titleColor;	// G=0x27751d; S=0x27752d; 
@property(copy, nonatomic) NSString* title;	// G=0x2774f9; S=0x27750d; 
@property(retain, nonatomic) id context;	// G=0x2774d5; S=0x2774e5; 
@property(retain, nonatomic) NSString* cid;	// G=0x27749d; S=0x2774ad; 
@property(assign, nonatomic) int tag;	// G=0x27747d; S=0x27748d; 
-(void).cxx_destruct;	// 0x2775c5
-(id)init;	// 0x27738d
@end

