/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIColor, HJProfileSegmentItem;

__attribute__((visibility("hidden")))
@interface HJSegmentView : XXUnknownSuperclass {
	BOOL _isSelected;
	HJProfileSegmentItem* _item;
	UIColor* _normalColor;
	UIColor* _highlightColor;
	UILabel* _countLabel;
	UILabel* _titleLabel;
	UILabel* _line;
}
@property(retain, nonatomic) UILabel* line;	// G=0x1a5c41; S=0x1a5eed; 
@property(retain, nonatomic) UILabel* titleLabel;	// G=0x1a5ce1; S=0x1a5ec5; 
@property(retain, nonatomic) UILabel* countLabel;	// G=0x1a5b19; S=0x1a5e9d; 
@property(retain, nonatomic) UIColor* highlightColor;	// G=0x1a5e65; S=0x1a5e75; 
@property(retain, nonatomic) UIColor* normalColor;	// G=0x1a5e2d; S=0x1a5e3d; 
@property(retain, nonatomic) HJProfileSegmentItem* item;	// G=0x1a5e1d; S=0x1a59b1; 
@property(assign, nonatomic) BOOL isSelected;	// G=0x1a5e0d; S=0x1a5949; 
-(void).cxx_destruct;	// 0x1a5f15
-(void)layoutSubviews;	// 0x1a5795
-(void)commonInit;	// 0x1a5729
-(id)initWithFrame:(CGRect)frame;	// 0x1a56d1
@end

