/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSTableViewController.h"
#import "HJBaseCellDelegate.h"

@class HJDiscEmptyView, HJLoadingView2, NSString, HJDiscoverBaseCell, UIView, NSMutableArray, NSIndexPath, HJErrorView;

__attribute__((visibility("hidden")))
@interface HJSearchMoreUserController : DSTableViewController <HJBaseCellDelegate> {
	NSString* _searchContent;
	NSMutableArray* _userArrM;
	UIView* _emtpyView;
	UIView* _errorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	HJDiscEmptyView* _theEmptyView;
	HJErrorView* _theErrorView;
	NSIndexPath* _preIndexPath;
	HJDiscoverBaseCell* _selectedCell;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak HJDiscoverBaseCell* selectedCell;	// G=0x134411; S=0x134431; 
@property(retain, nonatomic) NSIndexPath* preIndexPath;	// G=0x1343d9; S=0x1343e9; 
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x1343a1; S=0x1343b1; 
@property(retain, nonatomic) HJDiscEmptyView* theEmptyView;	// G=0x134369; S=0x134379; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x134331; S=0x134341; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x1339d5; S=0x134309; 
@property(retain, nonatomic) UIView* errorView;	// G=0x133c3d; S=0x1342e1; 
@property(retain, nonatomic) UIView* emtpyView;	// G=0x133ee1; S=0x1342b9; 
@property(retain, nonatomic) NSMutableArray* userArrM;	// G=0x133401; S=0x134291; 
@property(copy, nonatomic) NSString* searchContent;	// G=0x13426d; S=0x134281; 
-(void).cxx_destruct;	// 0x134445
-(void)checkError:(id)error;	// 0x1341dd
-(void)checkEmpty;	// 0x13417d
-(void)onTapEmptyView;	// 0x1339d1
-(void)onTapErrorView;	// 0x1339b1
-(void)showTable;	// 0x1338cd
-(void)showError;	// 0x1337e9
-(void)showEmpty;	// 0x133705
-(void)showLoading;	// 0x133621
-(void)setupSubviews;	// 0x1334c1
-(void)onBack;	// 0x13347d
-(void)setupBackBarButton;	// 0x133451
-(void)loadDataWithSearchContent:(id)searchContent;	// 0x13317d
-(void)onClickIconViewOfCell:(id)cell;	// 0x133081
-(void)viewWillDisappear:(BOOL)view;	// 0x13300d
-(void)viewWillAppear:(BOOL)view;	// 0x132f81
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x132e31
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x132e29
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x132ded
-(int)numberOfSectionsInTableView:(id)tableView;	// 0x132de9
-(void)dealloc;	// 0x132d1d
-(void)onUserFollowStatusChangedNotification:(id)notification;	// 0x132b19
-(void)viewDidLoad;	// 0x1329b9
@end

