/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJSearchInfo : XXUnknownSuperclass {
	BOOL _hasmore;
	NSMutableArray* _users;
	NSMutableArray* _lives;
	NSMutableArray* _replays;
	NSMutableArray* _liveReplay;
	int _offset;
}
@property(assign, nonatomic) BOOL hasmore;	// G=0x25d565; S=0x25d575; 
@property(assign, nonatomic) int offset;	// G=0x25d545; S=0x25d555; 
@property(retain, nonatomic) NSMutableArray* liveReplay;	// G=0x25d50d; S=0x25d51d; 
@property(retain, nonatomic) NSMutableArray* replays;	// G=0x25d4d5; S=0x25d4e5; 
@property(retain, nonatomic) NSMutableArray* lives;	// G=0x25d49d; S=0x25d4ad; 
@property(retain, nonatomic) NSMutableArray* users;	// G=0x25d465; S=0x25d475; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x25d0e9
+(id)searchForUserInfo:(id)userInfo;	// 0x25ce7d
-(void).cxx_destruct;	// 0x25d585
@end

