/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, HJSeedCreateShareResponse;

__attribute__((visibility("hidden")))
@interface HJSeedStartLiveResponse : XXUnknownSuperclass {
	NSString* _liveid;
	NSString* _location;
	HJSeedCreateShareResponse* _share;
	double _balance;
}
@property(assign) double balance;	// G=0x4d615; S=0x4d649; 
@property(retain, nonatomic) HJSeedCreateShareResponse* share;	// G=0x4d5dd; S=0x4d5ed; 
@property(retain, nonatomic) NSString* location;	// G=0x4d5a5; S=0x4d5b5; 
@property(retain, nonatomic) NSString* liveid;	// G=0x4d56d; S=0x4d57d; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x4d389
-(void).cxx_destruct;	// 0x4d67d
@end

