/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface HJShortVideoUploadingManager : XXUnknownSuperclass {
	NSMutableDictionary* _uploadingDataDict;
}
@property(retain, nonatomic) NSMutableDictionary* uploadingDataDict;	// G=0x76b25; S=0x76b35; 
+(float)getVideoSecond:(id)second;	// 0x76a15
+(void)deleteRecordWithFileURL:(id)fileURL;	// 0x76989
+(id)sharedInstance;	// 0x74b35
-(void).cxx_destruct;	// 0x76b5d
-(void)cancelUploadingWithFileURL:(id)fileURL;	// 0x767f5
-(void)publishVideo:(id)video;	// 0x763c1
-(void)uploadCover:(id)cover;	// 0x75e05
-(void)checkComplete:(id)complete;	// 0x75875
-(void)doUploadSlices:(id)slices;	// 0x752c9
-(void)uploadingWithImageUploadModel:(id)imageUploadModel progress:(id)progress success:(id)success failure:(id)failure;	// 0x74c79
-(id)init;	// 0x74c09
@end

