/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJServices.h"
#import "HJServicesConstraits.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface HJStatisIntf : HJServices <HJServicesConstraits> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)sharedIntfs;	// 0xa06c1
-(id)statis_share:(id)share relatedId:(id)anId authorId:(id)anId3 uid:(id)uid shareType:(id)type pageName:(id)name complete:(id)complete failured:(id)failured;	// 0xa07e5
-(id)init;	// 0xa0795
@end

