/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJSuggestData : XXUnknownSuperclass {
	NSString* _query;
	NSMutableArray* _results;
}
@property(retain, nonatomic) NSMutableArray* results;	// G=0x25cc19; S=0x25cc29; 
@property(retain, nonatomic) NSString* query;	// G=0x25cbe1; S=0x25cbf1; 
+(id)responseWithInfo:(id)info;	// 0x25c9b1
-(void).cxx_destruct;	// 0x25cc51
@end

