/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"


__attribute__((visibility("hidden")))
@interface HJTableViewController : XXUnknownSuperclass {
	BOOL _appear;
	UIEdgeInsets _tableInsets;
}
@property(assign, nonatomic, getter=isAppear) BOOL appear;	// G=0xa3fc9; S=0xa3fd9; 
@property(assign, nonatomic) UIEdgeInsets tableInsets;	// G=0xa3fb1; S=0xa3c35; 
-(void)refreshWhenViewAppear;	// 0xa3fad
-(void)setupBackBarButton;	// 0xa3db9
-(void)hjLoadNewData;	// 0xa3db5
-(void)hjLoadMoreData;	// 0xa3db1
-(void)hiddenFooterView:(BOOL)view;	// 0xa3d55
-(void)hjNoticeNoMoreData;	// 0xa3cfd
-(void)beginLoadNewTableView;	// 0xa3ca5
-(void)endRefresh;	// 0xa3af5
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0xa3af1
-(int)numberOfSectionsInTableView:(id)tableView;	// 0xa3aed
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;	// 0xa3ae1
-(int)preferredInterfaceOrientationForPresentation;	// 0xa3add
-(unsigned)supportedInterfaceOrientations;	// 0xa3ad9
-(BOOL)shouldAutorotate;	// 0xa3ad5
-(void)setTitle:(id)title;	// 0xa3955
-(void)onBack:(id)back;	// 0xa3911
-(void)didReceiveMemoryWarning;	// 0xa38e5
-(void)initRefresh;	// 0xa34ed
-(void)setupTableView;	// 0xa3391
-(void)viewDidLoad;	// 0xa3299
-(id)initWithNibName:(id)nibName bundle:(id)bundle;	// 0xa322d
@end

