/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HJToastMgr : XXUnknownSuperclass {
}
+(void)showLCH_Toast:(id)toast;	// 0x35e81d
+(void)showLiveToast:(id)toast;	// 0x35e6b5
+(void)showToast:(id)toast;	// 0x35e54d
+(void)showToast:(id)toast view:(id)view duration:(double)duration;	// 0x35e3c9
+(void)showDebugToast:(id)toast;	// 0x35e3c5
+(void)initialize;	// 0x35e275
@end

