/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXApiDelegate.h"
#import "WeiboSDKDelegate.h"
#import "TencentSessionDelegate.h"
#import "NSURLConnectionDataDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"

@class NSOperationQueue, TencentOAuth, HJServices, NSURLConnection, SendMessageToWXReq, HJUserActivationResponse, NSString;
@protocol HJTPUManagerDelegate;

__attribute__((visibility("hidden")))
@interface HJTPUManager : XXUnknownSuperclass <WXApiDelegate, WeiboSDKDelegate, TencentSessionDelegate, NSURLConnectionDataDelegate> {
	TencentOAuth* _tecentOAuth;
	NSOperationQueue* _requestQueue;
	HJServices* _serviceIntfs;
	NSURLConnection* _wxConn;
	HJUserActivationResponse* _userInfo;
	id<HJTPUManagerDelegate> _delegate;
	SendMessageToWXReq* _wxReq;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) SendMessageToWXReq* wxReq;	// G=0x3a8901; S=0x3a8911; 
@property(assign, nonatomic) __weak id<HJTPUManagerDelegate> delegate;	// G=0x3a88cd; S=0x3a88ed; 
@property(retain, nonatomic) HJUserActivationResponse* userInfo;	// G=0x3a8895; S=0x3a88a5; 
@property(readonly, assign, nonatomic) TencentOAuth* tecentOAuth;	// G=0x3a8885; 
+(id)allocWithZone:(NSZone*)zone;	// 0x3a132d
+(id)new;	// 0x3a130d
+(id)sharedTPUManager;	// 0x3a1239
-(void).cxx_destruct;	// 0x3a8939
-(void)bindSinaWithID:(id)anId token:(id)token;	// 0x3a8549
-(void)bindWechatWithRequest:(id)request;	// 0x3a8091
-(void)bindWechatAuthentificateWithViewController:(id)viewController andDelegate:(id)delegate;	// 0x3a7f21
-(void)bindSinaWeiboAuthenticateWithDelegate:(id)delegate;	// 0x3a7e0d
-(void)postSinaWeiboWithContent:(id)content image:(id)image orPictureURL:(id)url;	// 0x3a7c81
-(BOOL)postQQZoneWithTitle:(id)title description:(id)description url:(id)url previewImageData:(id)data scene:(int)scene;	// 0x3a7bb5
-(BOOL)postQQWithTitle:(id)title description:(id)description url:(id)url previewImageData:(id)data scene:(int)scene;	// 0x3a7ae9
-(BOOL)postImgToQQWithTitle:(id)title description:(id)description image:(id)image;	// 0x3a79d9
-(BOOL)postQQWithTitle:(id)title description:(id)description thumbImage:(id)image image:(id)image4 url:(id)url scene:(int)scene;	// 0x3a7771
-(BOOL)postWeixinWithTitle:(id)title description:(id)description thumbImage:(id)image image:(id)image4 url:(id)url scene:(int)scene;	// 0x3a7301
-(void)tencentDidNotLogin:(BOOL)tencent;	// 0x3a72d5
-(void)tencentDidNotNetWork;	// 0x3a72c1
-(void)tencentDidLogin;	// 0x3a637d
-(void)bindQQAuthentificateWithViewController:(id)viewController andDelegate:(id)delegate;	// 0x3a6225
-(void)QQAuthenticateWithDelegate:(id)delegate;	// 0x3a60cd
-(void)userLoginWithPhone:(id)phone verifyCode:(id)code delegate:(id)delegate completion:(id)completion;	// 0x3a5775
-(void)userLoginWithPhone:(id)phone password:(id)password verifyCode:(id)code delegate:(id)delegate failure:(id)failure;	// 0x3a4d41
-(void)userForgetPasswordWithPhone:(id)phone npassword:(id)npassword verifyCode:(id)code delegate:(id)delegate failure:(id)failure;	// 0x3a4d3d
-(void)userLoginWithPhone:(id)phone password:(id)password delegate:(id)delegate failure:(id)failure;	// 0x3a4331
-(void)userRegisteWithPhone:(id)phone password:(id)password verifyCode:(id)code delegate:(id)delegate failure:(id)failure;	// 0x3a3941
-(void)onResp:(id)resp;	// 0x3a34e1
-(void)connection:(id)connection didReceiveData:(id)data;	// 0x3a26c9
-(void)connection:(id)connection didFailWithError:(id)error;	// 0x3a2625
-(id)parseToStringValue:(id)stringValue;	// 0x3a2609
-(void)didReceiveWeiboResponse:(id)response;	// 0x3a1859
-(void)didReceiveWeiboRequest:(id)request;	// 0x3a1805
-(BOOL)isWBAppInstalled;	// 0x3a17e9
-(BOOL)isWXAppInstalled;	// 0x3a17cd
-(void)wechatAuthentificateWithViewController:(id)viewController andDelegate:(id)delegate;	// 0x3a16d5
-(void)sinaWeiboAuthenticateWithDelegate:(id)delegate;	// 0x3a15e1
-(BOOL)handleOpenURL:(id)url sourceApplication:(id)application;	// 0x3a1505
-(id)registerTecent;	// 0x3a149d
-(BOOL)registerSinaWeibo;	// 0x3a1459
-(BOOL)registerWeChat;	// 0x3a1431
-(id)init;	// 0x3a134d
@end

