/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ZZAction.h"

@class AFHTTPRequestOperationManager;

__attribute__((visibility("hidden")))
@interface HJUpdateSplashAction : ZZAction {
	AFHTTPRequestOperationManager* _manager;
}
-(void).cxx_destruct;	// 0x2d5c8d
-(void)getData:(id)data completion:(id)completion failure:(id)failure;	// 0x2d59bd
-(void)start;	// 0x2d492d
@end

