/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJTableViewCell.h"

@class UILabel, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface HJUserWalletTableViewCell : HJTableViewCell {
	UILabel* _userWalletLabel;
	UIActivityIndicatorView* _activityIndicator;
}
@property(assign, nonatomic) __weak UIActivityIndicatorView* activityIndicator;	// G=0x28cb1d; S=0x28cb3d; 
@property(assign, nonatomic) __weak UILabel* userWalletLabel;	// G=0x28cae9; S=0x28cb09; 
-(void).cxx_destruct;	// 0x28cb51
-(void)showBalance;	// 0x28c83d
-(void)setBalanceLabel:(int)label;	// 0x28c689
-(void)awakeFromNib;	// 0x28c579
@end

