/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJLiveBaseController.h"

@class NSString, HJUserIntf, UIView, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HJUserFollowingViewController : HJLiveBaseController {
	HJUserIntf* _refreshIntf;
	HJUserIntf* _loadmoreIntf;
	BOOL _isMyself;
	UIView* _emtpyView;
	NSString* _userId;
	NSMutableArray* _dataArray;
}
@property(assign, nonatomic) BOOL isMyself;	// G=0xd37e9; S=0xd37f9; 
@property(retain, nonatomic) NSMutableArray* dataArray;	// G=0xd37b1; S=0xd37c1; 
@property(retain, nonatomic) NSString* userId;	// G=0xd3779; S=0xd3789; 
@property(retain, nonatomic) UIView* emtpyView;	// G=0xd249d; S=0xd3751; 
-(void).cxx_destruct;	// 0xd3809
-(void)onUserFollowStatusChangedNotification:(id)notification;	// 0xd3545
-(void)doLoadmore;	// 0xd31c1
-(void)handleRefresh:(id)refresh;	// 0xd2db9
-(void)doRefresh;	// 0xd2d69
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0xd2d61
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0xd2c11
-(int)numberOfSectionsInTableView:(id)tableView;	// 0xd2c0d
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0xd2bd1
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0xd2ad5
-(id)itemArray;	// 0xd2a75
-(void)showTable;	// 0xd2439
-(void)showEmpty;	// 0xd23d5
-(void)viewDidDisappear:(BOOL)view;	// 0xd2349
-(void)viewWillAppear:(BOOL)view;	// 0xd2289
-(void)viewWillLayoutSubviews;	// 0xd217d
-(void)onClickBack;	// 0xd2139
-(void)setupNavigationBar;	// 0xd1e2d
-(void)onUserInfoChangedNotification:(id)notification;	// 0xd1ad1
-(void)viewDidLoad;	// 0xd17cd
-(void)setTitle:(id)title;	// 0xd1641
-(void)dealloc;	// 0xd15d5
-(id)initWithUserId:(id)userId;	// 0xd13e1
@end

