/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface HJUserGetDiscoveryResponse : XXUnknownSuperclass {
	BOOL _beMore;
	NSArray* _friendes;
	NSArray* _anchors;
	int _offset;
}
@property(assign, nonatomic) int offset;	// G=0x3c9e0d; S=0x3c9e1d; 
@property(assign, nonatomic) BOOL beMore;	// G=0x3c9ded; S=0x3c9dfd; 
@property(retain, nonatomic) NSArray* anchors;	// G=0x3c9db5; S=0x3c9dc5; 
@property(retain, nonatomic) NSArray* friendes;	// G=0x3c9d7d; S=0x3c9d8d; 
+(id)responseWithUserInfo:(id)userInfo;	// 0x3c998d
-(void).cxx_destruct;	// 0x3c9e2d
@end

