/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "HJServices.h"
#import "HJServicesConstraits.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface HJVerifiedIntf : HJServices <HJServicesConstraits> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)allocWithZone:(NSZone*)zone;	// 0x1b7b19
+(id)new;	// 0x1b7af9
+(id)sharedIntfs;	// 0x1b7a25
-(id)getFollowingRecommendationsByOffset:(int)offset Complete:(id)complete failured:(id)failured;	// 0x1b83ed
-(id)verified_getAllCategories:(int)categories complete:(id)complete failured:(id)failured;	// 0x1b8259
-(id)verified_GetCategorie:(id)categorie offset:(int)offset complete:(id)complete failured:(id)failured;	// 0x1b7f45
-(id)verified_GetCategories:(id)categories failured:(id)failured;	// 0x1b7b89
-(id)init;	// 0x1b7b39
@end

