/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol HJVideoViewDelegate <NSObject>
@optional
-(void)playEnd:(id)end;
-(void)currentPlayerTimeLengh:(float)lengh;
-(void)bufferTimeLengh:(float)lengh;
-(void)dontPlayer:(id)player;
-(void)networkNotBest:(id)best;
-(void)readyStartPlaying:(id)playing;
@end

