/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UIImageView, AVPlayer, AVPlayerItem, UIActivityIndicatorView, HJPlayerProgressSlider;
@protocol HJVideoViewDelegate;

__attribute__((visibility("hidden")))
@interface HJVideoView : XXUnknownSuperclass {
	AVPlayer* _player;
	AVPlayerItem* _playerItem;
	float _currentTime;
	BOOL _isScrollPaused;
	NSString* _videoModel;
	int _timeScale;
	id<HJVideoViewDelegate> _delegate;
	HJPlayerProgressSlider* _progressSlider;
	int _playbackState;
	UIActivityIndicatorView* _activityIndicatorView;
	NSString* _contentUrl;
	float _totalTime;
	UIImageView* _playBtnImageView;
}
@property(retain, nonatomic) UIImageView* playBtnImageView;	// G=0x16be91; S=0x16bea1; 
@property(retain, nonatomic) NSString* videoModel;	// G=0x16be81; S=0x16ad99; 
@property(readonly, assign, nonatomic) int timeScale;	// G=0x16be71; 
@property(readonly, assign) float totalTime;	// G=0x16be61; 
@property(retain, nonatomic) NSString* contentUrl;	// G=0x16be51; S=0x16ae09; 
@property(retain, nonatomic) UIActivityIndicatorView* activityIndicatorView;	// G=0x16be19; S=0x16be29; 
@property(assign, nonatomic) int playbackState;	// G=0x16bdf9; S=0x16be09; 
@property(retain, nonatomic) HJPlayerProgressSlider* progressSlider;	// G=0x16bdc1; S=0x16bdd1; 
@property(assign, nonatomic) __weak id<HJVideoViewDelegate> delegate;	// G=0x16bd8d; S=0x16bdad; 
-(void).cxx_destruct;	// 0x16bec9
-(void)scrollTrigger:(id)trigger;	// 0x16bbc5
-(void)monitoringPlayback:(id)playback;	// 0x16b939
-(void)updateSliderValue:(id)value;	// 0x16b861
-(double)availableDuration;	// 0x16b779
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;	// 0x16b2b5
-(void)moviePlayDidEnd:(id)moviePlay;	// 0x16b211
-(id)_setVideoModel:(id)model;	// 0x16b1bd
-(void)_setAssert:(id)anAssert;	// 0x16af21
-(void)speed:(XXStruct_pwHToB)speed;	// 0x16ad2d
-(void)repeatPlaying;	// 0x16aca5
-(void)stop;	// 0x16ac59
-(void)pause;	// 0x16ac01
-(void)play;	// 0x16ab99
-(void)dealloc;	// 0x16aaf9
-(void)Actiondo:(id)actiondo;	// 0x16aa9d
-(id)initWithFrame:(CGRect)frame contentUrl:(id)url withDelegate:(id)delegate;	// 0x16a711
@end

