/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"


@protocol HPGrowingTextViewDelegate
@optional
-(BOOL)growingTextViewShouldReturn:(id)growingTextView;
-(void)growingTextViewDidChangeSelection:(id)growingTextView;
-(void)growingTextView:(id)view didChangeHeight:(float)height;
-(void)growingTextView:(id)view willChangeHeight:(float)height;
-(void)growingTextViewDidChange:(id)growingTextView;
-(BOOL)growingTextView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)growingTextViewDidEndEditing:(id)growingTextView;
-(void)growingTextViewDidBeginEditing:(id)growingTextView;
-(BOOL)growingTextViewShouldEndEditing:(id)growingTextView;
-(BOOL)growingTextViewShouldBeginEditing:(id)growingTextView;
@end

