/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSTableViewController.h"

@class HJErrorView, UIView, HJLoadingView2, HJDiscEmptyView;

__attribute__((visibility("hidden")))
@interface HSDiscAniController : DSTableViewController {
	UIView* _emtpyView;
	UIView* _errorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	HJDiscEmptyView* _theEmptyView;
	HJErrorView* _theErrorView;
}
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x1ac291; S=0x1ac2a1; 
@property(retain, nonatomic) HJDiscEmptyView* theEmptyView;	// G=0x1ac259; S=0x1ac269; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x1ac221; S=0x1ac231; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x1abaed; S=0x1ac1f9; 
@property(retain, nonatomic) UIView* errorView;	// G=0x1abd55; S=0x1ac1d1; 
@property(retain, nonatomic) UIView* emtpyView;	// G=0x1abf61; S=0x1ac1a9; 
-(void).cxx_destruct;	// 0x1ac2c9
-(void)showTable;	// 0x1aba09
-(void)showError;	// 0x1ab925
-(void)showEmpty;	// 0x1ab841
-(void)showLoading;	// 0x1ab75d
-(void)setupSubviews;	// 0x1ab5fd
-(void)viewDidLayoutSubviews;	// 0x1ab2f1
-(void)viewDidLoad;	// 0x1ab2b1
@end

