/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageVideoCamera.h"

@class AVAudioRecorder, UIImage, GPUImageFilter, GPUImagePicture, GPUImageMovieWriter, AVCaptureStillImageOutput, GPUImageView, NSObject, IFRotationFilter, AVMutableComposition, AVAssetExportSession;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface IFVideoCamera : GPUImageVideoCamera {
	BOOL isRecordingMovie;
	GPUImageFilter* filter;
	GPUImagePicture* sourcePicture1;
	GPUImagePicture* sourcePicture2;
	GPUImagePicture* sourcePicture3;
	GPUImagePicture* sourcePicture4;
	GPUImagePicture* sourcePicture5;
	GPUImageFilter* internalFilter;
	GPUImagePicture* internalSourcePicture1;
	GPUImagePicture* internalSourcePicture2;
	GPUImagePicture* internalSourcePicture3;
	GPUImagePicture* internalSourcePicture4;
	GPUImagePicture* internalSourcePicture5;
	GPUImageView* gpuImageView;
	GPUImageView* gpuImageView_HD;
	IFRotationFilter* rotationFilter;
	int currentFilterType;
	NSObject<OS_dispatch_queue>* prepareFilterQueue;
	UIImage* rawImage;
	GPUImagePicture* stillImageSource;
	AVCaptureStillImageOutput* stillImageOutput;
	id delegate;
	GPUImageMovieWriter* movieWriter;
	AVAudioRecorder* soundRecorder;
	AVMutableComposition* mutableComposition;
	AVAssetExportSession* assetExportSession;
}
@property(retain, nonatomic) AVAssetExportSession* assetExportSession;	// G=0x316385; S=0x316395; 
@property(retain, nonatomic) AVMutableComposition* mutableComposition;	// G=0x31634d; S=0x31635d; 
@property(retain, nonatomic) AVAudioRecorder* soundRecorder;	// G=0x316315; S=0x316325; 
@property(retain, nonatomic) GPUImageMovieWriter* movieWriter;	// G=0x3162bd; S=0x3162cd; 
@property(retain, nonatomic) AVCaptureStillImageOutput* stillImageOutput;	// G=0x316265; S=0x316275; 
@property(retain, nonatomic) GPUImagePicture* stillImageSource;	// G=0x31622d; S=0x31623d; 
@property(assign, nonatomic) NSObject<OS_dispatch_queue>* prepareFilterQueue;	// G=0x3161d5; S=0x3161e5; 
@property(assign, nonatomic) int currentFilterType;	// G=0x3161b5; S=0x3161c5; 
@property(retain, nonatomic) IFRotationFilter* rotationFilter;	// G=0x31617d; S=0x31618d; 
@property(retain, nonatomic) GPUImagePicture* internalSourcePicture5;	// G=0x3160fd; S=0x31610d; 
@property(retain, nonatomic) GPUImagePicture* internalSourcePicture4;	// G=0x3160c5; S=0x3160d5; 
@property(retain, nonatomic) GPUImagePicture* internalSourcePicture3;	// G=0x31608d; S=0x31609d; 
@property(retain, nonatomic) GPUImagePicture* internalSourcePicture2;	// G=0x316055; S=0x316065; 
@property(retain, nonatomic) GPUImagePicture* internalSourcePicture1;	// G=0x31601d; S=0x31602d; 
@property(retain, nonatomic) GPUImageFilter* internalFilter;	// G=0x315fe5; S=0x315ff5; 
@property(retain, nonatomic) GPUImagePicture* sourcePicture5;	// G=0x315fad; S=0x315fbd; 
@property(retain, nonatomic) GPUImagePicture* sourcePicture4;	// G=0x315f75; S=0x315f85; 
@property(retain, nonatomic) GPUImagePicture* sourcePicture3;	// G=0x315f3d; S=0x315f4d; 
@property(retain, nonatomic) GPUImagePicture* sourcePicture2;	// G=0x315f05; S=0x315f15; 
@property(retain, nonatomic) GPUImagePicture* sourcePicture1;	// G=0x315ecd; S=0x315edd; 
@property(retain, nonatomic) GPUImageFilter* filter;	// G=0x315e95; S=0x315ea5; 
@property(assign, nonatomic) BOOL isRecordingMovie;	// G=0x3162f5; S=0x316305; 
@property(assign, nonatomic) id delegate;	// G=0x31629d; S=0x3162ad; 
@property(retain, nonatomic) UIImage* rawImage;	// G=0x3161f5; S=0x316205; 
@property(retain) GPUImageView* gpuImageView_HD;	// G=0x316159; S=0x31616d; 
@property(retain) GPUImageView* gpuImageView;	// G=0x316135; S=0x316149; 
-(void).cxx_destruct;	// 0x3163bd
-(id)initWithSessionPreset:(id)sessionPreset cameraPosition:(int)position highVideoQuality:(BOOL)quality;	// 0x315b05
-(void)switchFilter:(int)filter;	// 0x315969
-(void)forceSwitchToNewFilter:(int)newFilter;	// 0x3130f1
-(void)switchToNewFilter;	// 0x311749
-(void)cancelAlbumPhotoAndGoBackToNormal;	// 0x31165d
-(void)takePhoto;	// 0x311189
-(CGSize)properSizeForResizingLargeImage:(id)resizingLargeImage;	// 0x3110f5
-(id)fileURLForTempMovie;	// 0x310f81
-(void)removeFile:(id)file;	// 0x310ec5
-(void)stopRecordingMovie;	// 0x310d7d
-(void)startRecordingMovie;	// 0x310bd5
-(BOOL)canStartRecordingMovie;	// 0x310b51
-(void)stopRecordingSound;	// 0x310ac1
-(void)prepareToRecordSound;	// 0x310879
-(void)startRecordingSound;	// 0x310859
-(id)fileURLForTempSound;	// 0x3106e5
-(void)initializeSoundRecorder;	// 0x31069d
-(void)image:(id)image didFinishSavingWithError:(id)error contextInfo:(void*)info;	// 0x310619
-(void)video:(id)video didFinishSavingWithError:(id)error contextInfo:(void*)info;	// 0x310501
-(void)combineSoundAndMovie;	// 0x30fc61
-(id)fileURLForFinalMixedAsset;	// 0x30faed
-(void)focusAndAutoContinuousFocusAtPoint:(CGPoint)point;	// 0x30f8f1
-(void)focusAndLockAtPoint:(CGPoint)point;	// 0x30f6f5
-(void)saveCurrentStillImage;	// 0x30f641
@end

