/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IMProtoHelper.h"


@interface IMProtoVoiceCallProxy : IMProtoHelper {
}
-(id)createChannelRequestWithCaller:(id)caller callee:(id)callee sn:(int)sn;	// 0xa59b41
@end

