/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IMUser, IMMessage;

@interface IMTask : XXUnknownSuperclass {
	int _taskType;
	IMMessage* _message;
	IMUser* _user;
}
@property(assign) IMUser* user;	// G=0x9dcd91; S=0x9dcda1; 
@property(retain) IMMessage* message;	// G=0x9dcd6d; S=0x9dcd81; 
@property(assign) int taskType;	// G=0x9dcd4d; S=0x9dcd5d; 
-(void).cxx_destruct;	// 0x9dcdb1
-(void)main;	// 0x9dcc95
-(id)initTask:(id)task User:(id)user;	// 0x9dcc05
-(id)initTask:(int)task Message:(id)message User:(id)user;	// 0x9dcb6d
@end

