/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, Verifiedinfo;

__attribute__((visibility("hidden")))
@interface Invitee : XXUnknownSuperclass {
	BOOL _verified;
	NSString* _uid;
	NSString* _nickname;
	NSString* _avatar;
	NSString* _avatar_l;
	NSString* _signature;
	NSString* _lives;
	NSString* _watches;
	NSString* _praises;
	NSString* _followings;
	NSString* _followed;
	NSString* _blocked;
	NSString* _gender;
	NSString* _astro;
	NSString* _location;
	Verifiedinfo* _verifiedInfo;
	NSString* _source;
	NSString* _balance;
}
@property(retain, nonatomic) NSString* balance;	// G=0x20d615; S=0x20d625; 
@property(retain, nonatomic) NSString* source;	// G=0x20d5dd; S=0x20d5ed; 
@property(retain, nonatomic) Verifiedinfo* verifiedInfo;	// G=0x20d5a5; S=0x20d5b5; 
@property(assign, nonatomic) BOOL verified;	// G=0x20d585; S=0x20d595; 
@property(retain, nonatomic) NSString* location;	// G=0x20d54d; S=0x20d55d; 
@property(retain, nonatomic) NSString* astro;	// G=0x20d515; S=0x20d525; 
@property(retain, nonatomic) NSString* gender;	// G=0x20d4dd; S=0x20d4ed; 
@property(retain, nonatomic) NSString* blocked;	// G=0x20d4a5; S=0x20d4b5; 
@property(retain, nonatomic) NSString* followed;	// G=0x20d46d; S=0x20d47d; 
@property(retain, nonatomic) NSString* followings;	// G=0x20d435; S=0x20d445; 
@property(retain, nonatomic) NSString* praises;	// G=0x20d3fd; S=0x20d40d; 
@property(retain, nonatomic) NSString* watches;	// G=0x20d3c5; S=0x20d3d5; 
@property(retain, nonatomic) NSString* lives;	// G=0x20d38d; S=0x20d39d; 
@property(retain, nonatomic) NSString* signature;	// G=0x20d355; S=0x20d365; 
@property(retain, nonatomic) NSString* avatar_l;	// G=0x20d31d; S=0x20d32d; 
@property(retain, nonatomic) NSString* avatar;	// G=0x20d2e5; S=0x20d2f5; 
@property(retain, nonatomic) NSString* nickname;	// G=0x20d2ad; S=0x20d2bd; 
@property(retain, nonatomic) NSString* uid;	// G=0x20d275; S=0x20d285; 
+(id)responseWithInfo:(id)info;	// 0x20cbf1
-(void).cxx_destruct;	// 0x20d64d
@end

