/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IPAYTextField.h"


@interface IPAYBankField : IPAYTextField {
}
-(id)removeNonDigits:(id)digits andPreserveCursorPosition:(unsigned*)position;	// 0xb6015d
-(id)init;	// 0xb60131
@end

