/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UILabel, UITapGestureRecognizer;

@interface IPAYMarqueeLabel : XXUnknownSuperclass {
	BOOL _labelize;
	BOOL _holdScrolling;
	BOOL _tapToScroll;
	BOOL _isPaused;
	BOOL _orientationWillChange;
	unsigned _animationCurve;
	unsigned _marqueeType;
	float _scrollDuration;
	float _rate;
	float _leadingBuffer;
	float _trailingBuffer;
	float _fadeLength;
	float _animationDelay;
	UILabel* _subLabel;
	id _orientationObserver;
	UITapGestureRecognizer* _tapRecognizer;
	NSArray* _gradientColors;
	double _animationDuration;
	CGRect _homeLabelFrame;
	CGRect _awayLabelFrame;
}
@property(retain, nonatomic) NSArray* gradientColors;	// G=0xb67b7d; S=0xb68021; 
@property(assign, nonatomic) CGRect awayLabelFrame;	// G=0xb67fe5; S=0xb67ffd; 
@property(assign, nonatomic) CGRect homeLabelFrame;	// G=0xb67fa9; S=0xb67fc1; 
@property(assign, nonatomic) __weak UITapGestureRecognizer* tapRecognizer;	// G=0xb67f75; S=0xb67f95; 
@property(readonly, assign, nonatomic) BOOL labelShouldScroll;	// G=0xb63855; 
@property(assign, nonatomic) double animationDuration;	// G=0xb67f49; S=0xb67f61; 
@property(retain, nonatomic) id orientationObserver;	// G=0xb67f25; S=0xb67f35; 
@property(assign, nonatomic) BOOL orientationWillChange;	// G=0xb67f05; S=0xb67f15; 
@property(retain, nonatomic) UILabel* subLabel;	// G=0xb67ecd; S=0xb67edd; 
@property(readonly, assign, nonatomic) BOOL awayFromHome;	// G=0xb67aa1; 
@property(assign, nonatomic) BOOL isPaused;	// G=0xb67ead; S=0xb67ebd; 
@property(assign, nonatomic) float animationDelay;	// G=0xb67e8d; S=0xb67e9d; 
@property(assign, nonatomic) float fadeLength;	// G=0xb67e7d; S=0xb67795; 
@property(assign, nonatomic) float continuousMarqueeExtraBuffer;	// G=0xb67785; S=0xb67775; 
@property(assign, nonatomic) float trailingBuffer;	// G=0xb67e6d; S=0xb67739; 
@property(assign, nonatomic) float leadingBuffer;	// G=0xb67e5d; S=0xb676fd; 
@property(assign, nonatomic) float rate;	// G=0xb67e4d; S=0xb6764d; 
@property(assign, nonatomic) float scrollDuration;	// G=0xb67e3d; S=0xb67695; 
@property(assign, nonatomic) unsigned marqueeType;	// G=0xb67e2d; S=0xb678f5; 
@property(assign, nonatomic) BOOL tapToScroll;	// G=0xb67e1d; S=0xb677ed; 
@property(assign, nonatomic) BOOL holdScrolling;	// G=0xb67e0d; S=0xb67a4d; 
@property(assign, nonatomic) BOOL labelize;	// G=0xb67dfd; S=0xb67a1d; 
@property(assign, nonatomic) unsigned animationCurve;	// G=0xb67ded; S=0xb676dd; 
+(void)notifyController:(id)controller withMessage:(id)message;	// 0xb6179d
+(void)controllerLabelsShouldAnimate:(id)controllerLabels;	// 0xb61775
+(void)controllerLabelsShouldLabelize:(id)controllerLabels;	// 0xb6174d
+(void)controllerViewAppearing:(id)appearing;	// 0xb61731
+(void)controllerViewDidAppear:(id)controllerView;	// 0xb61715
+(void)controllerViewWillAppear:(id)controllerView;	// 0xb616f9
+(void)restartLabelsOfController:(id)controller;	// 0xb616d1
-(void).cxx_destruct;	// 0xb68049
-(void)dealloc;	// 0xb67d2d
-(id)allSubLabels:(BOOL)labels;	// 0xb67ca1
-(id)secondarySubLabels;	// 0xb67c8d
-(id)allSubLabels;	// 0xb67c79
-(void)updateSubLabelsForKeysWithValues:(id)values;	// 0xb674a9
-(void)updateSubLabelsForKey:(id)key withValue:(id)value;	// 0xb673b1
-(void)refreshSubLabels:(id)labels;	// 0xb67199
-(void)setMinimumScaleFactor:(float)factor;	// 0xb67169
-(void)setAdjustsLetterSpacingToFitWidth:(BOOL)fitWidth;	// 0xb67139
-(CGSize)intrinsicContentSize;	// 0xb670f1
-(void)setBaselineAdjustment:(int)adjustment;	// 0xb6709d
-(int)baselineAdjustment;	// 0xb67061
-(void)setMinimumFontSize:(float)size;	// 0xb67031
-(void)setAdjustsFontSizeToFitWidth:(BOOL)fitWidth;	// 0xb67001
-(void)setNumberOfLines:(int)lines;	// 0xb66fd1
-(void)setEnabled:(BOOL)enabled;	// 0xb66f7d
-(BOOL)isEnabled;	// 0xb66f41
-(void)setHighlighted:(BOOL)highlighted;	// 0xb66eed
-(BOOL)isHighlighted;	// 0xb66eb1
-(void)setHighlightedTextColor:(id)color;	// 0xb66e95
-(id)highlightedTextColor;	// 0xb66e4d
-(void)setShadowOffset:(CGSize)offset;	// 0xb66df9
-(CGSize)shadowOffset;	// 0xb66db1
-(void)setShadowColor:(id)color;	// 0xb66d95
-(id)shadowColor;	// 0xb66d4d
-(void)setBackgroundColor:(id)color;	// 0xb66ce1
-(id)backgroundColor;	// 0xb66c99
-(void)setTextColor:(id)color;	// 0xb66c7d
-(id)textColor;	// 0xb66c35
-(void)setFont:(id)font;	// 0xb66b79
-(id)font;	// 0xb66b31
-(void)setAttributedText:(id)text;	// 0xb66a75
-(id)attributedText;	// 0xb66a2d
-(void)setText:(id)text;	// 0xb66971
-(id)text;	// 0xb66929
-(id)viewForBaselineLayout;	// 0xb66919
-(void)setBounds:(CGRect)bounds;	// 0xb6683d
-(void)setFrame:(CGRect)frame;	// 0xb66761
-(void)labelReturnedToHome:(BOOL)home;	// 0xb6675d
-(void)labelWillBeginScroll;	// 0xb66759
-(void)triggerScrollStart;	// 0xb66709
-(void)labelWasTapped:(id)tapped;	// 0xb666d1
-(void)unpauseLabel;	// 0xb662c1
-(void)pauseLabel;	// 0xb66039
-(void)shutdownLabel;	// 0xb66029
-(void)resetLabel;	// 0xb65fbd
-(void)restartLabel;	// 0xb65f55
-(void)animationDidStop:(id)animation finished:(BOOL)finished;	// 0xb65f15
-(id)timingFunctionForAnimationOptions:(unsigned)animationOptions;	// 0xb65e95
-(id)keyFrameAnimationForProperty:(id)property values:(id)values interval:(double)interval delay:(double)delay;	// 0xb65b89
-(id)keyFrameAnimationForGradientFadeLength:(float)gradientFadeLength interval:(double)interval delay:(double)delay;	// 0xb64fc1
-(void)removeGradientMask;	// 0xb64f85
-(void)applyGradientMaskForFadeLength:(float)fadeLength animated:(BOOL)animated;	// 0xb648b1
-(void)scrollContinuousWithInterval:(double)interval after:(double)after;	// 0xb64241
-(void)scrollAwayWithInterval:(double)interval delayAmount:(double)amount;	// 0xb63c7d
-(void)scrollAwayWithInterval:(double)interval delay:(BOOL)delay;	// 0xb63c29
-(void)scrollAwayWithInterval:(double)interval;	// 0xb63c05
-(void)returnLabelToOriginImmediately;	// 0xb63acd
-(void)beginScrollWithDelay:(BOOL)delay;	// 0xb63a25
-(void)beginScroll;	// 0xb63a11
-(BOOL)labelReadyForScroll;	// 0xb63989
-(CGSize)sizeThatFits:(CGSize)fits;	// 0xb637c5
-(CGSize)subLabelSize;	// 0xb6370d
-(void)updateSublabelAndLocationsAndBeginScroll:(BOOL)scroll;	// 0xb62795
-(void)updateSublabelAndLocations;	// 0xb62781
-(void)didMoveToWindow;	// 0xb62725
-(void)willMoveToWindow:(id)window;	// 0xb6270d
-(void)layoutSubviews;	// 0xb626c9
-(void)didMoveToSuperview;	// 0xb626b5
-(void)minimizeLabelFrameWithMaximumSize:(CGSize)maximumSize adjustHeight:(BOOL)height;	// 0xb624fd
-(void)observedViewControllerChange:(id)change;	// 0xb62415
-(void)setupLabel;	// 0xb6204d
-(void)forwardPropertiesToSubLabel;	// 0xb61c55
-(void)awakeFromNib;	// 0xb61c15
-(id)initWithCoder:(id)coder;	// 0xb61b99
-(id)initWithFrame:(CGRect)frame rate:(float)rate andFadeLength:(float)length;	// 0xb61ae5
-(id)initWithFrame:(CGRect)frame duration:(double)duration andFadeLength:(float)length;	// 0xb61a2d
-(id)initWithFrame:(CGRect)frame;	// 0xb619f5
-(void)labelsShouldAnimate:(id)labels;	// 0xb61969
-(void)labelsShouldLabelize:(id)labels;	// 0xb618dd
-(void)viewControllerShouldRestart:(id)viewController;	// 0xb61855
@end

