/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface IPAYFeeInfoSchema : XXUnknownSuperclass {
	NSString* _mFeeId;
	int _mFeeType;
	int _mPrice;
	NSString* _mFeeTip;
}
@property(retain, nonatomic) NSString* mFeeTip;	// G=0xb5a721; S=0xb5a731; 
@property(assign, nonatomic) int mPrice;	// G=0xb5a701; S=0xb5a711; 
@property(assign, nonatomic) int mFeeType;	// G=0xb5a6e1; S=0xb5a6f1; 
@property(retain, nonatomic) NSString* mFeeId;	// G=0xb5a6a9; S=0xb5a6b9; 
+(id)parseData:(id)data;	// 0xb5a30d
-(void).cxx_destruct;	// 0xb5a759
-(id)description;	// 0xb5a5ed
-(BOOL)copy:(id)copy;	// 0xb5a51d
-(void)reset;	// 0xb5a4c1
-(void)dealloc;	// 0xb5a481
-(id)init;	// 0xb5a43d
@end

