/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface IPAYLimitInput : XXUnknownSuperclass {
	BOOL _enableLimitCount;
}
@property(assign, nonatomic) BOOL enableLimitCount;	// G=0xb7096d; S=0xb7097d; 
+(id)sharedInstance;	// 0xb7053d
+(void)load;	// 0xb704e9
-(void)textViewDidChange:(id)textView;	// 0xb70819
-(void)textFieldViewDidChange:(id)textFieldView;	// 0xb706c5
-(id)init;	// 0xb705dd
@end

