/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"


@interface IPAYStretchImageView : XXUnknownSuperclass {
}
-(void)reStretch;	// 0xb602d5
-(void)resizableImageWithInsets:(UIEdgeInsets)insets;	// 0xb60255
@end

