/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface IPAYGetSmsCodeSchema : XXUnknownSuperclass {
	NSString* _mSeq;
	int _mExpired;
}
@property(assign, nonatomic) int mExpired;	// G=0xb5e815; S=0xb5e825; 
@property(retain, nonatomic) NSString* mSeq;	// G=0xb5e7dd; S=0xb5e7ed; 
+(id)parseData:(id)data;	// 0xb5e569
-(void).cxx_destruct;	// 0xb5e835
-(id)description;	// 0xb5e761
-(BOOL)copy:(id)copy;	// 0xb5e6ed
-(void)reset;	// 0xb5e6b9
-(void)dealloc;	// 0xb5e679
-(id)init;	// 0xb5e635
@end

