/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSArray;

@interface IPAYOrderSchema : XXUnknownSuperclass {
	NSString* _mTransId;
	NSString* _mCpName;
	NSString* _mAppName;
	NSString* _mWaresName;
	NSString* _mServiceNo;
	NSArray* _mFeeInfoList;
	NSArray* _mPayTypeList;
}
@property(retain, nonatomic) NSArray* mPayTypeList;	// G=0xb59bc1; S=0xb59bd1; 
@property(retain, nonatomic) NSArray* mFeeInfoList;	// G=0xb59b89; S=0xb59b99; 
@property(retain, nonatomic) NSString* mServiceNo;	// G=0xb59b51; S=0xb59b61; 
@property(retain, nonatomic) NSString* mWaresName;	// G=0xb59b19; S=0xb59b29; 
@property(retain, nonatomic) NSString* mAppName;	// G=0xb59ae1; S=0xb59af1; 
@property(retain, nonatomic) NSString* mCpName;	// G=0xb59aa9; S=0xb59ab9; 
@property(retain, nonatomic) NSString* mTransId;	// G=0xb59a71; S=0xb59a81; 
+(id)parseData:(id)data;	// 0xb5933d
-(void).cxx_destruct;	// 0xb59bf9
-(id)description;	// 0xb59925
-(BOOL)copy:(id)copy;	// 0xb5979d
-(void)reset;	// 0xb59705
-(void)dealloc;	// 0xb596c5
-(id)init;	// 0xb59681
@end

