/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface IPAYNotifySchema : XXUnknownSuperclass {
	NSString* _mNotifyUrl;
}
@property(retain, nonatomic) NSString* mNotifyUrl;	// G=0xb5c775; S=0xb5c785; 
+(id)parseData:(id)data;	// 0xb5c5a1
-(void).cxx_destruct;	// 0xb5c7ad
-(id)description;	// 0xb5c715
-(BOOL)copy:(id)copy;	// 0xb5c6d5
-(void)reset;	// 0xb5c6c1
-(void)dealloc;	// 0xb5c681
-(id)init;	// 0xb5c63d
@end

