/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UITextRange;

@interface IPAYTextField : XXUnknownSuperclass {
	NSString* previousTextFieldContent;
	UITextRange* previousSelection;
	int _maxDigitLimit;
	id _ipayFieldBlock;
}
@property(copy, nonatomic) id ipayFieldBlock;	// G=0xb72519; S=0xb7252d; 
@property(assign, nonatomic) int maxDigitLimit;	// G=0xb72509; S=0xb71ec9; 
-(void).cxx_destruct;	// 0xb7253d
-(void)shouldChangeCharactersInRange:(id)range;	// 0xb72439
-(void)reformatAsCardNumber:(id)number;	// 0xb721d1
-(id)insertSpacesEveryFourDigitsIntoString:(id)string andPreserveCursorPosition:(unsigned*)position;	// 0xb720c5
-(id)removeNonDigits:(id)digits andPreserveCursorPosition:(unsigned*)position;	// 0xb71fa9
-(void)dealloc;	// 0xb71f2d
-(id)init;	// 0xb71dfd
@end

