/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol IPAYMASConstraintDelegate;

@interface IPAYMASConstraint : XXUnknownSuperclass {
	BOOL _updateExisting;
	id<IPAYMASConstraintDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<IPAYMASConstraintDelegate> delegate;	// G=0xb60069; S=0xb60089; 
@property(assign, nonatomic) BOOL updateExisting;	// G=0xb60049; S=0xb60059; 
-(void).cxx_destruct;	// 0xb6009d
-(void)uninstall;	// 0xb5ffb1
-(void)install;	// 0xb5ff19
-(void)deactivate;	// 0xb5fe81
-(void)activate;	// 0xb5fde9
-(void)setOffset:(float)offset;	// 0xb5fd51
-(void)setCenterOffset:(CGPoint)offset;	// 0xb5fcb9
-(void)setSizeOffset:(CGSize)offset;	// 0xb5fc21
-(void)setInsets:(UIEdgeInsets)insets;	// 0xb5fb89
-(id)key;	// 0xb5faf1
-(id)equalToWithRelation;	// 0xb5fa59
-(id)priority;	// 0xb5f9c1
-(id)dividedBy;	// 0xb5f929
-(id)multipliedBy;	// 0xb5f891
-(id)centerYWithinMargins;	// 0xb5f87d
-(id)centerXWithinMargins;	// 0xb5f869
-(id)trailingMargin;	// 0xb5f855
-(id)leadingMargin;	// 0xb5f841
-(id)bottomMargin;	// 0xb5f82d
-(id)topMargin;	// 0xb5f819
-(id)rightMargin;	// 0xb5f805
-(id)leftMargin;	// 0xb5f7f1
-(id)baseline;	// 0xb5f7dd
-(id)centerY;	// 0xb5f7c9
-(id)centerX;	// 0xb5f7b5
-(id)height;	// 0xb5f7a1
-(id)width;	// 0xb5f78d
-(id)trailing;	// 0xb5f779
-(id)leading;	// 0xb5f765
-(id)bottom;	// 0xb5f751
-(id)right;	// 0xb5f73d
-(id)top;	// 0xb5f729
-(id)left;	// 0xb5f715
-(id)addConstraintWithLayoutAttribute:(int)layoutAttribute;	// 0xb5f67d
-(id)and;	// 0xb5f679
-(id)with;	// 0xb5f675
-(void)setLayoutConstantWithValue:(id)value;	// 0xb5f501
-(id)mas_offset;	// 0xb5f4fd
-(id)valueOffset;	// 0xb5f471
-(id)offset;	// 0xb5f3e5
-(id)centerOffset;	// 0xb5f355
-(id)sizeOffset;	// 0xb5f2c5
-(id)insets;	// 0xb5f221
-(id)priorityHigh;	// 0xb5f171
-(id)priorityMedium;	// 0xb5f0c5
-(id)priorityLow;	// 0xb5f019
-(id)mas_lessThanOrEqualTo;	// 0xb5ef5d
-(id)lessThanOrEqualTo;	// 0xb5eea1
-(id)mas_greaterThanOrEqualTo;	// 0xb5ede5
-(id)greaterThanOrEqualTo;	// 0xb5ed29
-(id)mas_equalTo;	// 0xb5ec6d
-(id)equalTo;	// 0xb5ebb1
-(id)init;	// 0xb5eb85
@end

