/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol IPAYAmountFootViewDelegate <NSObject>
@optional
-(void)footView:(id)view clickReturn:(id)aReturn;
-(void)footView:(id)view textChanged:(id)changed;
-(void)footView:(id)view clickClear:(id)clear;
-(void)footView:(id)view endEditing:(id)editing;
-(void)footView:(id)view beginEditing:(id)editing;
-(void)footView:(id)view clickPayButton:(id)button;
@end

