/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface IPAYActivitySchema : XXUnknownSuperclass {
	NSString* _mTitle;
	NSString* _mDetail;
	NSString* _mUrl;
}
@property(retain, nonatomic) NSString* mUrl;	// G=0xb5b861; S=0xb5b871; 
@property(retain, nonatomic) NSString* mDetail;	// G=0xb5b829; S=0xb5b839; 
@property(retain, nonatomic) NSString* mTitle;	// G=0xb5b7f1; S=0xb5b801; 
+(id)parseData:(id)data;	// 0xb5b4b1
-(void).cxx_destruct;	// 0xb5b899
-(id)description;	// 0xb5b73d
-(BOOL)copy:(id)copy;	// 0xb5b685
-(void)reset;	// 0xb5b63d
-(void)dealloc;	// 0xb5b5fd
-(id)init;	// 0xb5b5b9
@end

