/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITabBarControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableSet;
@protocol IQAudioPickerControllerDelegate;

__attribute__((visibility("hidden")))
@interface IQAudioPickerController : XXUnknownSuperclass <UITabBarControllerDelegate> {
	BOOL _previousNavigationBarHidden;
	BOOL _allowsPickingMultipleItems;
	NSMutableSet* _selectedItems;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableSet* selectedItems;	// G=0x32cad; S=0x32cbd; 
@property(assign, nonatomic) BOOL allowsPickingMultipleItems;	// G=0x32c8d; S=0x32c9d; 
@property(assign, nonatomic) id<UITabBarControllerDelegate, IQAudioPickerControllerDelegate> delegate;
-(void).cxx_destruct;	// 0x32ce5
-(void)viewWillDisappear:(BOOL)view;	// 0x32c1d
-(void)viewWillAppear:(BOOL)view;	// 0x328b9
-(void)viewDidLoad;	// 0x327e9
@end

