/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITabBarControllerDelegate.h"
#import "IQMediaCaptureControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "IQAssetsPickerControllerDelegate.h"
#import "IQAudioPickerControllerDelegate.h"

@class NSString;
@protocol IQMediaPickerControllerDelegate;

__attribute__((visibility("hidden")))
@interface IQMediaPickerController : XXUnknownSuperclass <IQMediaCaptureControllerDelegate, IQAssetsPickerControllerDelegate, IQAudioPickerControllerDelegate, UITabBarControllerDelegate> {
	BOOL _allowsPickingMultipleItems;
	id<IQMediaPickerControllerDelegate> _mediaDelegate;
	int _mediaType;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int mediaType;	// G=0xd3eed; S=0xd3b31; 
@property(assign, nonatomic) BOOL allowsPickingMultipleItems;	// G=0xd3ecd; S=0xd3edd; 
@property(assign, nonatomic) id<IQMediaPickerControllerDelegate> mediaDelegate;	// G=0xd3ead; S=0xd3ebd; 
-(void)audioPickerControllerDidCancel:(id)audioPickerController;	// 0xd3e29
-(void)audioPickerController:(id)controller didPickMediaItems:(id)items;	// 0xd3d61
-(void)assetsPickerControllerDidCancel:(id)assetsPickerController;	// 0xd3cdd
-(void)assetsPickerController:(id)controller didFinishMediaWithInfo:(id)info;	// 0xd3c51
-(void)mediaCaptureControllerDidCancel:(id)mediaCaptureController;	// 0xd3bcd
-(void)mediaCaptureController:(id)controller didFinishMediaWithInfo:(id)info;	// 0xd3b41
-(void)viewWillAppear:(BOOL)view;	// 0xd394d
-(void)viewDidLoad;	// 0xd38c1
-(id)init;	// 0xd3879
@end

