/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IQAudioPickerController, NSArray;

__attribute__((visibility("hidden")))
@interface IQSongsCompilationsViewController : XXUnknownSuperclass {
	NSArray* collections;
	IQAudioPickerController* _audioPickerController;
}
@property(assign, nonatomic) IQAudioPickerController* audioPickerController;	// G=0x3c5ff1; S=0x3c6001; 
-(void).cxx_destruct;	// 0x3c6011
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x3c5ead
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x3c5bed
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x3c5bcd
-(void)cancelAction:(id)action;	// 0x3c5ad1
-(void)doneAction:(id)action;	// 0x3c5859
-(void)viewDidLoad;	// 0x3c5629
-(id)init;	// 0x3c5571
@end

