/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class IQAudioPickerController, NSArray;

__attribute__((visibility("hidden")))
@interface IQSongsArtistListViewController : XXUnknownSuperclass {
	NSArray* collections;
	IQAudioPickerController* _audioPickerController;
}
@property(assign, nonatomic) IQAudioPickerController* audioPickerController;	// G=0x31f779; S=0x31f789; 
-(void).cxx_destruct;	// 0x31f799
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x31f531
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x31f155
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x31f135
-(void)cancelAction:(id)action;	// 0x31f039
-(void)doneAction:(id)action;	// 0x31edc1
-(void)viewDidLoad;	// 0x31eb7d
-(id)init;	// 0x31eac5
@end

