/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface JPExtension : XXUnknownSuperclass {
}
+(id)getDictOfStruct:(void*)aStruct structDefine:(id)define;	// 0x416e8d
+(void)getStructDataWidthDict:(void*)dict dict:(id)dict2 structDefine:(id)define;	// 0x41683d
+(int)sizeOfStructTypes:(id)structTypes;	// 0x416781
+(id)formatOCToJS:(id)js;	// 0x4166ad
+(id)formatJSToOC:(id)oc;	// 0x416665
+(id)formatPointerOCToJS:(void*)js;	// 0x416621
+(void*)formatPointerJSToOC:(id)oc;	// 0x41649d
+(void)main:(id)main;	// 0x416499
@end

