/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface JQButton : XXUnknownSuperclass {
}
+(id)createJQButton;	// 0x14e99
-(void)layoutSubviews;	// 0x15009
-(id)initWithFrame:(CGRect)frame;	// 0x14f3d
@end

