/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJHeartsEmitterDelegate.h"
#import "JQDealPraiseManagerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSTimer, JQDealPraiseManager, NSString, HJHeartsEmitter, JQButton;

__attribute__((visibility("hidden")))
@interface JQDealPraiseViewController : XXUnknownSuperclass <JQDealPraiseManagerDelegate, HJHeartsEmitterDelegate> {
	BOOL _firstIn;
	JQButton* _praiseCountBtn;
	HJHeartsEmitter* _heartsEmitter;
	NSString* _liveId;
	JQDealPraiseManager* _dealPraiseManager;
	int _needsubmitHearts;
	NSTimer* _timerHeart;
	long long _totalCount;
	long long _praiseCount;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSTimer* timerHeart;	// G=0x39bba9; S=0x39bbb9; 
@property(assign, nonatomic) int needsubmitHearts;	// G=0x39bb89; S=0x39bb99; 
@property(assign, nonatomic, getter=isFirstIn) BOOL firstIn;	// G=0x39bb69; S=0x39bb79; 
@property(retain, nonatomic) JQDealPraiseManager* dealPraiseManager;	// G=0x39b565; S=0x39bb41; 
@property(retain, nonatomic) NSString* liveId;	// G=0x39bb09; S=0x39bb19; 
@property(assign, nonatomic) long long praiseCount;	// G=0x39badd; S=0x39baf5; 
@property(assign, nonatomic) long long totalCount;	// G=0x39bac5; S=0x39b6d1; 
@property(retain, nonatomic) HJHeartsEmitter* heartsEmitter;	// G=0x39b661; S=0x39ba9d; 
@property(retain, nonatomic) JQButton* praiseCountBtn;	// G=0x39b5e9; S=0x39ba75; 
-(void).cxx_destruct;	// 0x39bbe1
-(void)reStart;	// 0x39b9a5
-(void)setNewTotalPraiseCount:(long long)count;	// 0x39b9a1
-(void)cleanPraiseCount;	// 0x39b97d
-(void)dealloc;	// 0x39b92d
-(void)cleanData;	// 0x39b879
-(void)birthOne;	// 0x39b42d
-(void)heartsEmitter:(id)emitter heartDidRemoved:(id)heart;	// 0x39b3c9
-(void)dealPraiseManager:(id)manager postPraiseHeart:(id)heart;	// 0x39b33d
-(void)submitHeartHttp;	// 0x39b285
-(void)initTimer;	// 0x39b0f9
-(void)receivePraiseData:(id)data;	// 0x39b0a9
-(void)dealPraiseManager:(id)manager totalCountDidChanged:(long long)totalCount;	// 0x39b091
-(void)viewDidLoad;	// 0x39b065
-(id)init;	// 0x39afd9
@end

