/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "JQLiveBaseController.h"
#import "HJBaseCellDelegate.h"

@class NSString, NSTimer, UIButton, HJSeedIntf;

__attribute__((visibility("hidden")))
@interface JQLiveListController : JQLiveBaseController <HJBaseCellDelegate> {
	UIButton* _leftButton;
	NSTimer* _refreshTimer;
	HJSeedIntf* _refreshIntf;
	HJSeedIntf* _statusIntf;
	HJSeedIntf* _loadmoreIntf;
	UIButton* _bgBtn;
	double _refreshInterval;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIButton* bgBtn;	// G=0x20abf1; S=0x20ac01; 
@property(retain, nonatomic) HJSeedIntf* loadmoreIntf;	// G=0x20abb9; S=0x20abc9; 
@property(retain, nonatomic) HJSeedIntf* statusIntf;	// G=0x20ab81; S=0x20ab91; 
@property(retain, nonatomic) HJSeedIntf* refreshIntf;	// G=0x20ab49; S=0x20ab59; 
@property(assign, nonatomic) double refreshInterval;	// G=0x20ab31; S=0x208c41; 
@property(retain, nonatomic) NSTimer* refreshTimer;	// G=0x20aaf9; S=0x20ab09; 
-(void).cxx_destruct;	// 0x20ac29
-(void)doLoadmore;	// 0x20aae9
-(void)doLoadMoreReplay;	// 0x20a679
-(void)loadReplayList;	// 0x20a489
-(void)doLoadMoreLive;	// 0x209dc9
-(void)handleRefresh:(id)refresh;	// 0x20949d
-(void)doRefresh;	// 0x2093c1
-(void)doAutoRefreshing;	// 0x208c95
-(void)judgeStateAndStartAutoRefreshing;	// 0x208c1d
-(void)stopAutoRefreshing;	// 0x208be9
-(void)startAutoRefreshing;	// 0x208b21
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0x20882d
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x2085e9
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0x208285
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x2081b9
-(void)onClickIconViewOfCell:(id)cell;	// 0x207f89
-(void)setupCells;	// 0x207e55
-(void)pushToPrevueVc;	// 0x207cc5
-(void)pushToProfileVc;	// 0x207c4d
-(void)setupRightBarItem;	// 0x2079f9
-(void)setupLeftBarItem;	// 0x2076f1
-(void)viewDidLayoutSubviews;	// 0x20768d
-(void)dealloc;	// 0x207611
-(void)iconChanged:(id)changed;	// 0x20748d
-(void)viewWillAppear:(BOOL)view;	// 0x207461
-(void)viewDidLoad;	// 0x2072f9
-(void)setUpTitleView;	// 0x207029
-(void)removedTipForKeyWindow;	// 0x206ff1
-(void)setUpFirstInView;	// 0x206951
-(void)pushToPrevueView;	// 0x2067c1
@end

