/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "DSTableViewController.h"
#import "UIScrollViewDelegate.h"
#import "living-Structs.h"

@class NSString, HJLoadingView2, HJEmptyView, NSTimer, UIImageView, UIView, NSMutableArray, HJErrorView;

__attribute__((visibility("hidden")))
@interface JQLiveBaseController : DSTableViewController <UIScrollViewDelegate> {
	BOOL _noMoreData;
	BOOL _hideHeaderAndFooterView;
	BOOL _listStateObserver;
	NSMutableArray* _liveListArr;
	unsigned _listState;
	NSMutableArray* _replayArrM;
	UIView* _emtpyView;
	UIView* _errorView;
	UIView* _loadingView;
	HJLoadingView2* _theLoadingView;
	HJEmptyView* _theEmptyView;
	HJErrorView* _theErrorView;
	UIImageView* _tipsView;
	NSTimer* _refreshTimer;
	double _refreshInterval;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=isListStateObserver) BOOL listStateObserver;	// G=0x23e19d; S=0x23e1ad; 
@property(retain, nonatomic) NSTimer* refreshTimer;	// G=0x23e165; S=0x23e175; 
@property(retain, nonatomic) UIImageView* tipsView;	// G=0x23cdd1; S=0x23e13d; 
@property(retain, nonatomic) HJErrorView* theErrorView;	// G=0x23e105; S=0x23e115; 
@property(retain, nonatomic) HJEmptyView* theEmptyView;	// G=0x23e0cd; S=0x23e0dd; 
@property(retain, nonatomic) HJLoadingView2* theLoadingView;	// G=0x23e095; S=0x23e0a5; 
@property(retain, nonatomic) UIView* loadingView;	// G=0x23d0ad; S=0x23e06d; 
@property(retain, nonatomic) UIView* errorView;	// G=0x23d28d; S=0x23e045; 
@property(retain, nonatomic) UIView* emtpyView;	// G=0x23d499; S=0x23e01d; 
@property(assign, nonatomic) double refreshInterval;	// G=0x23dff1; S=0x23e009; 
@property(retain, nonatomic) NSMutableArray* replayArrM;	// G=0x23df19; S=0x23dfc9; 
@property(assign, nonatomic) BOOL hideHeaderAndFooterView;	// G=0x23dfa9; S=0x23dfb9; 
@property(assign, nonatomic) BOOL noMoreData;	// G=0x23df89; S=0x23df99; 
@property(assign, nonatomic) unsigned listState;	// G=0x23df69; S=0x23df79; 
@property(retain, nonatomic) NSMutableArray* liveListArr;	// G=0x23d729; S=0x23d77d; 
-(void).cxx_destruct;	// 0x23e1bd
-(void)moreListAnimation:(unsigned)animation;	// 0x23d839
-(void)onClickSeedingButton;	// 0x23d6ed
-(void)checkError:(id)error;	// 0x23d009
-(void)checkEmpty;	// 0x23cd51
-(void)onTapEmptyView;	// 0x23cd41
-(void)onTapErrorView;	// 0x23cd31
-(void)showTable;	// 0x23cc4d
-(void)showError;	// 0x23cb69
-(void)showEmpty;	// 0x23ca85
-(void)showLoading;	// 0x23c9a1
-(int)numberOfSectionsInTableView:(id)tableView;	// 0x23c99d
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0x23c961
-(void)setupSubviews;	// 0x23c801
-(void)setupbackgroundImage;	// 0x23c5c5
-(void)setupProperty;	// 0x23c4e5
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0x23c3a9
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;	// 0x23bf01
-(void)addObserver;	// 0x23bea1
-(void)dealloc;	// 0x23be35
-(void)applicationWillEnterForeground;	// 0x23be05
-(void)applicationDidEnterBackground;	// 0x23bdf5
-(void)viewDidAppear:(BOOL)view;	// 0x23bda1
-(void)viewWillDisappear:(BOOL)view;	// 0x23bbb9
-(void)liveWindowHide;	// 0x23bb89
-(void)liveWindowShow;	// 0x23bb79
-(void)viewWillAppear:(BOOL)view;	// 0x23b95d
-(void)setupRefresh;	// 0x23b8a5
-(void)viewDidLoad;	// 0x23b7d9
@end

