/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface JumpToBizProfileReq : BaseReq {
	NSString* username;
	NSString* extMsg;
	int _profileType;
}
@property(assign, nonatomic) int profileType;	// G=0xcc7161; S=0xcc7171; 
@property(retain, nonatomic) NSString* extMsg;	// G=0xcc712d; S=0xcc713d; 
@property(retain, nonatomic) NSString* username;	// G=0xcc70f9; S=0xcc7109; 
-(void)dealloc;	// 0xcc70a1
@end

