/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UIWindow, UIView;
@protocol LCActionSheetDelegate;

__attribute__((visibility("hidden")))
@interface LCActionSheet : XXUnknownSuperclass {
	NSArray* _buttonTitles;
	UIView* _darkView;
	UIView* _bottomView;
	id<LCActionSheetDelegate> _delegate;
	UIWindow* _backWindow;
}
@property(retain, nonatomic) UIWindow* backWindow;	// G=0x3d3769; S=0x3d3f45; 
+(id)sheetWithTitle:(id)title buttonTitles:(id)titles redButtonIndex:(int)index delegate:(id)delegate;	// 0x3d2a61
-(void).cxx_destruct;	// 0x3d3f6d
-(id)buttonTitleAtIndex:(unsigned)index;	// 0x3d3ef5
-(void)show;	// 0x3d3d71
-(void)didClickCancelBtn;	// 0x3d3b29
-(void)dismiss:(id)dismiss;	// 0x3d3941
-(void)didClickBtn:(id)btn;	// 0x3d38b9
-(id)initWithTitle:(id)title buttonTitles:(id)titles redButtonIndex:(int)index delegate:(id)delegate;	// 0x3d2add
@end

