/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSData, NSString;
@protocol LDSimplePingDelegate;

__attribute__((visibility("hidden")))
@interface LDSimplePing : XXUnknownSuperclass {
	CFHostRef _host;
	CFSocketRef _socket;
	unsigned short _identifier;
	unsigned short _nextSequenceNumber;
	NSString* _hostName;
	NSData* _hostAddress;
	id<LDSimplePingDelegate> _delegate;
}
@property(assign, nonatomic) unsigned short nextSequenceNumber;	// G=0x2f0575; S=0x2f0585; 
@property(readonly, assign, nonatomic) unsigned short identifier;	// G=0x2f0565; 
@property(copy, nonatomic) NSData* hostAddress;	// G=0x2f050d; S=0x2f0521; 
@property(readonly, copy, nonatomic) NSString* hostName;	// G=0x2f04f9; 
@property(assign, nonatomic) __weak id<LDSimplePingDelegate> delegate;	// G=0x2f0531; S=0x2f0551; 
+(const ICMPHeader*)icmpInPacket:(id)packet;	// 0x2ef7e9
+(const IPHeader*)ipHeaderInPacket:(id)packet;	// 0x2ef745
+(unsigned)icmpHeaderOffsetInPacket:(id)packet;	// 0x2ef679
+(id)simplePingWithHostAddress:(id)hostAddress;	// 0x2eef2d
+(id)simplePingWithHostName:(id)hostName;	// 0x2eeed9
-(void).cxx_destruct;	// 0x2f0595
-(void)stop;	// 0x2f0491
-(void)stopDataTransfer;	// 0x2f0465
-(void)stopHostResolution;	// 0x2f0411
-(void)start;	// 0x2f019d
-(void)hostResolutionDone;	// 0x2effd5
-(void)startWithHostAddress;	// 0x2efb9d
-(void)readData;	// 0x2ef931
-(BOOL)isValidPingResponsePacket:(id)packet;	// 0x2ef83d
-(void)sendPingWithData:(id)data;	// 0x2ef19d
-(void)didFailWithHostStreamError:(timeval)hostStreamError;	// 0x2ef091
-(void)didFailWithError:(id)error;	// 0x2eef85
-(void)noop;	// 0x2eef81
-(void)dealloc;	// 0x2eee31
-(id)initWithHostName:(id)hostName address:(id)address;	// 0x2eed41
@end

