/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface LiveGuideView : XXUnknownSuperclass {
}
+(BOOL)shouldShowGuideView;	// 0x17fe19
+(void)initialize;	// 0x17f5d1
-(void)touchesBegan:(id)began withEvent:(id)event;	// 0x17fcc1
-(void)setup;	// 0x17f6c9
-(id)initWithFrame:(CGRect)frame;	// 0x17f671
-(id)init;	// 0x17f62d
@end

