/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol MASConstraintDelegate;

@interface MASConstraint : XXUnknownSuperclass {
	BOOL _updateExisting;
	id<MASConstraintDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<MASConstraintDelegate> delegate;	// G=0x43a059; S=0x43a079; 
@property(assign, nonatomic) BOOL updateExisting;	// G=0x43a039; S=0x43a049; 
-(void).cxx_destruct;	// 0x43a08d
-(void)uninstall;	// 0x439fa1
-(void)install;	// 0x439f09
-(void)deactivate;	// 0x439e71
-(void)activate;	// 0x439dd9
-(void)setOffset:(float)offset;	// 0x439d41
-(void)setCenterOffset:(CGPoint)offset;	// 0x439ca9
-(void)setSizeOffset:(CGSize)offset;	// 0x439c11
-(void)setInsets:(UIEdgeInsets)insets;	// 0x439b79
-(id)key;	// 0x439ae1
-(id)equalToWithRelation;	// 0x439a49
-(id)priority;	// 0x4399b1
-(id)dividedBy;	// 0x439919
-(id)multipliedBy;	// 0x439881
-(id)centerYWithinMargins;	// 0x43986d
-(id)centerXWithinMargins;	// 0x439859
-(id)trailingMargin;	// 0x439845
-(id)leadingMargin;	// 0x439831
-(id)bottomMargin;	// 0x43981d
-(id)topMargin;	// 0x439809
-(id)rightMargin;	// 0x4397f5
-(id)leftMargin;	// 0x4397e1
-(id)baseline;	// 0x4397cd
-(id)centerY;	// 0x4397b9
-(id)centerX;	// 0x4397a5
-(id)height;	// 0x439791
-(id)width;	// 0x43977d
-(id)trailing;	// 0x439769
-(id)leading;	// 0x439755
-(id)bottom;	// 0x439741
-(id)right;	// 0x43972d
-(id)top;	// 0x439719
-(id)left;	// 0x439705
-(id)addConstraintWithLayoutAttribute:(int)layoutAttribute;	// 0x43966d
-(id)and;	// 0x439669
-(id)with;	// 0x439665
-(void)setLayoutConstantWithValue:(id)value;	// 0x4394f1
-(id)mas_offset;	// 0x4394ed
-(id)valueOffset;	// 0x439461
-(id)offset;	// 0x4393d5
-(id)centerOffset;	// 0x439345
-(id)sizeOffset;	// 0x4392b5
-(id)insets;	// 0x439211
-(id)priorityHigh;	// 0x439161
-(id)priorityMedium;	// 0x4390b5
-(id)priorityLow;	// 0x439009
-(id)mas_lessThanOrEqualTo;	// 0x438f4d
-(id)lessThanOrEqualTo;	// 0x438e91
-(id)mas_greaterThanOrEqualTo;	// 0x438dd5
-(id)greaterThanOrEqualTo;	// 0x438d19
-(id)mas_equalTo;	// 0x438c5d
-(id)equalTo;	// 0x438ba1
-(id)init;	// 0x438b75
@end

