/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

@interface MASViewAttribute : XXUnknownSuperclass {
	UIView* _view;
	id _item;
	int _layoutAttribute;
}
@property(readonly, assign, nonatomic) int layoutAttribute;	// G=0x43b641; 
@property(readonly, assign, nonatomic) __weak id item;	// G=0x43b621; 
@property(readonly, assign, nonatomic) __weak UIView* view;	// G=0x43b601; 
-(void).cxx_destruct;	// 0x43b651
-(unsigned)hash;	// 0x43b57d
-(BOOL)isEqual:(id)equal;	// 0x43b4a1
-(BOOL)isSizeAttribute;	// 0x43b469
-(id)initWithView:(id)view item:(id)item layoutAttribute:(int)attribute;	// 0x43b3c1
-(id)initWithView:(id)view layoutAttribute:(int)attribute;	// 0x43b3a1
@end

