/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MJRefreshBackStateFooter.h"

@class NSMutableDictionary, UIImageView;

@interface MJRefreshBackGifFooter : MJRefreshBackStateFooter {
	UIImageView* _gifView;
	NSMutableDictionary* _stateImages;
	NSMutableDictionary* _stateDurations;
}
@property(retain, nonatomic) NSMutableDictionary* stateDurations;	// G=0x423d71; S=0x424685; 
@property(retain, nonatomic) NSMutableDictionary* stateImages;	// G=0x423d11; S=0x42465d; 
@property(readonly, assign, nonatomic) __weak UIImageView* gifView;	// G=0x423ca1; 
-(void).cxx_destruct;	// 0x4246ad
-(void)setState:(int)state;	// 0x424369
-(void)placeSubviews;	// 0x424199
-(void)setPullingPercent:(float)percent;	// 0x424001
-(void)setImages:(id)images forState:(int)state;	// 0x423f91
-(void)setImages:(id)images duration:(double)duration forState:(int)state;	// 0x423dd1
@end

