/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary, NSString;

@interface MobClickCheckUpdate : XXUnknownSuperclass {
	NSString* _appHomeUrl;
	NSString* _updateTitle;
	NSString* _updateCancelButtonTitle;
	NSString* _updateOtherButtonTitles;
	id _updateDelegate;
	SEL _appUpdateSelector;
	NSMutableDictionary* _updateInfo;
	BOOL _checkUpdateJobFlag;
}
@property(retain, nonatomic) NSMutableDictionary* updateInfo;	// G=0xb1dc69; S=0xb1dc79; 
@property(assign, nonatomic) id updateDelegate;	// G=0xb1dc49; S=0xb1dc59; 
@property(assign, nonatomic) SEL appUpdateSelector;	// G=0xb1dc29; S=0xb1dc39; 
@property(copy, nonatomic) NSString* updateOtherButtonTitles;	// G=0xb1dbe1; S=0xb1dbf9; 
@property(copy, nonatomic) NSString* updateCancelButtonTitle;	// G=0xb1db99; S=0xb1dbb1; 
@property(copy, nonatomic) NSString* updateTitle;	// G=0xb1db51; S=0xb1db69; 
@property(copy, nonatomic) NSString* appHomeUrl;	// G=0xb1db09; S=0xb1db21; 
+(id)sharedInstance;	// 0xb1ca21
-(id)description;	// 0xb1d9b1
-(void)dealloc;	// 0xb1d8c5
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0xb1d851
-(void)checkUpdateWithDelegate:(id)delegate selector:(SEL)selector;	// 0xb1d7c5
-(void)checkUpdate;	// 0xb1d765
-(void)checkUpdate:(id)update cancelButtonTitle:(id)title otherButtonTitles:(id)titles;	// 0xb1d651
-(void)checkAppUpdateResult;	// 0xb1d571
-(id)getData:(id)data error:(id*)error;	// 0xb1d369
-(void)excuteUpdate:(id)update;	// 0xb1d1ad
-(BOOL)checkAppUpdate:(id)update;	// 0xb1d15d
-(void)appUpdateWithAlert:(id)alert;	// 0xb1cebd
-(id)setAppUpdateData;	// 0xb1cd21
-(void)toggleCheckUpdateJobFlag;	// 0xb1cd05
-(void)gotAppkey;	// 0xb1ccc5
-(id)init;	// 0xb1cc45
@end

