/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString, NSMutableDictionary, NSOperationQueue, NSMutableArray;

@interface MobClickInternal : XXUnknownSuperclass {
	NSOperationQueue* _sendLogQueue;
	NSOperationQueue* _otherQueue;
	NSMutableArray* _terminates;
	NSMutableArray* _events;
	NSMutableArray* _errors;
	NSMutableArray* _ekv;
	NSMutableArray* _tmpContainer;
	NSString* _json;
	NSDictionary* _error_support_info;
	NSString* _sessionID;
	NSString* _wrapperType;
	NSString* _wrapperVersion;
	NSMutableArray* _pageItems;
	NSMutableDictionary* _pageItemsHash;
	NSMutableDictionary* _ekvBeginTimes;
	NSMutableDictionary* _eventBeginTimes;
}
@property(copy, nonatomic) NSString* json;	// G=0xb18fa9; S=0xb18fc1; 
@property(copy, nonatomic) NSString* wrapperVersion;	// G=0xb18f61; S=0xb18f79; 
@property(copy, nonatomic) NSString* wrapperType;	// G=0xb18f19; S=0xb18f31; 
@property(copy, nonatomic) NSString* sessionID;	// G=0xb18ed1; S=0xb18ee9; 
@property(retain) NSDictionary* error_support_info;	// G=0xb18e89; S=0xb18ea1; 
@property(retain) NSMutableArray* tmpContainer;	// G=0xb18e41; S=0xb18e59; 
@property(retain) NSMutableArray* ekv;	// G=0xb18df9; S=0xb18e11; 
@property(retain) NSMutableArray* errors;	// G=0xb18db1; S=0xb18dc9; 
@property(retain) NSMutableArray* events;	// G=0xb18d69; S=0xb18d81; 
@property(retain) NSMutableArray* terminates;	// G=0xb18d21; S=0xb18d39; 
@property(retain, nonatomic) NSOperationQueue* otherQueue;	// G=0xb18ced; S=0xb18cfd; 
@property(retain, nonatomic) NSOperationQueue* sendLogQueue;	// G=0xb18cb9; S=0xb18cc9; 
+(void)setErrorSupportInfo:(id)info;	// 0xb1862d
+(void)installUncaughtExceptionHandler;	// 0xb18051
+(id)sharedInstance;	// 0xb15c25
-(void)buildDummySession;	// 0xb18bb9
-(void)removeInstanceMsgs;	// 0xb18b59
-(void)removeSessions;	// 0xb18b31
-(id)header;	// 0xb18669
-(void)error:(id)error;	// 0xb18255
-(void)saveCrashInfo:(id)info;	// 0xb1809d
-(void)ekvEnd:(id)end;	// 0xb17ea5
-(void)eventEnd:(id)end;	// 0xb17d21
-(void)ekvBegin:(id)begin;	// 0xb17bdd
-(void)eventBegin:(id)begin;	// 0xb17a99
-(void)unarchiveErrors:(id)errors;	// 0xb17895
-(void)unarchiveEvents:(id)events;	// 0xb176c5
-(void)unarchiveSessions:(id)sessions;	// 0xb17599
-(void)unarchiveObjects:(id)objects;	// 0xb17555
-(void)archiveObjects:(id)objects;	// 0xb173ad
-(id)archiveObjectsWithHeader:(BOOL)header;	// 0xb172f5
-(void)archiveCacheToFile;	// 0xb1722d
-(id)loadCacheFile;	// 0xb171a5
-(void)loadCache;	// 0xb1712d
-(void)loadCacheFromTempContainer;	// 0xb16f6d
-(void)saveAndCleanCache;	// 0xb16f25
-(void)removeCacheData;	// 0xb16e89
-(void)stopSession:(double)session;	// 0xb16c21
-(void)handleInactivate:(double)inactivate;	// 0xb16bcd
-(void)workEvent:(id)event;	// 0xb1648d
-(void)setEventSessionID:(id)anId;	// 0xb16415
-(void)addEvent:(id)event inContainer:(id)container;	// 0xb1638d
-(id)arrayWithEventType:(int)eventType;	// 0xb162b5
-(void)beginPerformJob;	// 0xb160bd
-(void)generateEnvelopeFile;	// 0xb16071
-(BOOL)hasJob;	// 0xb15fe9
-(void)validateEnvelopeFiles:(id)files;	// 0xb15d51
-(void)dealloc;	// 0xb15a75
-(id)init;	// 0xb15889
@end

