/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface OpenWebviewReq : BaseReq {
	NSString* _url;
}
@property(retain, nonatomic) NSString* url;	// G=0xcc706d; S=0xcc707d; 
-(void)dealloc;	// 0xcc7021
@end

