/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OpenApi : XXUnknownSuperclass {
}
+(int)tencentAuhorizeState;	// 0xb39499
+(void)setTencentAuthorizeState:(int)state;	// 0xb39489
+(void)clearParam;	// 0xb39475
+(id)getApiVersion;	// 0xb39469
+(id)getSupportingMaxApiVersion;	// 0xb3945d
+(id)getQZoneInstallUrl;	// 0xb39451
+(BOOL)openQZone;	// 0xb39369
+(BOOL)shareWithQZoneWithData:(id)data;	// 0xb39349
+(BOOL)sendCommandToQZone:(id)qzone params:(id)params;	// 0xb39329
+(BOOL)authorizeWithPermission:(id)permission delegate:(id)delegate firstCall:(int)call;	// 0xb38fc1
+(BOOL)isQZoneInstalled;	// 0xb38f0d
+(int)qqVersion;	// 0xb38d8d
+(int)qzoneVersion;	// 0xb38c41
+(BOOL)canHandleOpenURL:(id)url;	// 0xb38b85
+(BOOL)handleOpenURL:(id)url;	// 0xb38ab5
+(BOOL)canParseURL:(id)url;	// 0xb38a7d
+(void)unRegisterAppSessionDelegate:(id)delegate;	// 0xb38a65
+(void)unRegisterApp:(id)app withDelegate:(id)delegate andOldApi:(id)api;	// 0xb38a39
+(BOOL)registerApp:(id)app withDelegate:(id)delegate andOldApi:(id)api;	// 0xb38a0d
+(BOOL)registerApp:(id)app;	// 0xb3899d
+(id)dictionaryByParseUrlFromSeparator:(id)separator separator:(id)separator2;	// 0xb38791
+(BOOL)isQZoneSupportGeneralPastboard;	// 0xb38731
+(BOOL)isSupportGeneralPastboard;	// 0xb386d1
+(BOOL)processMessage:(id)message;	// 0xb37af9
+(BOOL)openQZoneWithCommandStr:(id)commandStr andPasteBoardName:(id)name data:(id)data;	// 0xb37961
+(BOOL)openQZoneWithCommand:(int)command andPasteBoardName:(id)name data:(id)data;	// 0xb37915
+(BOOL)openQQWithCommand:(int)command andPasteBoardName:(id)name data:(id)data;	// 0xb37785
+(id)getDictionaryFromGeneralPasteBoard:(id)generalPasteBoard;	// 0xb376d9
+(id)getDictionaryFromPasteBoard:(id)pasteBoard;	// 0xb3764d
+(id)saveDictionaryByGeneralPastboard:(id)pastboard;	// 0xb375a1
+(id)getGeneralPastboardNameKey;	// 0xb37555
+(id)saveDictionary:(id)dictionary toPasteBoard:(id)pasteBoard;	// 0xb374a1
@end

