/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface OpenTempSessionReq : BaseReq {
	NSString* username;
	NSString* _sessionFrom;
}
@property(retain, nonatomic) NSString* sessionFrom;	// G=0xcc6fed; S=0xcc6ffd; 
@property(retain, nonatomic) NSString* username;	// G=0xcc6fb9; S=0xcc6fc9; 
-(void)dealloc;	// 0xcc6f61
@end

