/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseResp.h"

@class NSString;

@interface PayResp : BaseResp {
	NSString* returnKey;
}
@property(retain, nonatomic) NSString* returnKey;	// G=0xcc6909; S=0xcc6919; 
-(void)dealloc;	// 0xcc68c5
-(id)init;	// 0xcc6885
@end

