/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, EAGLContext, CAEAGLLayer;

@interface PlayerGLView : XXUnknownSuperclass {
	int m_backingWidth;
	int m_backingHeight;
	int m_texturWidth;
	int m_texturHeight;
	EAGLContext* m_context;
	unsigned m_viewRenderbuffer;
	unsigned m_viewFramebuffer;
	unsigned m_videoFrameTexture[3];
	int m_viewScale;
	const float* squareVertices;
	unsigned m_vert_scale;
	int m_uniforms[3];
	unsigned m_program;
	CAEAGLLayer* m_eaglLayer;
	int _iExit;
	bool _bExchangeWH;
	NSString* _savePath;
	BOOL m_bEnableVideo;
	BOOL _m_bMirror;
	int _m_DisplayMode;
}
@property(assign, nonatomic) int m_DisplayMode;	// G=0x4ad2b9; S=0x4ad2c9; 
@property(assign, nonatomic) BOOL m_bMirror;	// G=0x4ad299; S=0x4ad2a9; 
@property(assign, nonatomic) BOOL m_bEnableVideo;	// G=0x4ad279; S=0x4ad289; 
@property(retain, nonatomic) EAGLContext* m_context;	// G=0x4ad259; S=0x4ad269; 
+(Class)layerClass;	// 0x4abe1d
-(void)rotate:(float)rotate withX:(float)x withY:(float)y withZ:(float)z;	// 0x4ad215
-(void)setDisplayScale:(int)scale withWidth:(int)width withHeight:(int)height;	// 0x4ad101
-(void)setVideoSize:(unsigned)size height:(unsigned)height;	// 0x4acf79
-(BOOL)validateProgram:(unsigned)program;	// 0x4acf25
-(BOOL)linkProgram:(unsigned)program;	// 0x4acefd
-(BOOL)compileShader:(unsigned*)shader type:(unsigned)type file:(id)file;	// 0x4ace95
-(BOOL)loadShaders;	// 0x4acc19
-(void)tearDownGL;	// 0x4acb9d
-(void)dealloc;	// 0x4aca21
-(void)destroryTexture;	// 0x4aca0d
-(void)createTexture;	// 0x4ac8f5
-(void)destroyFramebuffer;	// 0x4ac8b1
-(BOOL)createFramebuffers;	// 0x4ac7e1
-(void)clearFrame;	// 0x4ac751
-(void)glDraw;	// 0x4ac74d
-(void)drawView;	// 0x4ac21d
-(id)initWithFrame:(CGRect)frame orientationType:(int)type;	// 0x4abe79
-(id)initWithFrame:(CGRect)frame;	// 0x4abe39
@end

