/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray;

@interface PLCrashReportThreadInfo : XXUnknownSuperclass {
	int _threadNumber;
	NSArray* _stackFrames;
	BOOL _crashed;
	NSArray* _registers;
}
@property(readonly, assign, nonatomic) NSArray* registers;	// G=0xcb31f9; 
@property(readonly, assign, nonatomic) BOOL crashed;	// G=0xcb31e9; 
@property(readonly, assign, nonatomic) NSArray* stackFrames;	// G=0xcb31d9; 
@property(readonly, assign, nonatomic) int threadNumber;	// G=0xcb31c9; 
-(void)dealloc;	// 0xcb3165
-(id)initWithThreadNumber:(int)threadNumber stackFrames:(id)frames crashed:(BOOL)crashed registers:(id)registers;	// 0xcb30c1
@end

