/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class PLCrashReportSymbolInfo;

@interface PLCrashReportStackFrameInfo : XXUnknownSuperclass {
	unsigned long long _instructionPointer;
	PLCrashReportSymbolInfo* _symbolInfo;
}
@property(readonly, assign, nonatomic) PLCrashReportSymbolInfo* symbolInfo;	// G=0xcb749d; 
@property(readonly, assign, nonatomic) unsigned long long instructionPointer;	// G=0xcb7485; 
-(void)dealloc;	// 0xcb7439
-(id)initWithInstructionPointer:(unsigned long long)instructionPointer symbolInfo:(id)info;	// 0xcb73c9
@end

