/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;

@interface QHACustomEvent : XXUnknownSuperclass {
	unsigned _type;
	NSString* _eventId;
	unsigned _samplingType;
	NSString* _statusValue;
	NSString* _label;
	NSDictionary* _customAttributes;
	int _dataLevel;
	unsigned long long _timeValue;
	unsigned long long _timestamp;
}
@property(readonly, assign, nonatomic) unsigned long long timestamp;	// G=0x489aed; 
@property(assign, nonatomic) int dataLevel;	// G=0x489add; S=0x489491; 
@property(retain, nonatomic) NSDictionary* customAttributes;	// G=0x489aa5; S=0x489ab5; 
@property(retain, nonatomic) NSString* label;	// G=0x489a6d; S=0x489a7d; 
@property(retain, nonatomic) NSString* statusValue;	// G=0x489a35; S=0x489a45; 
@property(assign, nonatomic) unsigned long long timeValue;	// G=0x489a09; S=0x489a21; 
@property(assign, nonatomic) unsigned samplingType;	// G=0x4899e9; S=0x4899f9; 
@property(retain, nonatomic) NSString* eventId;	// G=0x4899b1; S=0x4899c1; 
@property(assign, nonatomic) unsigned type;	// G=0x489991; S=0x4899a1; 
+(void)onEvent:(id)event label:(id)label attributes:(id)attributes timeValue:(long long)value type:(unsigned)type;	// 0x489711
+(void)onPushEvent:(id)event type:(unsigned)type label:(id)label;	// 0x489605
+(void)onEvent:(id)event;	// 0x4895a5
+(void)onTimeEvent:(id)event;	// 0x489565
+(id)timeEvent:(id)event;	// 0x489515
+(id)eventWithId:(id)anId;	// 0x4894c5
-(void).cxx_destruct;	// 0x489b05
-(id)toDictionary;	// 0x489809
-(id)initWithId:(id)anId;	// 0x4893d1
@end

