/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface QHAReachabilityManager : XXUnknownSuperclass {
	int _networkReachabilityStatus;
	id _networkReachability;
	unsigned _networkReachabilityAssociation;
	id _networkReachabilityStatusBlock;
}
@property(copy, nonatomic) id networkReachabilityStatusBlock;	// G=0x4892b5; S=0x4892c9; 
@property(assign, nonatomic) unsigned networkReachabilityAssociation;	// G=0x489295; S=0x4892a5; 
@property(retain, nonatomic) id networkReachability;	// G=0x489271; S=0x489281; 
@property(readonly, assign, nonatomic, getter=isReachableViaWiFi) BOOL reachableViaWiFi;	// G=0x488c05; 
@property(readonly, assign, nonatomic, getter=isReachableViaWWAN) BOOL reachableViaWWAN;	// G=0x488be9; 
@property(readonly, assign, nonatomic, getter=isReachable) BOOL reachable;	// G=0x488ba9; 
@property(assign, nonatomic) int networkReachabilityStatus;	// G=0x489251; S=0x489261; 
+(id)keyPathsForValuesAffectingValueForKey:(id)key;	// 0x489185
+(id)managerForAddress:(const void*)address;	// 0x488a85
+(id)managerForDomain:(id)domain;	// 0x4889fd
+(id)sharedManager;	// 0x488915
-(void).cxx_destruct;	// 0x4892d9
-(void)setReachabilityStatusChangeBlock:(id)block;	// 0x489175
-(id)localizedNetworkReachabilityStatusString;	// 0x489159
-(void)stopMonitoring;	// 0x4890f9
-(void)startMonitoring;	// 0x488c25
-(void)dealloc;	// 0x488b69
-(id)init;	// 0x488b5d
-(id)initWithReachability:(SCNetworkReachabilityRef)reachability;	// 0x488ae5
@end

