/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface QHIVMediaSessionConfig : XXUnknownSuperclass {
	BOOL _isRecord;
	NSString* _sn;
	NSString* _liveid;
	NSString* _sign;
	NSString* _relayId;
	NSString* _relayServerStr;
	NSString* _streamKey;
	int _srcType;
}
@property(assign, nonatomic) int srcType;	// G=0x807c4d; S=0x807c5d; 
@property(assign, nonatomic) BOOL isRecord;	// G=0x807c2d; S=0x807c3d; 
@property(copy, nonatomic) NSString* streamKey;	// G=0x807c09; S=0x807c1d; 
@property(copy, nonatomic) NSString* relayServerStr;	// G=0x807be5; S=0x807bf9; 
@property(copy, nonatomic) NSString* relayId;	// G=0x807bc1; S=0x807bd5; 
@property(copy, nonatomic) NSString* sign;	// G=0x807b9d; S=0x807bb1; 
@property(copy, nonatomic) NSString* liveid;	// G=0x807b79; S=0x807b8d; 
@property(copy, nonatomic) NSString* sn;	// G=0x807b55; S=0x807b69; 
-(void).cxx_destruct;	// 0x807c6d
-(id)description;	// 0x807931
@end

