/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSData;

@interface QHIVMediaBuffer : XXUnknownSuperclass {
	BOOL _isKey;
	int _serialNum;
	int _mediaType;
	NSData* _mediaData;
	long long _timestamp;
}
@property(assign, nonatomic) long long timestamp;	// G=0x8078f1; S=0x807909; 
@property(assign, nonatomic) BOOL isKey;	// G=0x8078d1; S=0x8078e1; 
@property(retain, nonatomic) NSData* mediaData;	// G=0x807899; S=0x8078a9; 
@property(assign, nonatomic) int mediaType;	// G=0x807879; S=0x807889; 
@property(assign, nonatomic) int serialNum;	// G=0x807859; S=0x807869; 
-(void).cxx_destruct;	// 0x80791d
@end

