/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "QQApiImageObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface QQApiGroupTribeImageObject : QQApiImageObject {
	NSString* _bid;
	NSString* _bname;
}
@property(retain, nonatomic) NSString* bname;	// G=0xb493c5; S=0xb493d5; 
@property(retain, nonatomic) NSString* bid;	// G=0xb49391; S=0xb493a1; 
@end

