/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface QQApiDatastore : XXUnknownSuperclass {
	NSString* _scheme;
	NSString* _appId;
	NSString* _openId;
	NSString* _appName;
	NSString* _uin;
	NSString* _webviewToken;
}
@property(retain, nonatomic) NSString* webviewToken;	// G=0xb45e15; S=0xb45e25; 
@property(retain, nonatomic) NSString* appName;	// G=0xb45dad; S=0xb45dbd; 
@property(retain, nonatomic) NSString* appId;	// G=0xb45d45; S=0xb45d55; 
@property(retain, nonatomic) NSString* uin;	// G=0xb45de1; S=0xb45df1; 
@property(retain, nonatomic) NSString* openId;	// G=0xb45d79; S=0xb45d89; 
@property(retain, nonatomic) NSString* scheme;	// G=0xb45d11; S=0xb45d21; 
+(id)instance;	// 0xb45749
-(BOOL)isQQSupportApiGeneralPastboard;	// 0xb45cc5
-(void)clearApiLargeData;	// 0xb45c71
-(id)getApiLargeDataByGeneralPastboard;	// 0xb45c21
-(id)getApiLargeData;	// 0xb45bd1
-(int)setApiLargeData:(id)data;	// 0xb45b35
-(void)clearApiMessage;	// 0xb45ae1
-(id)getApiMessage;	// 0xb45a8d
-(int)setApiMessage:(id)message;	// 0xb45a1d
-(id)getAdItemArray;	// 0xb459c5
-(int)setAdItemArray:(id)array;	// 0xb458ad
-(int)registerWithMetadata:(id)metadata;	// 0xb45791
@end

