/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "QQApiObject.h"

@class NSURL;

__attribute__((visibility("hidden")))
@interface QQApiWebImageObject : QQApiObject {
	NSURL* _previewImageURL;
}
@property(retain, nonatomic) NSURL* previewImageURL;	// G=0xb4935d; S=0xb4936d; 
+(id)objectWithPreviewImageURL:(id)previewImageURL title:(id)title description:(id)description;	// 0xb49315
-(id)initWithPreviewImageURL:(id)previewImageURL title:(id)title description:(id)description;	// 0xb49295
@end

