/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface QQDataArray : XXUnknownSuperclass <NSCoding> {
	NSMutableArray* _dataArray;
}
+(id)arrayWithObjectArray:(id)objectArray;	// 0xb4bb3d
-(id)initWithCoder:(id)coder;	// 0xb4c025
-(void)encodeWithCoder:(id)coder;	// 0xb4bff5
-(void)removeAllObjects;	// 0xb4bfd5
-(BOOL)removeObjectAtIndex:(int)index;	// 0xb4bf89
-(BOOL)replaceObjectAtIndex:(int)index withObject:(id)object;	// 0xb4bf09
-(void)addObject:(id)object;	// 0xb4be99
-(int)count;	// 0xb4be79
-(id)objectArray;	// 0xb4bd6d
-(void)dealloc;	// 0xb4bd1d
-(id)init;	// 0xb4bcad
-(id)initWithObjectArray:(id)objectArray;	// 0xb4bb85
@end

