/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface QQPasteboardMgr : XXUnknownSuperclass {
	NSMutableArray* _boards;
}
+(id)instance;	// 0xb4b785
-(id)getArrayPasteboardByName:(id)name;	// 0xb4b9e5
-(id)getObjectPasteboardByName:(id)name;	// 0xb4b88d
-(void)dealloc;	// 0xb4b83d
-(id)init;	// 0xb4b7cd
@end

