/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSObject;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface Reachability : XXUnknownSuperclass {
	BOOL reachableOnWWAN;
	SCNetworkReachabilityRef reachabilityRef;
	NSObject<OS_dispatch_queue>* reachabilitySerialQueue;
	id reachableBlock;
	id unreachableBlock;
	id reachabilityObject;
}
@property(retain, nonatomic) id reachabilityObject;	// G=0x26789; S=0x26799; 
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* reachabilitySerialQueue;	// G=0x266e9; S=0x266f9; 
@property(assign, nonatomic) SCNetworkReachabilityRef reachabilityRef;	// G=0x266c9; S=0x266d9; 
@property(assign, nonatomic) BOOL reachableOnWWAN;	// G=0x26721; S=0x26731; 
@property(copy, nonatomic) id unreachableBlock;	// G=0x26765; S=0x26779; 
@property(copy, nonatomic) id reachableBlock;	// G=0x26741; S=0x26755; 
+(id)reachabilityForLocalWiFi;	// 0x25e01
+(id)reachabilityForInternetConnection;	// 0x25db5
+(id)reachabilityWithAddress:(const sockaddr_in*)address;	// 0x25d65
+(id)reachabilityWithHostname:(id)hostname;	// 0x25cf9
+(id)reachabilityWithHostName:(id)hostName;	// 0x25cdd
-(void).cxx_destruct;	// 0x267ad
-(id)description;	// 0x2665d
-(void)reachabilityChanged:(unsigned)changed;	// 0x26515
-(id)currentReachabilityFlags;	// 0x26439
-(id)currentReachabilityString;	// 0x26329
-(unsigned)reachabilityFlags;	// 0x262fd
-(int)currentReachabilityStatus;	// 0x262b9
-(BOOL)isInterventionRequired;	// 0x26285
-(BOOL)isConnectionOnDemand;	// 0x2624d
-(BOOL)connectionRequired;	// 0x26221
-(BOOL)isConnectionRequired;	// 0x26211
-(BOOL)isReachableViaWiFi;	// 0x261d9
-(BOOL)isReachableViaWWAN;	// 0x261a1
-(BOOL)isReachable;	// 0x26161
-(BOOL)isReachableWithFlags:(unsigned)flags;	// 0x2612d
-(void)stopNotifier;	// 0x260b1
-(BOOL)startNotifier;	// 0x25f25
-(void)dealloc;	// 0x25ead
-(id)initWithReachabilityRef:(SCNetworkReachabilityRef)reachabilityRef;	// 0x25e51
@end

