/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Safe_cast : XXUnknownSuperclass {
}
+(id)parseToDictionary:(id)dictionary;	// 0x2023d9
+(id)parseToArray:(id)array;	// 0x202341
+(int)parseToIntValue:(id)intValue;	// 0x2022b1
+(float)parseToFloatValue:(id)floatValue;	// 0x202215
+(long)parseTolongValue:(id)value;	// 0x202171
+(long long)parseTolongLongValue:(id)value;	// 0x2020dd
+(int)parseToIntegerValue:(id)integerValue;	// 0x20204d
+(BOOL)parseToBOOLValue:(id)boolvalue;	// 0x201fbd
+(double)parseToDoubleValue:(id)doubleValue;	// 0x201f25
+(id)parseToNumValue:(id)numValue;	// 0x201e29
+(id)parseToString:(id)string;	// 0x201d65
@end

