/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface SampledItem : XXUnknownSuperclass {
	BOOL _isSampled;
	int _lastSamplingRateValue;
	BOOL _logEnabled;
	int _itemId;
}
@property(readonly, assign, nonatomic) BOOL isSampled;	// G=0x4771a9; 
@property(assign, nonatomic) int itemId;	// G=0x477625; S=0x477635; 
-(int)readLastSamplingRateValue;	// 0x477579
-(BOOL)readLastSamplingResult;	// 0x4774bd
-(id)keyIsSampled;	// 0x477481
-(id)keyLastSamplingRate;	// 0x477445
-(void)updateWithSamplingRate:(unsigned)samplingRate;	// 0x477249
-(id)initWithItemId:(int)itemId;	// 0x477125
@end

