/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface ShareModel : XXUnknownSuperclass {
	NSString* _title;
	NSString* _content;
	NSString* _url;
	NSString* _urlsuffix;
	NSString* _imagestr;
	UIImage* _image;
	NSString* _ptitle;
	NSString* _pcontent;
}
@property(retain, nonatomic) NSString* pcontent;	// G=0x30e685; S=0x30e695; 
@property(retain, nonatomic) NSString* ptitle;	// G=0x30e64d; S=0x30e65d; 
@property(retain, nonatomic) UIImage* image;	// G=0x30e615; S=0x30e625; 
@property(retain, nonatomic) NSString* imagestr;	// G=0x30e5dd; S=0x30e5ed; 
@property(retain, nonatomic) NSString* urlsuffix;	// G=0x30e5a5; S=0x30e5b5; 
@property(retain, nonatomic) NSString* url;	// G=0x30e56d; S=0x30e57d; 
@property(retain, nonatomic) NSString* content;	// G=0x30e535; S=0x30e545; 
@property(retain, nonatomic) NSString* title;	// G=0x30e4fd; S=0x30e50d; 
-(void).cxx_destruct;	// 0x30e6bd
@end

