/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageFilter.h"


@interface SmartEyeSmoothCSEnhanceGoodPro : GPUImageFilter {
	int mLevelUniform;
	int sLevelUniform;
	int mXStepUniform;
	int mYStepUniform;
	int contrastRatio_10bitUniform;
	int contrastKeyPointUniform;
	int saturationRatio_10bitUniform;
	float _mLevel;
	float _mXStep;
	float _mYStep;
	float _sLevel;
	float _contrastRatio_10bit;
	float _contrastKeyPoint;
	float _saturationRatio_10bit;
}
@property(assign, nonatomic) float saturationRatio_10bit;	// G=0x83deed; S=0x83defd; 
@property(assign, nonatomic) float contrastKeyPoint;	// G=0x83decd; S=0x83dedd; 
@property(assign, nonatomic) float contrastRatio_10bit;	// G=0x83debd; S=0x83dda5; 
@property(assign, nonatomic) float mYStep;	// G=0x83de9d; S=0x83dcf1; 
@property(assign, nonatomic) float mXStep;	// G=0x83de8d; S=0x83dc99; 
@property(assign, nonatomic) float sLevel;	// G=0x83dead; S=0x83dd49; 
@property(assign, nonatomic) float mLevel;	// G=0x83de7d; S=0x83dc3d; 
-(void)setupFilterForSize:(CGSize)size;	// 0x83daf1
-(id)init;	// 0x83d929
@end

