/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSURL;

@protocol SongProtocol <NSObject>
@property(readonly, assign, nonatomic) BOOL isSilence;
@property(assign, nonatomic) double quietTime;
@property(retain, nonatomic) NSURL* ipodSongURL;
@property(retain, nonatomic) NSURL* fileURL;
-(id)copy;
@end

