/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SSApplicationInfo : XXUnknownSuperclass {
}
+(id)clipboardContent;	// 0x2e4aa5
+(id)applicationVersion;	// 0x2e4961
@end

