/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SSDiskInfo : XXUnknownSuperclass {
}
+(id)formattedMemory:(unsigned long long)memory;	// 0x33aa89
+(id)formatMemory:(long long)memory;	// 0x33a889
+(long long)longFreeDiskSpace;	// 0x33a6c9
+(long long)longDiskSpace;	// 0x33a50d
+(id)usedDiskSpace:(BOOL)space;	// 0x33a2e9
+(id)freeDiskSpace:(BOOL)space;	// 0x33a105
+(id)diskSpace;	// 0x339fc9
@end

