/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SSLocalizationInfo : XXUnknownSuperclass {
}
+(id)currency;	// 0x25f659
+(id)timeZone;	// 0x25f51d
+(id)language;	// 0x25f3e1
+(id)country;	// 0x25f2a5
@end

