/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface SSProcessorInfo : XXUnknownSuperclass {
}
+(int)processorBusSpeed;	// 0x1531f5
+(int)processorSpeed;	// 0x1530f1
+(int)numberActiveProcessors;	// 0x15305d
+(int)numberProcessors;	// 0x152fc9
@end

