/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIStoryboard;

__attribute__((visibility("hidden")))
@interface StoryboardRegist : XXUnknownSuperclass {
	UIStoryboard* _story;
}
@property(retain, nonatomic) UIStoryboard* story;	// G=0x2df095; S=0x2df0a5; 
+(id)sharedStoryboardRegist;	// 0x2def95
-(void).cxx_destruct;	// 0x2df0cd
-(id)makeViewControllerWithID:(id)anId;	// 0x2df075
@end

