/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CAShapeLayer, UIColor;

__attribute__((visibility("hidden")))
@interface SVIndefiniteAnimatedView : XXUnknownSuperclass {
	float _strokeThickness;
	float _radius;
	UIColor* _strokeColor;
	CAShapeLayer* _indefiniteAnimatedLayer;
}
@property(retain, nonatomic) CAShapeLayer* indefiniteAnimatedLayer;	// G=0x1a1e79; S=0x1a2945; 
@property(retain, nonatomic) UIColor* strokeColor;	// G=0x1a2935; S=0x1a27cd; 
@property(assign, nonatomic) float radius;	// G=0x1a2925; S=0x1a2755; 
@property(assign, nonatomic) float strokeThickness;	// G=0x1a2915; S=0x1a283d; 
-(void).cxx_destruct;	// 0x1a296d
-(CGSize)sizeThatFits:(CGSize)fits;	// 0x1a2869
-(void)setFrame:(CGRect)frame;	// 0x1a26e1
-(void)layoutAnimatedLayer;	// 0x1a1cfd
-(void)willMoveToSuperview:(id)superview;	// 0x1a1cb1
@end

