/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TCAPIRequest.h"

@class NSString;

@interface TCListPhotoDic : TCAPIRequest {
	NSString* _paramAlbumid;
}
@property(retain, nonatomic) NSString* paramAlbumid;	// G=0xb3f105; S=0xb3f09d; 
+(id)dictionary;	// 0xb3f065
-(void).cxx_destruct;	// 0xb3f115
@end

