/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TCAPIRequest.h"

@class NSString;

@interface TCSendStoryDic : TCAPIRequest {
	NSString* _paramTitle;
	NSString* _paramSummary;
	NSString* _paramDescription;
	NSString* _paramPics;
	NSString* _paramAct;
	NSString* _paramShareUrl;
}
@property(retain, nonatomic) NSString* paramShareUrl;	// G=0xb3f471; S=0xb3f3b9; 
@property(retain, nonatomic) NSString* paramAct;	// G=0xb3f461; S=0xb3f351; 
@property(retain, nonatomic) NSString* paramPics;	// G=0xb3f451; S=0xb3f2e9; 
@property(retain, nonatomic) NSString* paramDescription;	// G=0xb3f441; S=0xb3f281; 
@property(retain, nonatomic) NSString* paramSummary;	// G=0xb3f431; S=0xb3f219; 
@property(retain, nonatomic) NSString* paramTitle;	// G=0xb3f421; S=0xb3f1b1; 
+(id)dictionary;	// 0xb3f129
-(void).cxx_destruct;	// 0xb3f481
-(id)init;	// 0xb3f161
@end

