/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol TCWebViewControllerDelegate <NSObject>
@optional
-(BOOL)shouldAutorotateWithWebVC:(id)webVC;
-(unsigned)supportedInterfaceOrientationsWithWebVC:(id)webVC;
-(BOOL)webViewController:(id)controller shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(BOOL)webViewController:(id)controller shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)webViewController:(id)controller didFailLoadWithError:(id)error;
-(void)webViewController:(id)controller didCloseWithLastError:(id)lastError;
@end

