/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TencentLoginDelegate.h"
#import "TencentWebViewDelegate.h"
#import "NSObject.h"


@protocol TencentSessionDelegate <NSObject, TencentLoginDelegate, TencentWebViewDelegate>
@optional
-(void)tencentOAuth:(id)auth doCloseViewController:(id)controller;
-(void)tencentOAuth:(id)auth didSendBodyData:(int)data totalBytesWritten:(int)written totalBytesExpectedToWrite:(int)write userData:(id)data5;
-(void)responseDidReceived:(id)response forMessage:(id)message;
-(void)getUserInfoResponse:(id)response;
-(void)tencentFailedUpdate:(int)update;
-(void)tencentDidUpdate:(id)tencent;
-(BOOL)tencentNeedPerformReAuth:(id)auth;
-(BOOL)tencentNeedPerformIncrAuth:(id)auth withPermissions:(id)permissions;
-(void)tencentDidLogout;
@end

