/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "TencentLoginDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, TencentOAuth;

@interface TencentIncrAuthLogic : XXUnknownSuperclass <TencentLoginDelegate> {
	TencentOAuth* _tencentOAuth;
	NSString* _reportAction;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* reportAction;	// G=0xb3f709; S=0xb3f719; 
@property(assign, nonatomic) TencentOAuth* tencentOAuth;	// G=0xb3f6e9; S=0xb3f6f9; 
-(void).cxx_destruct;	// 0xb3f741
-(void)tencentDidNotNetWork;	// 0xb3f6ad
-(void)tencentDidNotLogin:(BOOL)tencent;	// 0xb3f665
-(void)tencentDidLogin;	// 0xb3f55d
-(id)initWithTencentOAuth:(id)tencentOAuth;	// 0xb3f505
@end

