/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor;

__attribute__((visibility("hidden")))
@interface THProgressLayer : XXUnknownSuperclass {
	float _progress;
}
@property(assign, nonatomic) float progress;	// G=0x199f31; S=0x199f41; 
@property(retain, nonatomic) UIColor* borderTintColor;
@property(retain, nonatomic) UIColor* progressTintColor;
+(BOOL)needsDisplayForKey:(id)key;	// 0x199bfd
-(void)drawRectangleInContext:(CGContextRef)context inRect:(CGRect)rect withRadius:(float)radius;	// 0x199e05
-(void)drawInContext:(CGContextRef)context;	// 0x199c65
@end

