/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface TSAVObjectBlockingQueue : XXUnknownSuperclass {
	int _maxSize;
	deque<AVObject *, std::__1::allocator<AVObject *> > _q;
}
@property(assign, nonatomic) int maxSize;	// G=0x81a275; S=0x81a285; 
@property(assign, nonatomic) deque<AVObject *, std::__1::allocator<AVObject *> > q;	// G=0x81a249; S=0x81a261; 
-(id).cxx_construct;	// 0x81a2a9
-(void).cxx_destruct;	// 0x81a295
-(void)enqueue_front:(id)front;	// 0x81a17d
-(id)dequeue_blocking;	// 0x81a0e5
-(id)dequeue;	// 0x81a089
-(void)enqueue:(id)enqueue;	// 0x819f15
-(id)initWithSize:(int)size;	// 0x819ed5
-(id)init;	// 0x819e95
@end

