/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString, NSTextCheckingResult;

__attribute__((visibility("hidden")))
@interface TTTAttributedLabelLink : XXUnknownSuperclass <NSCoding> {
	NSTextCheckingResult* _result;
	NSDictionary* _attributes;
	NSDictionary* _activeAttributes;
	NSDictionary* _inactiveAttributes;
	NSString* _accessibilityValue;
	id _linkTapBlock;
	id _linkLongPressBlock;
}
@property(copy, nonatomic) id linkLongPressBlock;	// G=0x21aa6d; S=0x21aa81; 
@property(copy, nonatomic) id linkTapBlock;	// G=0x21aa49; S=0x21aa5d; 
@property(copy, nonatomic) NSString* accessibilityValue;	// G=0x21a53d; S=0x21aa39; 
@property(readonly, copy, nonatomic) NSDictionary* inactiveAttributes;	// G=0x21aa25; 
@property(readonly, copy, nonatomic) NSDictionary* activeAttributes;	// G=0x21aa11; 
@property(readonly, copy, nonatomic) NSDictionary* attributes;	// G=0x21a9fd; 
@property(readonly, assign, nonatomic) NSTextCheckingResult* result;	// G=0x21a9ed; 
-(void).cxx_destruct;	// 0x21aa91
-(id)initWithCoder:(id)coder;	// 0x21a839
-(void)encodeWithCoder:(id)coder;	// 0x21a6c1
-(id)initWithAttributesFromLabel:(id)label textCheckingResult:(id)result;	// 0x21a485
-(id)initWithAttributes:(id)attributes activeAttributes:(id)attributes2 inactiveAttributes:(id)attributes3 textCheckingResult:(id)result;	// 0x21a389
@end

