/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMANSBJsonParser.h"
#import "UMANSBJsonBase.h"


@protocol UMANSBJsonParser
-(id)objectWithString:(id)string;
@end

@interface UMANSBJsonParser : UMANSBJsonBase <UMANSBJsonParser> {
	const char* c;
}
+(void)initialize;	// 0xaee4e1
-(BOOL)scanIsAtEnd;	// 0xaef42d
-(BOOL)scanNumber:(id*)number;	// 0xaef251
-(BOOL)scanHexQuad:(unsigned short*)quad;	// 0xaef1c9
-(BOOL)scanUnicodeChar:(unsigned short*)aChar;	// 0xaef0cd
-(BOOL)scanRestOfString:(id*)string;	// 0xaeee35
-(BOOL)scanRestOfDictionary:(id*)dictionary;	// 0xaeeb6d
-(BOOL)scanRestOfArray:(id*)array;	// 0xaee97d
-(BOOL)scanRestOfNull:(id*)null;	// 0xaee8fd
-(BOOL)scanRestOfFalse:(id*)aFalse;	// 0xaee87d
-(BOOL)scanRestOfTrue:(id*)aTrue;	// 0xaee7f9
-(BOOL)scanValue:(id*)value;	// 0xaee6a1
-(id)objectWithString:(id)string;	// 0xaee5fd
-(id)fragmentWithString:(id)string;	// 0xaee531
@end

