/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface UMANProtocolData : XXUnknownSuperclass {
}
+(id)md5Value:(id)value;	// 0xaec679
+(id)timezoneString;	// 0xaec609
+(id)languageString;	// 0xaec5b5
+(id)countryString;	// 0xaec551
+(id)appPirateString;	// 0xaec51d
+(BOOL)isAppPirate;	// 0xaec315
+(id)appShortVersionString;	// 0xaec289
+(id)appBundleVersionString;	// 0xaec1fd
+(id)appDisplayNameString;	// 0xaec171
+(id)appPackageNameString;	// 0xaec0e5
+(id)carrierString;	// 0xaec039
+(id)accessString;	// 0xaebe45
+(BOOL)isPad;	// 0xaebde5
+(id)deviceJailBreakString;	// 0xaebdb1
+(BOOL)isDeviceJailBreak;	// 0xaebd39
+(id)orientationString;	// 0xaebce5
+(id)cpuString;	// 0xaebcd9
+(id)osVersionString;	// 0xaebca5
+(id)osString;	// 0xaebc99
+(id)resolutionString;	// 0xaeba2d
+(id)deviceModelString;	// 0xaeb9bd
+(id)UUIDMD5String;	// 0xaeb985
+(id)UUIDString;	// 0xaeb955
+(id)openUDIDString;	// 0xaeb84d
+(id)deviceMacString;	// 0xaeb725
+(id)deviceIDVendorString;	// 0xaeb68d
+(id)lngString;	// 0xaeb681
+(id)latString;	// 0xaeb675
+(id)timeMSString;	// 0xaeb5b5
+(id)timeString;	// 0xaeb4f5
+(id)dateString;	// 0xaeb435
@end

