/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMANBaseEvent.h"

@class NSString, NSMutableDictionary;

@interface UMANEkv : UMANBaseEvent {
	int du;
	NSString* _id;
	NSString* _key;
	NSMutableDictionary* _values;
}
@property(copy, nonatomic) NSString* key;	// G=0xb146d5; S=0xb146ed; 
@property(retain, nonatomic) NSMutableDictionary* values;	// G=0xb146a1; S=0xb146b1; 
@property(copy, nonatomic) NSString* id;	// G=0xb14659; S=0xb14671; 
@property(assign, nonatomic) int du;	// G=0xb14639; S=0xb14649; 
-(void)encodeWithCoder:(id)coder;	// 0xb14559
-(id)initWithCoder:(id)coder;	// 0xb14471
-(void)outputUMLog;	// 0xb14299
-(id)attributes;	// 0xb13e99
-(void)updateDu;	// 0xb13e11
-(id)processDictionary:(id)dictionary;	// 0xb13add
-(id)initWithId:(id)anId key:(id)key values:(id)values isGKV:(BOOL)gkv;	// 0xb138b9
-(void)dealloc;	// 0xb13829
@end

