/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMANBaseEvent.h"

@class NSString;

@interface UMANError : UMANBaseEvent {
	NSString* _context;
}
@property(copy, nonatomic) NSString* context;	// G=0xaf5889; S=0xaf58a1; 
-(void)outputUMLog;	// 0xaf57d5
-(void)encodeWithCoder:(id)coder;	// 0xaf5775
-(id)initWithCoder:(id)coder;	// 0xaf570d
-(id)attributes;	// 0xaf5665
-(id)init;	// 0xaf5615
-(void)dealloc;	// 0xaf55c5
@end

