/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface UMGameLevel : XXUnknownSuperclass <NSCoding> {
	double _ts;
	NSString* _name;
	BOOL _running;
	double _du;
}
@property(assign, nonatomic) double du;	// G=0xaf610d; S=0xaf6125; 
@property(assign, nonatomic) BOOL running;	// G=0xaf60ed; S=0xaf60fd; 
@property(copy, nonatomic) NSString* name;	// G=0xaf60a5; S=0xaf60bd; 
@property(assign, nonatomic) double ts;	// G=0xaf6079; S=0xaf6091; 
+(id)levelWithName:(id)name;	// 0xaf5fed
-(void)dealloc;	// 0xaf6029
-(id)initWithName:(id)name;	// 0xaf5fb9
-(id)initWithCoder:(id)coder;	// 0xaf5fb5
-(void)encodeWithCoder:(id)coder;	// 0xaf5fb1
-(id)init;	// 0xaf5f1d
@end

