/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMTBase.h"
#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface UMTAppInfo : XXUnknownSuperclass <UMTBase, NSCoding> {
	NSString* __key;
	NSString* __version;
	int __version_index;
	NSString* __package_name;
	int __sdk_type;
	NSString* __sdk_version;
	NSString* __channel;
	NSString* __wrapper_type;
	NSString* __wrapper_version;
	int __vertical_type;
	BOOL __key_isset;
	BOOL __version_isset;
	BOOL __version_index_isset;
	BOOL __package_name_isset;
	BOOL __sdk_type_isset;
	BOOL __sdk_version_isset;
	BOOL __channel_isset;
	BOOL __wrapper_type_isset;
	BOOL __wrapper_version_isset;
	BOOL __vertical_type_isset;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;	// G=0xafbacd; 
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic, getter=vertical_type, setter=setVertical_type:) int vertical_type;	// G=0xafb29d; S=0xafb2ad; 
@property(retain, nonatomic, getter=wrapper_version, setter=setWrapper_version:) NSString* wrapper_version;	// G=0xafb1d5; S=0xafb209; 
@property(retain, nonatomic, getter=wrapper_type, setter=setWrapper_type:) NSString* wrapper_type;	// G=0xafb10d; S=0xafb141; 
@property(retain, nonatomic, getter=channel, setter=setChannel:) NSString* channel;	// G=0xafb045; S=0xafb079; 
@property(retain, nonatomic, getter=sdk_version, setter=setSdk_version:) NSString* sdk_version;	// G=0xafaf7d; S=0xafafb1; 
@property(assign, nonatomic, getter=sdk_type, setter=setSdk_type:) int sdk_type;	// G=0xafaf29; S=0xafaf39; 
@property(retain, nonatomic, getter=package_name, setter=setPackage_name:) NSString* package_name;	// G=0xafae61; S=0xafae95; 
@property(assign, nonatomic, getter=version_index, setter=setVersion_index:) int version_index;	// G=0xafae0d; S=0xafae1d; 
@property(retain, nonatomic, getter=version, setter=setVersion:) NSString* version;	// G=0xafad45; S=0xafad79; 
@property(retain, nonatomic, getter=key, setter=setKey:) NSString* key;	// G=0xafac7d; S=0xafacb1; 
-(void)validate;	// 0xafb9b1
-(void)write:(id)write;	// 0xafb55d
-(void)read:(id)read;	// 0xafb2f1
-(void)unsetVertical_type;	// 0xafb2dd
-(BOOL)vertical_typeIsSet;	// 0xafb2cd
-(void)unsetWrapper_version;	// 0xafb265
-(BOOL)wrapper_versionIsSet;	// 0xafb255
-(void)unsetWrapper_type;	// 0xafb19d
-(BOOL)wrapper_typeIsSet;	// 0xafb18d
-(void)unsetChannel;	// 0xafb0d5
-(BOOL)channelIsSet;	// 0xafb0c5
-(void)unsetSdk_version;	// 0xafb00d
-(BOOL)sdk_versionIsSet;	// 0xafaffd
-(void)unsetSdk_type;	// 0xafaf69
-(BOOL)sdk_typeIsSet;	// 0xafaf59
-(void)unsetPackage_name;	// 0xafaef1
-(BOOL)package_nameIsSet;	// 0xafaee1
-(void)unsetVersion_index;	// 0xafae4d
-(BOOL)version_indexIsSet;	// 0xafae3d
-(void)unsetVersion;	// 0xafadd5
-(BOOL)versionIsSet;	// 0xafadc5
-(void)unsetKey;	// 0xafad0d
-(BOOL)keyIsSet;	// 0xafacfd
-(void)dealloc;	// 0xafabb5
-(void)encodeWithCoder:(id)coder;	// 0xafa961
-(id)initWithCoder:(id)coder;	// 0xafa57d
-(id)initWithKey:(id)key version:(id)version version_index:(int)index package_name:(id)name sdk_type:(int)type sdk_version:(id)version6 channel:(id)channel wrapper_type:(id)type8 wrapper_version:(id)version9 vertical_type:(int)type10;	// 0xafa3dd
-(id)init;	// 0xafa3b1
@end

