/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMTBase.h"
#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UMTLatent;

@interface UMTControlPolicy : XXUnknownSuperclass <UMTBase, NSCoding> {
	UMTLatent* __latent;
	BOOL __latent_isset;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;	// G=0xb08119; 
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic, getter=latent, setter=setLatent:) UMTLatent* latent;	// G=0xb07e41; S=0xb07e75; 
-(void)validate;	// 0xb08115
-(void)write:(id)write;	// 0xb0805d
-(void)read:(id)read;	// 0xb07f09
-(void)unsetLatent;	// 0xb07ed1
-(BOOL)latentIsSet;	// 0xb07ec1
-(void)dealloc;	// 0xb07df5
-(void)encodeWithCoder:(id)coder;	// 0xb07da9
-(id)initWithCoder:(id)coder;	// 0xb07d09
-(id)initWithLatent:(id)latent;	// 0xb07ca5
-(id)init;	// 0xb07c79
@end

