/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UMTBase.h"
#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, UMTResolution;

@interface UMTDeviceInfo : XXUnknownSuperclass <UMTBase, NSCoding> {
	NSString* __device_id;
	NSString* __idmd5;
	NSString* __mac_address;
	NSString* __open_udid;
	NSString* __model;
	NSString* __cpu;
	NSString* __os;
	NSString* __os_version;
	UMTResolution* __resolution;
	BOOL __is_jailbroken;
	BOOL __is_pirated;
	NSString* __device_board;
	NSString* __device_brand;
	long long __device_manutime;
	NSString* __device_manufacturer;
	NSString* __device_manuid;
	NSString* __device_name;
	BOOL __device_id_isset;
	BOOL __idmd5_isset;
	BOOL __mac_address_isset;
	BOOL __open_udid_isset;
	BOOL __model_isset;
	BOOL __cpu_isset;
	BOOL __os_isset;
	BOOL __os_version_isset;
	BOOL __resolution_isset;
	BOOL __is_jailbroken_isset;
	BOOL __is_pirated_isset;
	BOOL __device_board_isset;
	BOOL __device_brand_isset;
	BOOL __device_manutime_isset;
	BOOL __device_manufacturer_isset;
	BOOL __device_manuid_isset;
	BOOL __device_name_isset;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;	// G=0xafefdd; 
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic, getter=device_name, setter=setDevice_name:) NSString* device_name;	// G=0xafe3d1; S=0xafe405; 
@property(retain, nonatomic, getter=device_manuid, setter=setDevice_manuid:) NSString* device_manuid;	// G=0xafe309; S=0xafe33d; 
@property(retain, nonatomic, getter=device_manufacturer, setter=setDevice_manufacturer:) NSString* device_manufacturer;	// G=0xafe241; S=0xafe275; 
@property(assign, nonatomic, getter=device_manutime, setter=setDevice_manutime:) long long device_manutime;	// G=0xafe1dd; S=0xafe1f5; 
@property(retain, nonatomic, getter=device_brand, setter=setDevice_brand:) NSString* device_brand;	// G=0xafe115; S=0xafe149; 
@property(retain, nonatomic, getter=device_board, setter=setDevice_board:) NSString* device_board;	// G=0xafe04d; S=0xafe081; 
@property(assign, nonatomic, getter=is_pirated, setter=setIs_pirated:) BOOL is_pirated;	// G=0xafdff9; S=0xafe009; 
@property(assign, nonatomic, getter=is_jailbroken, setter=setIs_jailbroken:) BOOL is_jailbroken;	// G=0xafdfa5; S=0xafdfb5; 
@property(retain, nonatomic, getter=resolution, setter=setResolution:) UMTResolution* resolution;	// G=0xafdedd; S=0xafdf11; 
@property(retain, nonatomic, getter=os_version, setter=setOs_version:) NSString* os_version;	// G=0xafde15; S=0xafde49; 
@property(retain, nonatomic, getter=os, setter=setOs:) NSString* os;	// G=0xafdd4d; S=0xafdd81; 
@property(retain, nonatomic, getter=cpu, setter=setCpu:) NSString* cpu;	// G=0xafdc85; S=0xafdcb9; 
@property(retain, nonatomic, getter=model, setter=setModel:) NSString* model;	// G=0xafdbbd; S=0xafdbf1; 
@property(retain, nonatomic, getter=open_udid, setter=setOpen_udid:) NSString* open_udid;	// G=0xafdaf5; S=0xafdb29; 
@property(retain, nonatomic, getter=mac_address, setter=setMac_address:) NSString* mac_address;	// G=0xafda2d; S=0xafda61; 
@property(retain, nonatomic, getter=idmd5, setter=setIdmd5:) NSString* idmd5;	// G=0xafd965; S=0xafd999; 
@property(retain, nonatomic, getter=device_id, setter=setDevice_id:) NSString* device_id;	// G=0xafd89d; S=0xafd8d1; 
-(void)validate;	// 0xafefd9
-(void)write:(id)write;	// 0xafe8a9
-(void)read:(id)read;	// 0xafe499
-(void)unsetDevice_name;	// 0xafe461
-(BOOL)device_nameIsSet;	// 0xafe451
-(void)unsetDevice_manuid;	// 0xafe399
-(BOOL)device_manuidIsSet;	// 0xafe389
-(void)unsetDevice_manufacturer;	// 0xafe2d1
-(BOOL)device_manufacturerIsSet;	// 0xafe2c1
-(void)unsetDevice_manutime;	// 0xafe22d
-(BOOL)device_manutimeIsSet;	// 0xafe21d
-(void)unsetDevice_brand;	// 0xafe1a5
-(BOOL)device_brandIsSet;	// 0xafe195
-(void)unsetDevice_board;	// 0xafe0dd
-(BOOL)device_boardIsSet;	// 0xafe0cd
-(void)unsetIs_pirated;	// 0xafe039
-(BOOL)is_piratedIsSet;	// 0xafe029
-(void)unsetIs_jailbroken;	// 0xafdfe5
-(BOOL)is_jailbrokenIsSet;	// 0xafdfd5
-(void)unsetResolution;	// 0xafdf6d
-(BOOL)resolutionIsSet;	// 0xafdf5d
-(void)unsetOs_version;	// 0xafdea5
-(BOOL)os_versionIsSet;	// 0xafde95
-(void)unsetOs;	// 0xafdddd
-(BOOL)osIsSet;	// 0xafddcd
-(void)unsetCpu;	// 0xafdd15
-(BOOL)cpuIsSet;	// 0xafdd05
-(void)unsetModel;	// 0xafdc4d
-(BOOL)modelIsSet;	// 0xafdc3d
-(void)unsetOpen_udid;	// 0xafdb85
-(BOOL)open_udidIsSet;	// 0xafdb75
-(void)unsetMac_address;	// 0xafdabd
-(BOOL)mac_addressIsSet;	// 0xafdaad
-(void)unsetIdmd5;	// 0xafd9f5
-(BOOL)idmd5IsSet;	// 0xafd9e5
-(void)unsetDevice_id;	// 0xafd92d
-(BOOL)device_idIsSet;	// 0xafd91d
-(void)dealloc;	// 0xafd749
-(void)encodeWithCoder:(id)coder;	// 0xafd359
-(id)initWithCoder:(id)coder;	// 0xafccc5
-(id)initWithDevice_id:(id)device_id idmd5:(id)a5 mac_address:(id)address open_udid:(id)udid model:(id)model cpu:(id)cpu os:(id)os os_version:(id)version resolution:(id)resolution is_jailbroken:(BOOL)jailbroken is_pirated:(BOOL)pirated device_board:(id)board device_brand:(id)brand device_manutime:(long long)manutime device_manufacturer:(id)manufacturer device_manuid:(id)manuid device_name:(id)name;	// 0xafca21
-(id)init;	// 0xafc9f5
@end

