/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((objc_exception))
@interface UMTException : XXUnknownSuperclass {
}
+(id)exceptionWithName:(id)name reason:(id)reason error:(id)error;	// 0xb20bf5
+(id)exceptionWithName:(id)name reason:(id)reason;	// 0xb20bd1
+(id)exceptionWithName:(id)name;	// 0xb20ba5
-(id)description;	// 0xb20c5d
@end

