/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "HJTPUManagerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "DSViewController.h"
#import "UITextFieldDelegate.h"
#import "living-Structs.h"

@class NSString, UIColor, UIBarButtonItem, RegisteTextField, NSTimer, UILabel, UIButton, HJVerifiedDetail, UIViewController;

__attribute__((visibility("hidden")))
@interface UpCentifyViewController : DSViewController <UITextFieldDelegate, HJTPUManagerDelegate, UIAlertViewDelegate> {
	UIColor* _backgroundColorOfView;
	HJVerifiedDetail* _verifiedDetail;
	UIViewController* _contextViewcontroller;
	UIButton* _reSendBtn;
	UILabel* _mobileLabel;
	RegisteTextField* _verifyCodeField;
	UILabel* _bottomLabel;
	UILabel* _topLabel;
	UIButton* _voiceCodeBtn;
	UIBarButtonItem* _sendItem;
	NSTimer* _codeTimer;
	unsigned _currentSecond;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned currentSecond;	// G=0x296b9; S=0x296c9; 
@property(retain, nonatomic) NSTimer* codeTimer;	// G=0x29681; S=0x29691; 
@property(retain, nonatomic) UIBarButtonItem* sendItem;	// G=0x29649; S=0x29659; 
@property(assign, nonatomic) __weak UIButton* voiceCodeBtn;	// G=0x29615; S=0x29635; 
@property(assign, nonatomic) __weak UILabel* topLabel;	// G=0x295e1; S=0x29601; 
@property(assign, nonatomic) __weak UILabel* bottomLabel;	// G=0x295ad; S=0x295cd; 
@property(assign, nonatomic) __weak RegisteTextField* verifyCodeField;	// G=0x29579; S=0x29599; 
@property(assign, nonatomic) __weak UILabel* mobileLabel;	// G=0x29545; S=0x29565; 
@property(assign, nonatomic) __weak UIButton* reSendBtn;	// G=0x29511; S=0x29531; 
@property(retain, nonatomic) UIViewController* contextViewcontroller;	// G=0x294d9; S=0x294e9; 
@property(retain, nonatomic) HJVerifiedDetail* verifiedDetail;	// G=0x294a1; S=0x294b1; 
@property(retain, nonatomic) UIColor* backgroundColorOfView;	// G=0x29491; S=0x27ca1; 
-(void).cxx_destruct;	// 0x296d9
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;	// 0x29341
-(void)resignResponder:(id)responder;	// 0x29305
-(void)dealloc;	// 0x292c5
-(void)fetchVoiceCode:(id)code;	// 0x29005
-(void)reSendButton:(id)button;	// 0x28bed
-(void)verifyCodeChanged:(id)changed;	// 0x28b49
-(void)didReceiveMemoryWarning;	// 0x28b1d
-(void)viewWillAppear:(BOOL)view;	// 0x28939
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;	// 0x288cd
-(void)sendItemAction:(id)action;	// 0x28145
-(void)secondChange;	// 0x28015
-(void)endTimer;	// 0x27df1
-(void)runTimer;	// 0x27d11
-(void)viewDidLoad;	// 0x27835
@end

