/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UPBaseViewController.h"

@class NSString, UILabel, UIImageView, UIView, CAGradientLayer;

@interface UPInitViewController : UPBaseViewController {
	BOOL mNeedUpgrade;
	NSString* mUpgradeUrl;
	UIImageView* _logoView;
	UILabel* _version;
	UILabel* _copyRight;
	UIView* _backGroundView;
	CAGradientLayer* _backGroundLayer;
	UIImageView* _loadingView;
}
@property(retain, nonatomic) NSString* mUpgradeUrl;	// G=0xc6facd; S=0xc6fadd; 
-(void).cxx_destruct;	// 0xc6fb05
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xc6f6c9
-(void)comunicateToUPMPDidFailWithErrorType:(int)comunicateToUPMP error:(id)error;	// 0xc6f699
-(void)comunicateToUPMPDidSucceedWithEvent:(int)comunicateToUPMP;	// 0xc6ee31
-(void)pushViewToUserInfoViewController;	// 0xc6ed09
-(void)pushViewControllerToOrderViewController;	// 0xc6eaa1
-(void)buttonCancelClicked;	// 0xc6ea4d
-(void)buttonOKClicked;	// 0xc6e889
-(void)postInitMessage;	// 0xc6e3ad
-(void)addSubViews;	// 0xc6db79
-(void)setBgColors:(id)colors;	// 0xc6d82d
-(void)showLoadingAlertView;	// 0xc6d641
-(void)resetStatusBar;	// 0xc6d509
-(void)viewDidUnload;	// 0xc6d4dd
-(void)dealloc;	// 0xc6d3dd
-(void)viewDidLoad;	// 0xc6d065
-(id)initWithNibName:(id)nibName bundle:(id)bundle;	// 0xc6cf95
@end

