/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UPJsonBase.h"
#import "UPJsonParser.h"


@protocol UPJsonParser
-(id)objectWithString:(id)string;
@end

@interface UPJsonParser : UPJsonBase <UPJsonParser> {
	const char* c;
}
+(void)initialize;	// 0xc47521
-(BOOL)scanIsAtEnd;	// 0xc4846d
-(BOOL)scanNumber:(id*)number;	// 0xc48291
-(BOOL)scanHexQuad:(unsigned short*)quad;	// 0xc48209
-(BOOL)scanUnicodeChar:(unsigned short*)aChar;	// 0xc4810d
-(BOOL)scanRestOfString:(id*)string;	// 0xc47e75
-(BOOL)scanRestOfDictionary:(id*)dictionary;	// 0xc47bad
-(BOOL)scanRestOfArray:(id*)array;	// 0xc479bd
-(BOOL)scanRestOfNull:(id*)null;	// 0xc4793d
-(BOOL)scanRestOfFalse:(id*)aFalse;	// 0xc478bd
-(BOOL)scanRestOfTrue:(id*)aTrue;	// 0xc47839
-(BOOL)scanValue:(id*)value;	// 0xc476e1
-(id)objectWithString:(id)string;	// 0xc4763d
-(id)fragmentWithString:(id)string;	// 0xc47571
@end

