/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIColor, NSMutableArray;
@protocol UPKeyboardDelegate;

@interface UPKeyboard : XXUnknownSuperclass {
	BOOL mSecurity;
	UPPasswordTool* _pinBlockTool;
	NSMutableArray* _rowLines;
	float _keyWidth;
	float _keyHeight;
	UIView* _titleView;
	UIView* _keyboardView;
	UIColor* _bgColor;
	id<UPKeyboardDelegate> mDelegate;
	NSMutableArray* mKeyArray;
	NSMutableArray* rowLines;
}
@property(retain, nonatomic) NSMutableArray* mKeyArray;	// G=0xc6a1ad; S=0xc6a1bd; 
@property(retain, nonatomic) NSMutableArray* rowLines;	// G=0xc6a1e5; S=0xc6a1f5; 
@property(assign, nonatomic) __weak id<UPKeyboardDelegate> mDelegate;	// G=0xc6a179; S=0xc6a199; 
-(void).cxx_destruct;	// 0xc6a21d
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xc69d71
-(void)makeSeperators;	// 0xc69985
-(void)refreshKeyBoard;	// 0xc697bd
-(id)getMessage:(id)message;	// 0xc69685
-(void)keyBoardMode:(int)mode;	// 0xc6958d
-(void)setSecurity:(BOOL)security;	// 0xc69269
-(id)initWithFrame:(CGRect)frame;	// 0xc690cd
-(id)keyboardKeyColor;	// 0xc69085
-(void)addDeleteBtn:(CGRect)btn;	// 0xc68c71
-(void)addDoneBtn:(CGRect)btn;	// 0xc68879
-(void)addKeyBtn:(CGRect)btn title:(id)title;	// 0xc68495
-(void)prepareKeyArray;	// 0xc68101
-(void)addKeys;	// 0xc67e49
-(void)makeKeyboardView;	// 0xc67d71
-(void)makeTitleView;	// 0xc67a35
-(void)deleteEncryptedPin;	// 0xc67a21
-(void)cleanSecurityPin;	// 0xc67a0d
-(void)encryptText:(id)text;	// 0xc67935
-(void)deleteClick;	// 0xc67841
-(void)textChanged:(id)changed;	// 0xc6764d
-(void)doneClick:(id)click;	// 0xc67575
-(id)configureBackgroundColor;	// 0xc6753d
-(void)prepareLocalData;	// 0xc67539
-(id)init;	// 0xc6736d
-(void)dealloc;	// 0xc6721d
@end

