/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol UPKeyboardDelegate
-(void)deleteClick;
-(void)textChanged:(id)changed;
-(void)doneClick;
@end

