/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UPMPService.h"


@interface UPMPServiceConsumption : UPMPService {
}
-(BOOL)parseUPMPResponse:(id)response;	// 0xc52d65
-(void)parsePromotionCouponResponse:(id)response;	// 0xc52c71
-(void)parsePromotionScoreResponse:(id)response;	// 0xc52b7d
-(void)parseOpenRulesResponse:(id)response;	// 0xc52a31
-(void)parseFollowRulesResponse:(id)response;	// 0xc528e5
-(void)parseBingoPromotionResponse:(id)response;	// 0xc52799
-(void)parseGetUserInfoResponse:(id)response;	// 0xc5264d
-(void)parseGetLoginRulesResponse:(id)response;	// 0xc52501
-(void)parseUnbindCardResponse:(id)response;	// 0xc52425
-(void)parseRulesResponse:(id)response;	// 0xc52191
-(void)postPromotionCoupon:(id)coupon andElement:(id)element;	// 0xc51fbd
-(void)postPromotionScore:(id)score andUUID:(id)uuid;	// 0xc51d7d
-(void)postBindCardRulesRequestWithParams:(id)params;	// 0xc51bdd
-(void)postReopenRequest;	// 0xc51a79
-(void)postBingoPromotionRequest;	// 0xc51915
-(void)postGetUserInfoRequestWithParams:(id)params;	// 0xc5177d
-(void)postGetLoginRequest;	// 0xc5162d
-(void)postOpenRulesRequestWithFlag:(id)flag param:(id)param;	// 0xc51399
-(void)postFollowRulesRequestWithParams:(id)params;	// 0xc51201
-(void)postRulesRequestWithFlag:(id)flag param:(id)param payType:(id)type payMode:(id)mode;	// 0xc50f41
-(void)postUnBindCardRequestWithCardId:(id)cardId;	// 0xc50da9
-(void)postModifyPhoneRequestWithCard:(id)card;	// 0xc50b05
@end

