/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "UPBaseCell.h"

@class UPTextField, NSMutableString;

@interface UPPasswordCell : UPBaseCell {
	NSMutableString* _securityPin;
	UPTextField* pTextField;
}
-(void).cxx_destruct;	// 0xc90339
-(void)deleteClick;	// 0xc90219
-(void)textChanged:(id)changed;	// 0xc900c5
-(BOOL)isLegalLength;	// 0xc90061
-(id)param;	// 0xc8fedd
-(id)initWithFrame:(CGRect)frame content:(id)content delegate:(id)delegate;	// 0xc8fd69
@end

