/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

@interface UPPromotionLoginView : XXUnknownSuperclass {
	NSDictionary* myContentDic;
}
-(void).cxx_destruct;	// 0xc95551
-(void)loginAcition;	// 0xc95501
-(void)addSubviews;	// 0xc94fc1
-(id)initWithFrame:(CGRect)frame andContent:(id)content;	// 0xc94f39
@end

