/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, UPLineView, NSMutableArray;
@protocol UPPromotionTabBarViewDelegate;

@interface UPPromotionTabBarViewController : XXUnknownSuperclass {
	NSMutableArray* tabButtonArray;
	UPLineView* cursorline;
	NSArray* tabNameArr;
	unsigned _selectIndex;
	id<UPPromotionTabBarViewDelegate> _myDelegate;
}
@property(assign, nonatomic) __weak id<UPPromotionTabBarViewDelegate> myDelegate;	// G=0xc7fc91; S=0xc7fcb1; 
@property(assign, nonatomic) unsigned selectIndex;	// G=0xc7fc71; S=0xc7fc81; 
-(void).cxx_destruct;	// 0xc7fcc5
-(void)buttonAction:(id)action;	// 0xc7fb81
-(void)selectButtonAtIndex:(unsigned)index;	// 0xc7f8fd
-(void)deselectButtons;	// 0xc7f801
-(void)didReceiveMemoryWarning;	// 0xc7f7d5
-(void)addbutionsStyle1;	// 0xc7f435
-(void)viewDidLoad;	// 0xc7f20d
-(id)initWithButtonNames:(id)buttonNames;	// 0xc7f1a1
@end

