/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UPBaseViewController.h"
#import "living-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UPPullListViewDelegate.h"

@class NSString, UPLabel, NSArray, UIView, UIActivityIndicatorView, UITableView;

@interface UPSucceedViewController : UPBaseViewController <UPPullListViewDelegate, UITableViewDataSource, UITableViewDelegate> {
	UPLabel* _tempPayInfoLabel;
	UIView* _successInfoView;
	UPLabel* _successTitleLabel;
	UPLabel* _successLabel;
	UIActivityIndicatorView* _indicator;
	UPLabel* _waitLabel;
	UITableView* _tableView;
	NSArray* promotions;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSArray* promotions;	// G=0xc880b1; S=0xc880c1; 
-(void).cxx_destruct;	// 0xc880e9
-(void)comunicateToUPMPDidFailWithErrorType:(int)comunicateToUPMP error:(id)error;	// 0xc88075
-(void)comunicateToUPMPDidSucceedWithEvent:(int)comunicateToUPMP;	// 0xc88059
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xc87cf5
-(id)atrributedStringFromInfo:(id)info;	// 0xc87649
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0xc873c5
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0xc873bd
-(float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0xc873b5
-(float)tableView:(id)view heightForFooterInSection:(int)section;	// 0xc873ad
-(int)numberOfSectionsInTableView:(id)tableView;	// 0xc873a9
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0xc86fe1
-(id)tableView:(id)view viewForFooterInSection:(int)section;	// 0xc86dd1
-(id)tableView:(id)view viewForHeaderInSection:(int)section;	// 0xc86a61
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0xc86985
-(void)nextAction:(id)action;	// 0xc86965
-(void)makeTableViewAtY:(float)y;	// 0xc865e1
-(float)makeLuckView;	// 0xc862e1
-(float)makePaySuccessInfo;	// 0xc855d1
-(float)makeOldPaySuccessInfo;	// 0xc8512d
-(float)addTemporaryPay:(float)pay;	// 0xc84bc1
-(void)addSubViews;	// 0xc8467d
-(void)addNavigationBar;	// 0xc84469
-(void)viewDidUnload;	// 0xc8443d
-(void)viewDidAppear:(BOOL)view;	// 0xc842bd
-(void)addAdBar;	// 0xc842b9
-(void)viewDidLoad;	// 0xc84145
-(id)initWithNibName:(id)nibName bundle:(id)bundle;	// 0xc84075
-(void)dealloc;	// 0xc83f75
@end

