/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

@interface UPToggleView : XXUnknownSuperclass {
	UIImageView* _imageView_CheckBox;
	BOOL _selected;
	id _actionBlcok;
	id _linkBlock;
}
@property(copy, nonatomic) id linkBlock;	// G=0xc7451d; S=0xc74531; 
@property(copy, nonatomic) id actionBlcok;	// G=0xc744d9; S=0xc744ed; 
@property(assign, nonatomic) BOOL selected;	// G=0xc744c9; S=0xc7442d; 
+(float)boxHeight;	// 0xc73b55
-(void).cxx_destruct;	// 0xc74561
-(void)tapAction;	// 0xc74331
-(void)chageBackgroundColor;	// 0xc7432d
-(void)installmentDesAction;	// 0xc742e1
-(id)initWithOrigin:(CGPoint)origin title:(id)title actionBlock:(id)block;	// 0xc74295
-(id)initWithOrigin:(CGPoint)origin title:(id)title urlDic:(id)dic actionBlock:(id)block linkBlock:(id)block5;	// 0xc73b5d
-(id)initWithFrame:(CGRect)frame;	// 0xc73b1d
@end

