/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UPBaseViewController.h"
#import "UPListViewDelegate.h"

@class NSString, UPPaymentElementsView, UPNewBankCardCell, UIView, UPDefaultCardView, UPListView, NSMutableArray, UPPromotionView;

@interface UPUserInfoViewController : UPBaseViewController <UPListViewDelegate> {
	UPPaymentElementsView* _userInfoView;
	UIView* _indicatorView;
	UIView* _mainView;
	BOOL _noBindCards;
	BOOL _isUPMP;
	bool _handleModifyPhone;
	int _selectedCardIndex;
	int _indexBeforeSelected;
	UPDefaultCardView* _defaultCardView;
	UPPromotionView* _promotionView;
	UPListView* _cardListView;
	UPNewBankCardCell* _cardInputCell;
	NSMutableArray* _bindCardDescriptions;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;	// 0xc8f6a5
-(void)buttonOKClicked;	// 0xc8f5d5
-(void)buttonCancelClicked;	// 0xc8f509
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;	// 0xc8f0cd
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;	// 0xc8ec49
-(void)comunicateToUPMPDidFailWithErrorType:(int)comunicateToUPMP error:(id)error;	// 0xc8eb75
-(void)comunicateToUPMPDidSucceedWithEvent:(int)comunicateToUPMP;	// 0xc8ea2d
-(void)pushViewControllerToPayingViewController;	// 0xc8e979
-(void)pushViewControllerToEntrustViewController;	// 0xc8e8d9
-(void)pullListAnimationDidStart:(float)pullListAnimation;	// 0xc8e749
-(void)listViewDidSelectedAtIndex:(int)listView;	// 0xc8e5dd
-(void)pushViewToInputViewController;	// 0xc8e565
-(void)refreshCardRulesView;	// 0xc8e111
-(void)nextAction:(id)action;	// 0xc8df19
-(void)postCommonCmd:(id)cmd;	// 0xc8dd55
-(void)pushViewToSuccessViewContriller;	// 0xc8dce1
-(void)pushViewToBindUrlViewContriller;	// 0xc8db49
-(float)addIndicatorViewWithOriginY:(float)originY;	// 0xc8d50d
-(void)showSupportedBank;	// 0xc8d39d
-(void)modifyAction:(id)action;	// 0xc8d28d
-(float)makeInputAtY:(float)y;	// 0xc8cdfd
-(float)showNoCardInfoAtY:(float)y;	// 0xc8cc29
-(float)addCardRules:(id)rules originY:(float)y;	// 0xc8caf9
-(void)showBindCardsList;	// 0xc8c889
-(float)addCardListViewWithOriginY:(float)originY;	// 0xc8c701
-(float)addUserInfosViewWithOriginY:(float)originY;	// 0xc8c5b9
-(void)addSubViews;	// 0xc8c0dd
-(float)makeInstalmentViewAtY:(float)y;	// 0xc8bfa1
-(float)makePromotionViewAtY:(float)y;	// 0xc8be79
-(void)promotionViewOpenUrl:(id)url andTitle:(id)title;	// 0xc8be49
-(void)promotionView:(id)view WillChangeFrameWithOffset:(float);	// 0xc8bc49
-(void)promotionAndInstalmentConflict:(id)conflict;	// 0xc8ba49
-(void)resetFrameOfView:(id)view withYOffset:(float)yoffset;	// 0xc8b9c5
-(void)addNavigationBar;	// 0xc8b851
-(void)releaseLocalDatas;	// 0xc8b7f5
-(void)initLocalDatas;	// 0xc8b3fd
-(void)viewDidAppear:(BOOL)view;	// 0xc8b399
-(void)didReceiveMemoryWarning;	// 0xc8b36d
-(void)viewDidLoad;	// 0xc8b319
-(void)dealloc;	// 0xc8b29d
-(id)initWithNibName:(id)nibName bundle:(id)bundle;	// 0xc8b255
@end

