/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface UTDevice : XXUnknownSuperclass {
}
+(void)aidAsync:(id)async token:(id)token aidDelegate:(id)delegate;	// 0xcf8dad
+(id)aid:(id)aid token:(id)token;	// 0xcf8b4d
+(id)utdid;	// 0xcf85dd
+(id)bundleSeedID;	// 0xcf83a9
@end

