/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView, UIButton;

__attribute__((visibility("hidden")))
@interface VideoTableViewCell : XXUnknownSuperclass {
	UIImageView* _imageViewVideo;
	UILabel* _labelTitle;
	UILabel* _labelSubtitle;
	UIButton* _buttonPlay;
}
@property(retain, nonatomic) UIButton* buttonPlay;	// G=0x251bed; S=0x251bfd; 
@property(retain, nonatomic) UILabel* labelSubtitle;	// G=0x251bb5; S=0x251bc5; 
@property(retain, nonatomic) UILabel* labelTitle;	// G=0x251b7d; S=0x251b8d; 
@property(retain, nonatomic) UIImageView* imageViewVideo;	// G=0x251b45; S=0x251b55; 
-(void).cxx_destruct;	// 0x251c25
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;	// 0x251b15
-(void)awakeFromNib;	// 0x251b11
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;	// 0x251ae1
@end

