/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import "GPUImageTwoInputFilter.h"


@interface VSJoinFilter : GPUImageTwoInputFilter {
	CGRect _inner;
}
@property(assign, nonatomic) CGRect inner;	// G=0x83e681; S=0x83e699; 
-(void)setInnerRegion:(CGRect)region;	// 0x83e625
-(id)initWithInner:(CGRect)inner;	// 0x83e5c5
-(id)init;	// 0x83e5a9
@end

