/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBHttpRequestDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, WeiboSDK3rdApp;

@interface WBAidManager : XXUnknownSuperclass <WBHttpRequestDelegate> {
	int aidStatus;
	WeiboSDK3rdApp* _app;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak NSString* sub;	// G=0xd3497d; S=0xd349f1; 
@property(assign, nonatomic) __weak NSString* aid;	// G=0xd34829; S=0xd3489d; 
@property(retain, nonatomic) WeiboSDK3rdApp* app;	// G=0xd35aed; S=0xd35afd; 
+(id)sharedInstance;	// 0xd34ad1
-(void).cxx_destruct;	// 0xd35b25
-(void)request:(id)request didFinishLoadingWithResult:(id)result;	// 0xd35769
-(void)request:(id)request didFailWithError:(id)error;	// 0xd355f5
-(void)retryFetchAidSinceErrorHappened;	// 0xd355c1
-(void)fetchAidIfNeededWithApp:(id)app;	// 0xd35525
-(void)fetchAid:(BOOL)aid;	// 0xd351f9
-(id)generateMFPString;	// 0xd34c6d
-(id)advertisementIdentifier;	// 0xd34bf9
-(id)init;	// 0xd34b91
@end

