/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBBaseRequest.h"

@class NSString;

@interface WBAuthorizeRequest : WBBaseRequest {
	BOOL _shouldShowWebViewForAuthIfCannotSSO;
	NSString* redirectURI;
	NSString* scope;
}
@property(assign, nonatomic) BOOL shouldShowWebViewForAuthIfCannotSSO;	// G=0xd23ae9; S=0xd23af9; 
@property(retain, nonatomic) NSString* scope;	// G=0xd23ab1; S=0xd23ac1; 
@property(retain, nonatomic) NSString* redirectURI;	// G=0xd23a79; S=0xd23a89; 
+(Class)associateResponseClass;	// 0xd23a5d
-(void).cxx_destruct;	// 0xd23b09
-(void)loadFromDictionary:(id)dictionary;	// 0xd23999
-(void)storeToDictionary:(id)dictionary;	// 0xd238a5
-(id)validate;	// 0xd237ed
-(BOOL)canBeReceived;	// 0xd237e9
-(BOOL)canBeSent;	// 0xd237e5
-(id)init;	// 0xd237a1
@end

