/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import "living-Structs.h"
#import "UITableViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, NSMutableArray, UITableView;
@protocol WBCountryCodeViewControllerDelegate;

@interface WBCountryCodeViewController : XXUnknownSuperclass <UITableViewDataSource, UITableViewDelegate> {
	UITableView* countryCodeTableView;
	NSMutableArray* countryArray;
	id<WBCountryCodeViewControllerDelegate> delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<WBCountryCodeViewControllerDelegate> delegate;	// G=0xd33c7d; S=0xd33c9d; 
-(void).cxx_destruct;	// 0xd33cb1
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;	// 0xd33b65
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;	// 0xd33745
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;	// 0xd3373d
-(int)tableView:(id)view numberOfRowsInSection:(int)section;	// 0xd336f1
-(int)numberOfSectionsInTableView:(id)tableView;	// 0xd336d1
-(id)tableView:(id)view titleForHeaderInSection:(int)section;	// 0xd3361d
-(id)tableView:(id)view viewForHeaderInSection:(int)section;	// 0xd33315
-(float)tableView:(id)view heightForHeaderInSection:(int)section;	// 0xd332e9
-(id)sectionIndexTitlesForTableView:(id)tableView;	// 0xd3311d
-(void)configData:(id)data;	// 0xd32ebd
-(void)dealloc;	// 0xd32e29
-(void)back;	// 0xd32e15
-(void)didReceiveMemoryWarning;	// 0xd32de9
-(void)viewDidLoad;	// 0xd32c99
@end

