/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIGestureRecognizerDelegate.h"
#import "WBHttpRequestDelegate.h"
#import "UITextFieldDelegate.h"
#import "WBCountryCodeViewControllerDelegate.h"
#import "WBSDKTTTAttributedLabelDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "living-Structs.h"

@class WBSDKPhoneCountryView, WBSDKProgressHUD, WBSDKTTTAttributedLabel, WBSDKTextField, NSString, NSTimer, UILabel, UIImageView, UIButton, UIScrollView;

@interface WBMessageRegisterViewController : XXUnknownSuperclass <WBHttpRequestDelegate, UITextFieldDelegate, WBCountryCodeViewControllerDelegate, UIGestureRecognizerDelegate, WBSDKTTTAttributedLabelDelegate> {
	UIScrollView* _backgroundScrollView;
	WBSDKPhoneCountryView* _countryView;
	UILabel* tipsLabel;
	UILabel* serviceLabel;
	UIImageView* _textFieldBackgroudImageView;
	WBSDKTextField* _phoneNumberTextField;
	WBSDKTextField* _verifyCodeTextField;
	UILabel* _toastMessageLabel;
	UIButton* _loginButton;
	UIButton* _sendVerifyCodeButton;
	int _resendTime;
	NSTimer* _resendCodeTimer;
	WBSDKProgressHUD* hud;
	WBSDKTTTAttributedLabel* _stipulationLabel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) WBSDKTTTAttributedLabel* stipulationLabel;	// G=0xd4d951; S=0xd4ebb1; 
-(void).cxx_destruct;	// 0xd4ebd9
-(void)attributedLabel:(id)label didSelectLinkWithURL:(id)url;	// 0xd4eaf9
-(BOOL)textFieldShouldReturn:(id)textField;	// 0xd4ea95
-(void)textFieldValueDidChanged:(id)textFieldValue;	// 0xd4e9a1
-(void)textFieldDidBeginEditing:(id)textField;	// 0xd4e819
-(void)keyboardDidShowNotification:(id)keyboard;	// 0xd4e809
-(void)keyboardWillHideNotification:(id)keyboard;	// 0xd4e7f9
-(void)keyboardWillShowNotification:(id)keyboard;	// 0xd4e7e9
-(void)keyboardChangedNotification:(id)notification;	// 0xd4e629
-(void)toastDisplayWithMessage:(id)message isError:(BOOL)error;	// 0xd4e369
-(void)request:(id)request didFinishLoadingWithResult:(id)result;	// 0xd4dd1d
-(void)request:(id)request didFailWithError:(id)error;	// 0xd4dbc9
-(void)countryCodeDidSelect:(id)countryCode;	// 0xd4dba9
-(void)openPrivacyProtocolH5;	// 0xd4d87d
-(void)openUseProtocolH5;	// 0xd4d7a9
-(void)countryBtnClick;	// 0xd4d6c1
-(void)changeTime;	// 0xd4d221
-(void)getVerifyCode;	// 0xd4cd35
-(BOOL)checkIsPhoneNumber;	// 0xd4cbcd
-(BOOL)isPureInt:(id)int;	// 0xd4cb5d
-(BOOL)isEmptyOrWhitespace:(id)whitespace;	// 0xd4cac5
-(void)SendVerify;	// 0xd4c435
-(void)presentedVCBackButtonClicked;	// 0xd4c119
-(void)setupSubviews;	// 0xd4bb4d
-(void)initStipulations;	// 0xd4b8b5
-(void)initVerifyCodeButton;	// 0xd4b461
-(void)initLoginButton;	// 0xd4af39
-(void)initToastMessageLabel;	// 0xd4ade9
-(void)initTextField;	// 0xd4a89d
-(void)configSubviewsFrame;	// 0xd4a389
-(void)didReceiveMemoryWarning;	// 0xd4a359
-(void)keyboardHide:(id)hide;	// 0xd4a201
-(void)viewDidLoad;	// 0xd49fd5
-(void)dealloc;	// 0xd49ec9
-(id)initWithTitle:(id)title;	// 0xd49e51
@end

