/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WBOrderObject : XXUnknownSuperclass {
	NSString* orderString;
}
@property(retain, nonatomic) NSString* orderString;	// G=0xd2425d; S=0xd2426d; 
+(id)orderWithDictionary:(id)dictionary;	// 0xd24161
+(id)dictionaryWithOrder:(id)order;	// 0xd2408d
+(id)order;	// 0xd2402d
-(void).cxx_destruct;	// 0xd24295
-(id)validate;	// 0xd24059
@end

