/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBSDKBasicWebViewController.h"

@class NSDictionary;
@protocol WBSDKNormalWebRequestDelegate;

@interface WBSDKNormalWebViewController : WBSDKBasicWebViewController {
	id<WBSDKNormalWebRequestDelegate> _delegate;
	NSDictionary* _resultResponseInfo;
}
@property(retain, nonatomic) NSDictionary* resultResponseInfo;	// G=0xd210bd; S=0xd20765; 
@property(retain, nonatomic) id<WBSDKNormalWebRequestDelegate> delegate;	// G=0xd21099; S=0xd210a9; 
-(void).cxx_destruct;	// 0xd210cd
-(void)didFinishAndPassDataToUser;	// 0xd20e31
-(void)didReceiveWithResponseInfo:(id)responseInfo;	// 0xd20e21
-(BOOL)wbsdk_webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;	// 0xd20819
-(void)closeBtnClicked;	// 0xd20809
-(id)urlRequestFromWeiboSDKRequest:(id)weiboSDKRequest andExtraPara:(id)para;	// 0xd20499
-(void)dealloc;	// 0xd20455
@end

