/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface WBSDKBasicButton : XXUnknownSuperclass {
}
-(void)didPressButton:(id)button;	// 0xd45c89
-(id)initWithFrame:(CGRect)frame;	// 0xd45c1d
@end

