/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface WBSDKUtil : XXUnknownSuperclass {
}
+(id)md5:(id)a5;	// 0xd21101
@end

