/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBBaseRequest.h"

@class NSArray, NSString;

@interface WBSDKAppRecommendRequest : WBBaseRequest {
	NSArray* _uids;
	NSString* _access_token;
}
@property(retain, nonatomic) NSString* access_token;	// G=0xd4f2ed; S=0xd4f2fd; 
@property(retain, nonatomic) NSArray* uids;	// G=0xd4f2b5; S=0xd4f2c5; 
+(id)requestWithUIDs:(id)uids access_token:(id)token;	// 0xd4f229
-(void).cxx_destruct;	// 0xd4f325
-(BOOL)canBeReceived;	// 0xd4f2b1
-(BOOL)canBeSent;	// 0xd4f2ad
-(id)init;	// 0xd4f1b9
-(BOOL)canHandleByWeiboClientApp;	// 0xd4f1b5
@end

