/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, UIImageView, UIButton, UIView;

@interface WBSDKWebViewErrorView : XXUnknownSuperclass {
	UIButton* _retryButton;
	UIView* _buttonsContainer;
	UIButton* _closeButton;
	UILabel* _descriptionLabel;
	UIImageView* _imageView;
}
@property(retain, nonatomic) UIImageView* imageView;	// G=0xd2c1c5; S=0xd2c1d5; 
@property(retain, nonatomic) UILabel* descriptionLabel;	// G=0xd2c18d; S=0xd2c19d; 
@property(retain, nonatomic) UIButton* closeButton;	// G=0xd2c155; S=0xd2c165; 
@property(retain, nonatomic) UIView* buttonsContainer;	// G=0xd2c11d; S=0xd2c12d; 
@property(retain, nonatomic) UIButton* retryButton;	// G=0xd2c0e5; S=0xd2c0f5; 
-(void).cxx_destruct;	// 0xd2c1fd
-(void)layoutSubviews;	// 0xd2c0a5
-(void)layout;	// 0xd2bd41
-(void)hide;	// 0xd2bd2d
-(void)showError:(id)error;	// 0xd2bcc1
-(id)initWithFrame:(CGRect)frame;	// 0xd2b455
@end

