/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WBBaseMediaObject.h"

@class NSString;

@interface WBWebpageObject : WBBaseMediaObject {
	NSString* webpageUrl;
}
@property(retain, nonatomic) NSString* webpageUrl;	// G=0xd55095; S=0xd550a5; 
-(void).cxx_destruct;	// 0xd550cd
-(void)loadFromDictionary:(id)dictionary;	// 0xd55009
-(void)storeToDictionary:(id)dictionary;	// 0xd54f6d
-(id)validate;	// 0xd54ee1
@end

