/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class ThumbImage, UIImage, NSString, HJForetellListItemResponseExt, HJSeedLiveResponse, NSURL;

__attribute__((visibility("hidden")))
@interface WeixinActivity : XXUnknownSuperclass {
	UIImage* _icon;
	NSString* _text;
	UIImage* _image;
	ThumbImage* _thumb;
	NSURL* _url;
	HJForetellListItemResponseExt* _foreTellResponse;
	HJSeedLiveResponse* _liveResponse;
}
@property(retain, nonatomic) HJSeedLiveResponse* liveResponse;	// G=0x34c261; S=0x34c271; 
@property(retain, nonatomic) HJForetellListItemResponseExt* foreTellResponse;	// G=0x34c229; S=0x34c239; 
@property(retain, nonatomic) NSURL* url;	// G=0x34c1f1; S=0x34c201; 
@property(retain, nonatomic) ThumbImage* thumb;	// G=0x34c1b9; S=0x34c1c9; 
@property(retain, nonatomic) UIImage* image;	// G=0x34c181; S=0x34c191; 
@property(retain, nonatomic) NSString* text;	// G=0x34c149; S=0x34c159; 
@property(retain, nonatomic) UIImage* icon;	// G=0x34c111; S=0x34c121; 
+(int)activityCategory;	// 0x34b751
-(void).cxx_destruct;	// 0x34c299
-(void)activityDidFinish:(BOOL)activity;	// 0x34c10d
-(void)performActivity;	// 0x34bbd1
-(id)activityViewController;	// 0x34bbcd
-(void)prepareWithActivityItems:(id)activityItems;	// 0x34b9b5
-(BOOL)canPerformWithActivityItems:(id)activityItems;	// 0x34b9b1
-(id)activityImage;	// 0x34b785
-(id)activityTitle;	// 0x34b76d
-(id)activityType;	// 0x34b755
@end

