/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WXAuthInternal : XXUnknownSuperclass {
	NSString* scope;
	NSString* state;
}
@property(retain, nonatomic) NSString* state;	// G=0xcbe2d9; S=0xcbe2e9; 
@property(retain, nonatomic) NSString* scope;	// G=0xcbe2a5; S=0xcbe2b5; 
-(void)dealloc;	// 0xcbe24d
-(id)init;	// 0xcbe201
@end

