/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXOMTAEvent.h"
#import "WXOMTAEventProtocol.h"

@class NSString;

@interface WXOMTAGameUserEvent : WXOMTAEvent <WXOMTAEventProtocol> {
	NSString* _uid;
	NSString* _world;
	NSString* _level;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* level;	// G=0xcd24e9; S=0xcd24f9; 
@property(retain, nonatomic) NSString* world;	// G=0xcd24b5; S=0xcd24c5; 
@property(retain, nonatomic) NSString* uid;	// G=0xcd2481; S=0xcd2491; 
-(void)dealloc;	// 0xcd2409
-(id)init;	// 0xcd23dd
-(void)encode:(id)encode;	// 0xcd2319
-(int)getType;	// 0xcd2311
@end

