/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface WXOMTAPasteboard : XXUnknownSuperclass {
}
+(id)getCompanyDomain;	// 0xcd42f9
+(id)get:(id)get;	// 0xcd425d
+(void)set:(id)set value:(id)value;	// 0xcd41e9
@end

