/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface WXOMTAOpenUDID : XXUnknownSuperclass {
}
+(void)setOptOut:(BOOL)anOut;	// 0xcd820d
+(id)valueWithError:(id*)error;	// 0xcd7ae9
+(id)value;	// 0xcd7ac9
+(id)_generateFreshOpenUDID;	// 0xcd797d
+(id)_getDictFromPasteboard:(id)pasteboard;	// 0xcd7825
+(void)_setDict:(id)dict forPasteboard:(id)pasteboard;	// 0xcd77e1
@end

