/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "living-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView;

__attribute__((visibility("hidden")))
@interface WXShiftCircle : XXUnknownSuperclass {
	int _littleCircleCorner;
	UIView* _littleView;
}
@property(assign, nonatomic) __weak UIView* littleView;	// G=0x1b4999; S=0x1b49b9; 
@property(assign, nonatomic) int littleCircleCorner;	// G=0x1b4989; S=0x1b4851; 
-(void).cxx_destruct;	// 0x1b49cd
-(void)layoutSubviews;	// 0x1b48b9
-(id)initWithFrame:(CGRect)frame;	// 0x1b45c9
@end

