/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ZZCrashKit : XXUnknownSuperclass {
}
+(/*function-pointer*/ void*)getHandler;	// 0x344db5
+(void)setDefaultHandler;	// 0x344da5
-(id)applicationDocumentsDirectory;	// 0x344d65
@end

